### ISSUE TITLE
build_pa 编译成功，但没有生成ipa文件

### ISSUE THREAD

**Issue by purplepeng** [FIRHQ/fir-cli#10]
使用 fir build_ipa ./ -o ./ 编译成功，当前目录下生成了build目录和dSYM文件，但没有ipa文件，请教下是怎样回事，谢谢？

**Comment by NaixSpirit** [comment]
@purplepeng 方便把 build 时候的 log 贴出来吗?

**Comment by purplepeng** [comment]
/usr/bin/codesign --force --sign 6BCF7DA50E7D4264FFF79B82938980C64EAE9FE3 --entitlements /Users/PURPLEPENG/Documents/ipa\ build\ distribute/fir.im/marathon/build/marathon.build/Release-iphoneos/marathon.build/marathon.app.xcent /var/folders/3y/q_lrv8s56wlc5kv0r8g_35nh0000gn/T/d20150813-19072-6usr2g/marathon.app

Validate /var/folders/3y/q_lrv8s56wlc5kv0r8g_35nh0000gn/T/d20150813-19072-6usr2g/marathon.app
    cd "/Users/PURPLEPENG/Documents/ipa build distribute/fir.im/marathon"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PRODUCT_TYPE=com.apple.product-type.application
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/Validation /var/folders/3y/q_lrv8s56wlc5kv0r8g_35nh0000gn/T/d20150813-19072-6usr2g/marathon.app

** BUILD SUCCEEDED **


I, [2015-08-13T10:27:01.885347 #19072]  INFO -- : Build Success
I, [2015-08-13T10:27:01.885642 #19072]  INFO -- :

**Comment by NaixSpirit** [comment]
@purplepeng `fir build_ipa` 命令从本质上来说是对 `xcodebuild` 命令的封装.
从 log 上来看是 build 成功了,  可以试试在项目目录下直接运行 `xcodebuild build -sdk iphoneos` 命令看看是否能 build 成功

**Comment by purplepeng** [comment]
多谢，我在工程目录运行 xcodebuild build -sdk iphoneos 命令，执行结果和fir build_ipa一致，提示log和上面一致；但没有生成ipa文件；是没有archive吗？

**Comment by NaixSpirit** [comment]
`xcodebuild build -sdk iphoneos` 命令只会生成 `.app` 的包,  默认会在该项目下生成一个 **build** 文件夹, 检查下 `build/Release-iphoneos/xxxx.app` 这个目录下是否有 xxx.app, 如果没有, 那么就是 xcode 没有设置正确

**Comment by purplepeng** [comment]
build/Release-iphoneos/xxxx.app 目录下有xxx.app生成；
我用下面的xcodebuild命令可以生成导出ipa包：
* xcodebuild clean install
* xcodebuild -project marathon.xcodeproj -scheme marathon archive -archivePath ./
* xcodebuild -exportArchive -exportFormat IPA -archivePath ../marathon.xcarchive -exportPath ./
fir build_ipa ./ -o ./ 是不是没有包含xcodebuild 的archive action？

**Comment by NaixSpirit** [comment]
`archive action` 实际上就是 zip, 所以 fir-cli 在最后会调用 zip 命令
> https://github.com/FIRHQ/fir-cli/blob/master/lib/fir/util/build_ipa.rb#L126-L135

我觉得最终没有生成 ipa 包可能是因为没有加入 -scheme 命令

试试 `fir build_ipa ./ -o ./ -S marathon `

**Comment by purplepeng** [comment]
fail again...
当前目录下生成了build目录和dSYM文件，但没有ipa文件

**Comment by NaixSpirit** [comment]
直接 `fir build_ipa` 然后看看当前目录下的  `fir_build_ipa` 目录下有什么东西?

**Comment by purplepeng** [comment]
只有xxx.app.dSYM文件

**Comment by NaixSpirit** [comment]
@purplepeng 是的, 我这边是生成了 ipa 文件了
那就需要你详细的 log 了, 需要把 build 时候的全部 log 发给我
我的邮箱 hxy@fir.im

**Comment by purplepeng** [comment]
多谢；找到问题原因了，应该是我工程设置的原因；换了其他项目是可以生成ipa包的。
