### ISSUE TITLE
插件很给力，提个建议

### ISSUE THREAD

**Issue by Damon2999** [FIRHQ/fir-cli#100]
能不能加上重签名和prifile签名文件的功能，比如我自己用的编译命令是cocoapods-build "${WORKSPACE}/${ipaBuildPath} -g \"${code_sign}\" -f ${profile}"
其中-g和-f是做重签名用的，因为代码库拉下来的签名不一定是所需要的，得用xcode打开改很麻烦，不知道这个功能是否有需求。

**Comment by yaochenfeng** [comment]
赞同添加重签名和proifile签名功能，最好还有修改包名，就企业版和开发版都能使用了

**Comment by jw10126121** [comment]
这个功能一直都有啊。 我都有在用着，但是目前xcode8的自动签名用了的话，就不能重签名了
