### ISSUE TITLE
xcode8设置了automatically manager signing后，不能打包

### ISSUE THREAD

**Issue by jw10126121** [FIRHQ/fir-cli#102]
xcode8设置了automatically manager signing后，不能打包
fir bi ~/Documents/SmartSVN/GYFD/DemoPro -w -S DemoPro -C Release -o ~/Desktop/IpaList/GYLivePro PRODUCT_BUNDLE_IDENTIFIER="com.xxxx.DemoPro" PROVISIONING_PROFILE="xxxxxxxxxxx" CODE_SIGN_IDENTITY="iPhone Distribution: xxxxx Co., Ltd."  -Q -p -T xxxxxxxx -c “最新版本”

会提示，我在打包的时候，设置了证书名和profile信息

DemoPro has conflicting provisioning settings. DemoPro is automatically signed, but provisioning profile DisProfileLivePro has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

目前，我的解决方法是，取消automatically manager signing 

请问，有没有更好的解决方法。

**Comment by sanlengjingvv** [comment]
https://testerhome.com/topics/5954 回复有些讨论

**Comment by lionnner** [comment]
将你的 "PRODUCT_BUNDLE_IDENTIFIER="com.xxxx.DemoPro" PROVISIONING_PROFILE="xxxxxxxxxxx" CODE_SIGN_IDENTITY="iPhone Distribution: xxxxx Co., Ltd."" 替换成 " PROVISIONING_PROFILE_VALUE="Automatic" DEVELOPMENT_TEAM=XXXXX " 
然后不管你勾选没勾选 应该都可以了。
