### ISSUE TITLE
PhaseScriptExecution

### ISSUE THREAD

**Issue by JamCode** [FIRHQ/fir-cli#103]
## 请问这类错误是什么含义

> - The following build commands failed:
>   PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/wangjam/Library/Developer/Xcode/DerivedData/moneyiOS-fqpazxdxfvcthkchuotjrhxlandb/Build/Intermediates/moneyiOS.build/Debug-iphoneos/UATmoneyiOS.build/Script-B2458C8C1D59BA6700AF0815.sh

**Comment by JamCode** [comment]
编译命令如下

> fir build_ipa -w -S UATmoneyiOS

**Comment by zenghaojim33** [comment]
+ 1

The following build commands failed:
	PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/pro/Library/Developer/Xcode/DerivedData/Aipai-azorboawtgoxomfyhlzrljhiyfjq/Build/Intermediates/Aipai.build/Release-iphoneos/Aipai.build/Script-929BF7B3F7CE00B621343FAB.sh

**Comment by rickywbl** [comment]
+1   同样的问题 一直编译失败

**Comment by LanCat** [comment]
+1 同样的问题 一直编译失败
