### ISSUE TITLE
Invalid date/time in zip entry

### ISSUE THREAD

**Issue by hamberluo** [FIRHQ/fir-cli#105]
在使用命令行上传 apk 时出现以上信息（多行），但是上传还是成功的

ps：出现这个问题是在升级到 as 2.2 以后

**Comment by lionel126** [comment]
搜到这个了： http://stackoverflow.com/questions/27840214/rubyzip-error-causing-havoc-in-my-logs

**Comment by Rosepotato** [comment]
产生这个问题的原因可以看一下这个连接 https://github.com/calabash/calabash-android/issues/769。解决问题的方法：change **warning_invalid_date = true** to **waring_invalid_date = false** in ~/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/rubyzip-1.2.1/lib/zip.rb
