### ISSUE TITLE
'fir' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by lolstudio** [FIRHQ/fir-cli#114]
构建失败，问题详细情况：
1：在jenkins上的构建配置为 **构建** 中的 **Execute Windows batch command** 执行命令为
`fir publich ./app/build/outputs/apk/release/*.apk -T xxxtokenxxx --changelog="Uploaded by fir-cli jenkins" -Q`,
如果勾选为 **Execute shell** 则运行失败错误为
 $ sh -xe C:\Windows\TEMP\hudson6419396661621713971.sh
The system cannot find the file specified
FATAL: command execution failed
java.io.IOException: Cannot run program "sh"` 
**说明：远程连接到server(jenkins 服务器)后，手动进入该项目目录在命令行敲击该命令可以正常上传到fir上**

2：如1所说，在命令行上传后在项目目录没有找到生成的二维码图片，是不是命令配置错了？看到输出了"Published succeed: http://fir.im/xxxx" 请问怎么捕获这个值做后期处理

**Comment by lolstudio** [comment]
重新在 **Execute Windows batch command** 中执行如下命令`cmd -c fir publich ./app/**/*.apk -T xxxtokenxxx --changelog="Uploaded by fir-cli jenkins" -Q`
不会报错，但是不会上传到fir平台，日志如下
BUILD SUCCESSFUL

Total time: 1 mins 20.69 secs
Build step 'Invoke Gradle script' changed build result to SUCCESS
[xxx] $ cmd /c call C:\Windows\TEMP\hudson33xxx06.bat

C:\Program Files (x86)\Jenkins\workspace\androidBuild\xxx>cmd -c fir publich ./app/**/*.apk -T xxxtokenxxx --changelog="Uploaded by fir-cli jenkins" -Q 
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Program Files (x86)\Jenkins\workspace\androidBuild\xxx>
C:\Program Files (x86)\Jenkins\workspace\androidBuild\xxx>exit 0 
Sending e-mails to: xxx@xxx.com
Finished: SUCCESS
请协助，感谢 :sos: :sos: :sos:

**Comment by lolstudio** [comment]
已解决，得在jenkins系统管理添加path环境变量，不用添加cmd，最终命令
`fir publish ./app/**/*.apk -T xxxtokenxxx --changelog="Uploaded by fir-cli jenkins" -Q`

**Comment by yjukh5** [comment]
添加的是那个的环境变量
