### ISSUE TITLE
Unable to log in my account in Mac terminal, what reason is this?

### ISSUE THREAD

**Issue by xygkevin** [FIRHQ/fir-cli#117]
bogon:XKJY 2017-03-04 18-03-07 XXXXXXXXX$ fir login ea2dee6ba81f34125dc3baaexxxxxxxx
E, [2017-03-04T19:58:51.715376 #39690] ERROR -- : key not found: :ciphers
I, [2017-03-04T19:58:51.715473 #39690]  INFO -- : Retry in 5 times......
E, [2017-03-04T19:58:51.724775 #39690] ERROR -- : key not found: :ciphers
I, [2017-03-04T19:58:51.724817 #39690]  INFO -- : Retry in 4 times......
E, [2017-03-04T19:58:51.735065 #39690] ERROR -- : key not found: :ciphers
I, [2017-03-04T19:58:51.735114 #39690]  INFO -- : Retry in 3 times......
E, [2017-03-04T19:58:51.744505 #39690] ERROR -- : key not found: :ciphers
I, [2017-03-04T19:58:51.744551 #39690]  INFO -- : Retry in 2 times......
E, [2017-03-04T19:58:51.754170 #39690] ERROR -- : key not found: :ciphers
I, [2017-03-04T19:58:51.754226 #39690]  INFO -- : Retry in 1 times......
E, [2017-03-04T19:58:51.766278 #39690] ERROR -- : key not found: :ciphers

**Comment by woohyuknrg** [comment]
i have the same issue

**Comment by wangsu2004** [comment]
me to

**Comment by CaffreySun** [comment]
me too
