### ISSUE TITLE
ERROR -- : key not found: :ciphers

### ISSUE THREAD

**Issue by MIyulong** [FIRHQ/fir-cli#118]
刚装的fir，使用fir login输入token时、一直登录失败ERROR -- : key not found: :ciphers

**Comment by huhood** [comment]
+1

**Comment by Starryxu** [comment]
+1

**Comment by Starryxu** [comment]
+1

**Comment by huhood** [comment]
请使用ruby2.3.1，就可以了，最新的貌似说有问题

**Comment by MIyulong** [comment]
thanks , to use ruby2.3.1 to solve problem

**Comment by zijing07** [comment]
这个就修复了吗？就为了使用fir降级rvm有点不爽啊
