### ISSUE TITLE
fir-cli 如何打包企业证书

### ISSUE THREAD

**Issue by xumeng** [FIRHQ/fir-cli#119]
之前在jenkins里面用 fir b xxx -w -S xxxx -p -T xxxx是可以打出企业版的app的，
后来不知道什么时候开始就打的是企业账号的内测版了。
试着加-f参数，会报错：
 xcodebuild: error: The flag -exportArchive is required when specifying -exportProvisioningProfile.
xcodebuild: error: The flag -archivePath is required when specifying -exportArchive.

用DEBUG=1后的xcodebuild加上对应参数，会报错：
xcodebuild: error: The flag -scheme cannot be specified along with -exportArchive.
xcodebuild: error: The flag -exportPath is required when specifying -exportArchive.
xcodebuild: error: The flag -archivePath is required when specifying -exportArchive.

**Comment by su350380433** [comment]
大神 要打发布到app store的包要怎么打
