### ISSUE TITLE
Publish貌似SSL证书报错

### ISSUE THREAD

**Issue by smilelu** [FIRHQ/fir-cli#122]
I, [2017-03-22T14:52:22.941812 #5523]  INFO -- : Publishing app via xx<xxx@xxxxx.com>.......
I, [2017-03-22T14:52:22.941874 #5523]  INFO -- : ✈ -------------------------------------------- ✈
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
I, [2017-03-22T14:52:24.235641 #5523]  INFO -- : Fetching xxxxxxxxxxx@fir.im uploading info......
I, [2017-03-22T14:52:24.235690 #5523]  INFO -- : Uploading app: xxxxx-1.8.0(Build 21)
warning: Overriding "Content-Type" header "application/json" with "application/x-www-form-urlencoded" due to payload
I, [2017-03-22T14:52:24.391240 #5523]  INFO -- : Uploading app icon......
I, [2017-03-22T14:52:24.391307 #5523]  INFO -- : Converting app's icon......
warning: Overriding "Content-Type" header "application/json" with "multipart/form-data; boundary=----RubyFormBoundary5Nrkzv6mD2WBtbun" due to payload
E, [2017-03-22T14:52:26.290432 #5523] ERROR -- : SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
I, [2017-03-22T14:52:26.290474 #5523]  INFO -- : Retry 1 times......
E, [2017-03-22T14:52:28.292145 #5523] ERROR -- : closed stream
I, [2017-03-22T14:52:28.292181 #5523]  INFO -- : Retry 2 times......
E, [2017-03-22T14:52:30.297601 #5523] ERROR -- : closed stream
I, [2017-03-22T14:52:30.297640 #5523]  INFO -- : Retry 3 times......
E, [2017-03-22T14:52:32.302348 #5523] ERROR -- : closed stream
I, [2017-03-22T14:52:32.302380 #5523]  INFO -- : Retry 4 times......
E, [2017-03-22T14:52:34.305253 #5523] ERROR -- : closed stream
I, [2017-03-22T14:52:34.305285 #5523]  INFO -- : Retry 5 times......
E, [2017-03-22T14:52:36.309235 #5523] ERROR -- : closed stream

**Comment by newbdez33** [comment]
same here

**Comment by JesseZhu** [comment]
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by newbdez33** [comment]
应该是用了系统的ruby版本导致的，换个rvm环境就可以，比如：
`rvm use ruby-2.2.3`

**Comment by zhaochangwu** [comment]
我又出现了相同的问题, 问题解决了吗, 换了rvm环境 也没用

**Comment by youyisx** [comment]
这个问题怎么解啊，我也遇到了，切ruby环境也没有

**Comment by smilelu** [comment]
到现在也没解决，😭，换ruby版本没用

**Comment by youyisx** [comment]
# Install Homebrew:
$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install RVM:
$ \curl -sSL https://get.rvm.io | bash -s stable --ruby

$ gem install fir-cli
$ export PATH=/usr/local/bin:$PATH;gem install -n /usr/local/bin fir-cli
$ echo 'gem: --bindir /usr/local/bin' >> ~/.gemrc
$ gem install fir-cli

重新按这个流程走了一次，然后重启，就好了....

**Comment by mengxianliang** [comment]
我也遇到了这样的情况，最后在RubyChina(https://gems.ruby-china.org)上找到了解决办法。原文是：如果遇到 SSL 证书问题，你又无法解决，请直接用 http://gems.ruby-china.org 避免 SSL 的问题。
1、先看一下自己使用的ruby源地址
$ gem source -l
如果是 https://gems.ruby-china.org
执行下一步
2、删除这个原地址
$ gem source -r https://gems.ruby-china.org
3、添加新地址
$ gem source -a http://gems.ruby-china.org
