### ISSUE TITLE
Xcode 8.3 打包错误

### ISSUE THREAD

**Issue by calvingit** [FIRHQ/fir-cli#123]
报错误如下：

```bash
xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH
```

**Comment by huhood** [comment]
+1

**Comment by Kenshinhu** [comment]
+1

**Comment by zzjzz9266a** [comment]
+1

**Comment by Kitty2014** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-43163  17:01:25 ** BUILD SUCCEEDED **
17:01:25 
17:01:25 
17:01:25 I, [2017-03-29T17:01:25.045239 #4498]  INFO -- : Archiving......
17:01:25 I, [2017-03-29T17:01:25.045281 #4498]  INFO -- : ✈ -------------------------------------------- ✈
17:01:26 xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH
17:01:26 I, [2017-03-29T17:01:26.453258 #4498]  INFO -- : 
17:01:26 E, [2017-03-29T17:01:26.453471 #4498] ERROR -- : Archive failed
17:01:26 Build step 'Execute shell' marked build as failure
17:01:26 Finished: FAILURE

**Comment by Kitty2014** [comment]
https://github.com/jenkinsci/xcode-plugin/pull/76/commits/de240a9c2e192fba7d8c6d7509b9e8c00b102307   any  update？

**Comment by CaffreySun** [comment]
+1

**Comment by zzjzz9266a** [comment]
![image](https://cloud.githubusercontent.com/assets/17211710/24452356/6ec4edae-14b5-11e7-988f-1848d7813435.png)

我已经选择自己用命令行打包了

**Comment by calvingit** [comment]
Xcode 8.3去掉了PackageApplication，改用fastlane了

**Comment by mqlsq** [comment]
+1

**Comment by mqlsq** [comment]
那如何解决呢?

**Comment by NaixSpirit** [comment]
@jicheng1014 @yunheli 使用 xcodebuild 原生命令

```shell
# Create an archive
xcodebuild -alltargets -configuration "${CONFIGURATION}" -scheme "${SCHEME}" -archivePath "${APP_PATH}/${PROJECT}.xcarchive" archive

# Create the IPA file from the archive
xcodebuild -exportProvisioningProfile "${PROVISIONING_PROFILE_NAME}" -exportArchive -exportFormat IPA -archivePath "${APP_PATH}/${PROJECT}.xcarchive" -exportPath "${IPA_DIR}/${PROJECT}.ipa" CODE_SIGN_IDENTITY="${SIGNING_IDENTITY}"
```

重写 https://github.com/FIRHQ/fir-cli/blob/master/lib/fir/util/build_ipa.rb#L65-L72 部分逻辑

**Comment by Kitty2014** [comment]
@NaixSpirit 这个会更新在fir-cli里面么

**Comment by calvingit** [comment]
最新版本已经解决，关闭问题
