### ISSUE TITLE
1.6 版本中打包出现“no implicit conversion of nil into String”

### ISSUE THREAD

**Issue by Kenshinhu** [FIRHQ/fir-cli#126]
fir build_ipa xxx.xcodeproj -w -S target_name

.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/pathname.rb:337:in `initialize'
.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/pathname.rb:337:in `new'
.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/pathname.rb:337:in `+'
.rvm/gems/ruby-2.2.4/gems/xcodeproj-1.4.3/lib/xcodeproj/project.rb:97:in `open'
.rvm/gems/ruby-2.2.4/gems/fir-cli-1.6.0/lib/fir/util/build_ipa.rb:141:in `find_build_setting'
.rvm/gems/ruby-2.2.4/gems/fir-cli-1.6.0/lib/fir/util/build_ipa.rb:36:in `initialize_ipa_build_cmd'
.rvm/gems/ruby-2.2.4/gems/fir-cli-1.6.0/lib/fir/util/build_ipa.rb:11:in `build_ipa'
.rvm/gems/ruby-2.2.4/gems/fir-cli-1.6.0/lib/fir/cli.rb:50:in `build_ipa'
.rvm/gems/ruby-2.2.4/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
.rvm/gems/ruby-2.2.4/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
.rvm/gems/ruby-2.2.4/gems/fir-cli-1.6.0/lib/fir/cli.rb:181:in `invoke_command'
.rvm/gems/ruby-2.2.4/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
.rvm/gems/ruby-2.2.4/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
.rvm/gems/ruby-2.2.4/gems/fir-cli-1.6.0/bin/fir:8:in `<top (required)>'
.rvm/gems/ruby-2.2.4/bin/fir:23:in `load'
.rvm/gems/ruby-2.2.4/bin/fir:23:in `<main>'
.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mqlsq** [comment]
也遇到了同样的问题

**Comment by WangWenzhuang** [comment]
我也有这样的问题

no implicit conversion of nil into String
/Users/wangwenzhuang/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/pathname.rb:349:in `initialize'
/Users/wangwenzhuang/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/pathname.rb:349:in `new'
/Users/wangwenzhuang/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/pathname.rb:349:in `+'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0@global/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:97:in `open'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/fir-cli-1.6.1/lib/fir/util/build_ipa.rb:141:in `find_build_setting'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/fir-cli-1.6.1/lib/fir/util/build_ipa.rb:36:in `initialize_ipa_build_cmd'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/fir-cli-1.6.1/lib/fir/util/build_ipa.rb:11:in `build_ipa'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/fir-cli-1.6.1/lib/fir/cli.rb:50:in `build_ipa'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/fir-cli-1.6.1/lib/fir/cli.rb:181:in `invoke_command'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/gems/fir-cli-1.6.1/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:22:in `load'
/usr/local/bin/fir:22:in `<main>'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/wangwenzhuang/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by kemchenj** [comment]
```shell
no implicit conversion of nil into String
/Users/kemchenj/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/pathname.rb:337:in `initialize'
/Users/kemchenj/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/pathname.rb:337:in `new'
/Users/kemchenj/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/pathname.rb:337:in `+'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:97:in `open'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/fir-cli-1.6.1/lib/fir/util/build_ipa.rb:141:in `find_build_setting'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/fir-cli-1.6.1/lib/fir/util/build_ipa.rb:36:in `initialize_ipa_build_cmd'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/fir-cli-1.6.1/lib/fir/util/build_ipa.rb:11:in `build_ipa'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/fir-cli-1.6.1/lib/fir/cli.rb:50:in `build_ipa'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/fir-cli-1.6.1/lib/fir/cli.rb:181:in `invoke_command'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/gems/fir-cli-1.6.1/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:22:in `load'
/usr/local/bin/fir:22:in `<main>'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
/Users/kemchenj/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'
```

我也是有这样的问题

**Comment by yang-guo-2016** [comment]
问题已在 1.6.2 中修复

**Comment by kemchenj** [comment]
```shell
[2017-04-05T10:39:46.433098 #14810] ERROR -- : The xcodeproj file is missing, check the BUILD_DIR
```

@yang-guo-2016

**Comment by Kenshinhu** [comment]
@yang-guo-2016 1.6.3 版本中如果路径中有空白字符也会出来上面的问题
