### ISSUE TITLE
undefined method `deep_symbolize_keys' for false:FalseClass

### ISSUE THREAD

**Issue by xiaoqi-zhang** [FIRHQ/fir-cli#127]
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.0/lib/fir/util/config.rb:21:in `config'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.0/lib/fir/util/login.rb:11:in `login'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.0/lib/fir/cli.rb:125:in `login'
/usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.0/lib/fir/cli.rb:181:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.0/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:22:in `load'
/usr/local/bin/fir:22:in `<main>'

**Comment by xuezou** [comment]
I  got the same issue .Is there anyone figure it out?
There are two macbook difference in ruby version ,one is 2.4.0 got successful when fun 'fir login xxx' ,the other one get this error has ruby with version 2.0.0.
Is it the key point ? I am not sure.

**Comment by linet** [comment]
I also got the same issue. Is there anyone figure it out？

**Comment by linet** [comment]
I solve this problem.
Solution:
Delete the file ~/.fir-cli, and login angain.

**Comment by shiwensong** [comment]
@linet 
Where are the file ~/.fir-cli?I didn't find it. Please give advice or comments
