### ISSUE TITLE
xcode 8.3打包出现 The xcworkspace file is missing, check the BUILD_DIR

### ISSUE THREAD

**Issue by brightli** [FIRHQ/fir-cli#133]

**Comment by sigarron** [comment]
附议，同样的问题

**Comment by kemchenj** [comment]
@brightli @sigarron 

> 该指令在指向的目录中，找到第一个 workspace 文件, 对其进行编译.

我猜你们的命令应该是下面这样:

```shell
fir build_ipa Example/Example.workspace --workspace
```

试一下改成下面这样, 应该就可以了

```shell
fir build_ipa Example --workspace
```

**Comment by sigarron** [comment]
@kemchenj 
一样的，没有差别。

**Comment by vbonluk** [comment]
我更新了Xcode8.3也出现了这样的问题，并且执行了fir upgrade，更新到最新版。还是有问题

**Comment by vbonluk** [comment]
我使用的是jenkins：
fir build_ipa ${WORKSPACE} -o ${WORKSPACE}/ipa -p -c ${changelog} -Q -T ************
错误：
The xcworkspace file is missing, check the BUILD_DIR
说明：
${WORKSPACE}对应的是/Users/Vbon/.jenkins/jobs/xfj/workspace
.xcodeproj文件就在这个路径下面。

以前一直没有问题的。更新了xcode8.3就出现了。

**Comment by qingwen07** [comment]
附议，同样的问题

**Comment by protosse** [comment]
我今天也遇到这个问题了，之前的都是好好的。
