### ISSUE TITLE
I, [2017-04-19T19:13:33.996541 #77619]  INFO -- : RVM detected, forcing to use system ruby since xcodebuild cause error Now using system ruby. ** EXPORT FAILED **

### ISSUE THREAD

**Issue by crassusxst** [FIRHQ/fir-cli#137]
更新fir-cli 版本到1.6.3 打包提示以下错误：
I, [2017-04-19T19:13:33.996541 #77619]  INFO -- : RVM detected, forcing to use system ruby since xcodebuild cause error
Now using system ruby.
** EXPORT FAILED **

命令使用
fir build_ipa workspace目录 -w -S scheme -o 输出目录 -C Release  -p -T token

**Comment by XConstantine** [comment]
+1

**Comment by XConstantine** [comment]
@crassusxst 应该是你的Provisioning Profile的问题，fir-cli默认是ad-hoc类型，你可以重新创建一个对应的ad-hoc类型的Provisioning Profile重新试一下
