### ISSUE TITLE
release  打包成功 ，但是没成功导出

### ISSUE THREAD

**Issue by roselind** [FIRHQ/fir-cli#147]
日志 ：
PCloudUser.app.dSYM

** ARCHIVE SUCCEEDED **

I, [2017-06-09T12:43:08.337524 #30318]  INFO -- : Archiving......
I, [2017-06-09T12:43:08.337616 #30318]  INFO -- : ✈ -------------------------------------------- ✈
I, [2017-06-09T12:43:08.337678 #30318]  INFO -- : Generated plist file for exportOptionsPlist argument
I, [2017-06-09T12:43:08.337719 #30318]  INFO -- : {
I, [2017-06-09T12:43:08.337767 #30318]  INFO -- :   teamID:2S9N7AT33T
I, [2017-06-09T12:43:08.337801 #30318]  INFO -- :   method:release
I, [2017-06-09T12:43:08.337826 #30318]  INFO -- :   uploadSymbols:true
I, [2017-06-09T12:43:08.337980 #30318]  INFO -- :   uploadBitcode:false
I, [2017-06-09T12:43:08.338017 #30318]  INFO -- : }
I, [2017-06-09T12:43:09.819530 #30318]  INFO -- : RVM detected, forcing to use system ruby since xcodebuild cause error
Now using system ruby.
** EXPORT FAILED **

但是 adhot 版本打包成功 导出 也成功了

**Comment by crossPQW** [comment]
我之前也遇到过这个问题，后来是发现没有加`-E`参数导致的，这个参数有几个可选值`app-store, package, ad-hoc, enterprise, development, develpoer-id`，如果是发布到 appstore 的话就选 app-store，其他还有 ad-hoc 活着 enterprise 自己按需添加了。

**Comment by roselind** [comment]
哦哦 ，原来是这样  ，O(∩_∩)O谢谢
