### ISSUE TITLE
使用fir-cli上传apk，图标会变

### ISSUE THREAD

**Issue by Nstd** [FIRHQ/fir-cli#15]
环境：
windows 7
在jenkins中使用cygwin的sh.exe命令执行shell脚本（脚本内容是用fir-cli上传apk）

如题，图标会变成这样：
![image](https://cloud.githubusercontent.com/assets/3004225/9520210/bc82fa18-4cf7-11e5-943f-b2cbab57a30c.png)

**Comment by lanceli** [comment]
ipa也是

**Comment by NaixSpirit** [comment]
待会我看下

**Comment by NaixSpirit** [comment]
目前已经更换一种转换 icon  的方式, 等我出新版本

**Comment by NaixSpirit** [comment]
@lanceli 已经确认在 win8 环境下无法使用 fir-cli 上传 ipa

**Comment by ufolux** [comment]
osx10.11 下 fir-cli上传以后图标也会变

**Comment by NaixSpirit** [comment]
@lanceli @Nstd @ufolux 抱歉这个 issue 改了这么久, 目前这个问题已经有了很好的解决方案, 我正在测试, 本周末左右可以上线

**Comment by lanceli** [comment]
:100:

**Comment by NaixSpirit** [comment]
@lanceli @Nstd @ufolux 请安装 1.3.5 版本

**Comment by lolstudio** [comment]
同遇到这个问题，使用的fir-cli版本是1.5.0,上传到fir后显示的是默认图片，附上日志

I, [2017-01-06T13:19:16.624778 #6760]  INFO -- : Publishing app via xxx<xxx@qq.com>.......
I, [2017-01-06T13:19:16.624778 #6760]  INFO -- : 鉁� -------------------------------------------- 鉁�
I, [2017-01-06T13:19:18.746378 #6760]  INFO -- : Fetching com.xxx.xxx@fir.im uploading info......
I, [2017-01-06T13:19:18.746378 #6760]  INFO -- : Uploading app: xxx1.x.x(Build x)
I, [2017-01-06T13:19:18.949178 #6760]  INFO -- : Uploading app icon......
I, [2017-01-06T13:19:18.949178 #6760]  INFO -- : Converting app's icon......
I, [2017-01-06T13:19:40.002578 #6760]  INFO -- : Uploading app binary......
I, [2017-01-06T13:19:52.657178 #6760]  INFO -- : Updating app info......
I, [2017-01-06T13:19:53.000378 #6760]  INFO -- : Fetch app info from fir.im
I, [2017-01-06T13:19:53.109578 #6760]  INFO -- : 鉁� -------------------------------------------- 鉁�
I, [2017-01-06T13:19:53.109578 #6760]  INFO -- : Published succeed: http://fir.im/xxxx
I, [2017-01-06T13:19:53.218778 #6760]  INFO -- : Local qrcode file: C:/Program Files (x86)/xxx/xxx/app/build/outputs/apk/release/fir-xxx.png
I, [2017-01-06T13:19:53.218778 #6760]  INFO -- : `
