### ISSUE TITLE
fir publish 的时候能否跟上更新日志

### ISSUE THREAD

**Issue by y500** [FIRHQ/fir-cli#154]
在fir publish的时候能否加上-m之类的参数，加上更新日志，免得每次上传完还要到网页上编辑

**Comment by YasinZhou** [comment]
/usr/local/bin/fir publish ${upload_path}/${ipaName} -c ${upload_path}/${log_file_name}
#修改环境语言，否则fir上传日志中文不显示
export LANG="en_US.UTF-8"

**Comment by NaixSpirit** [comment]
```sh
$ fir publish --help
Usage:
  fir publish APP_FILE_PATH

Options:
 ...
  -L, [--logfile=LOGFILE]          # Path to writable logfile
 ...
```

**Comment by y500** [comment]
got it.
