### ISSUE TITLE
gem install fir-cli安装报错

### ISSUE THREAD

**Issue by wchengyu** [FIRHQ/fir-cli#155]
gem install fir-cli
ERROR:  SSL verification error at depth 1: unable to get local issuer certificate (20)
ERROR:  You must add /O=Digital Signature Trust Co./CN=DST Root CA X3 to your local trusted store
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

**Comment by leibaozai** [comment]
我的也报错，同求解
gem install fir-cli
Fetching: thor-0.19.4.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Library/Ruby/Gems/2.3.0/cache/thor-0.19.4.gem

**Comment by NaixSpirit** [comment]
参考 [常见的安装问题](https://github.com/FIRHQ/fir-cli/blob/master/doc/install.md#常见的安装问题)

**Comment by hnxyzhw** [comment]
$ echo 'gem: --bindir /usr/local/bin' >> ~/.gemrc
$ sudo gem install fir-cli
用了第三个解决办法，最后用管理员权限装成功了
