### ISSUE TITLE
windows下不能提交多行日志

### ISSUE THREAD

**Issue by Nstd** [FIRHQ/fir-cli#16]
环境：
windows 7
cygwin

```
comment="test1
test2
test3"
fir.bat p application_path -T user_token -c "$comment"
```

只有第一行注释：test1会被提交

**Comment by NaixSpirit** [comment]
windows 换行是使用 "\r\n" 吧

**Comment by Nstd** [comment]
意思是要把\r\n替换为\n吗？

**Comment by NaixSpirit** [comment]
@Nstd \r\n 还是不行吗?

**Comment by Nstd** [comment]
@NaixSpirit 还是不行，我们把jenkins改到mac下了:)

**Comment by NaixSpirit** [comment]
@Nstd fir-cli 对 windows 的支持不怎么好, 尽量使用 linux 或者 mac osx 系统吧

**Comment by NaixSpirit** [comment]
@Nstd 1.3.7 版本直接直接从文件读取 changelog 了

**Comment by Nstd** [comment]
@NaixSpirit 好的，多谢~
