### ISSUE TITLE
update to Xcode 9 build ipa error

### ISSUE THREAD

**Issue by vbonluk** [FIRHQ/fir-cli#160]
commend in jenkins:

fir build_ipa xxxx.xcodeproj -S xx -o xxx/ipa -p -c 'aa' -Q -T xxxxxxxxxxxx

error:

Error Domain=IDEProvisioningErrorDomain Code=9 ""xxx.app" requires a provisioning profile with the Push Notifications feature." UserInfo={NSLocalizedDescription="xxx.app" requires a provisioning profile with the Push Notifications feature., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

**Comment by iStig** [comment]
https://github.com/FIRHQ/fir-cli/issues/161
看起来是同一个问题
