### ISSUE TITLE
Xcode更新到9之后,打包失败.

### ISSUE THREAD

**Issue by mqlsq** [FIRHQ/fir-cli#161]
前几天更新到xcode9,然后打包就一直失败,提示是provisioning找不到.

**Comment by mqlsq** [comment]
Error Domain=IDEProvisioningErrorDomain Code=9 ""Hasrdaily.app" requires a provisioning profile with the Push Notifications and Associated Domains features." UserInfo={NSLocalizedDescription="xxx.app" requires a provisioning profile with the Push Notifications and Associated Domains features., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

**Comment by AngryPudge** [comment]
xcodebuild -help,查看最新说明，需要在exportOptions.plist中添加profile相关配置

**Comment by iStig** [comment]
@AngryPudge 
通过[这篇文章](http://www.sgfblog.com/archives/614#comments)
我能理解exportOptions.plist需要增加provisioningProfiles的配置说明
但是目前不知道exportOptions.plist中需要创建在哪里使用。等待继续查资料看看

**Comment by fujijing** [comment]
@iStig  
        你好，我是在exportOptions.plist增加provisioningProfiles配置之后执行脚本的，但是 export 失败，原因是存放exportOptions.plist路径的文件打不开

> The file “XXX” couldn’t be opened because you don’t have permission to view it.

请问你有遇到过吗？或者是我的执行步骤有问题？ 谢谢

**Comment by jessecoding** [comment]
错误码如下:

Error Domain=IDEDistributionStripXattrsStepDomain Code=1 "Stripping extended attributes failed." UserInfo={NSLocalizedDescription=Stripping extended attributes failed., NSLocalizedRecoverySuggestion="/usr/bin/xattr -crs /var/folders/4x/clx2dg_d2k9bmywrjmksdw9c0000gn/T/XcodeDistPipeline.xBT/Root/Payload/DesignManager.app" exited with a non-zero status. The /usr/bin/xattr tool may be damaged.}

**Comment by crespoxiao** [comment]
我也遇到这个问题了

**Comment by jessecoding** [comment]
@crespoxiao 你的命令怎么写的？你的电脑环境是？

**Comment by crespoxiao** [comment]
@jessecoding    我解决了

fir build_ipa "$projectDir" -o "$outputDir" -w true -S Canyin -E enterprise -O build/In-house/exportOptions.plist -p -V -T 5a52f03b98c22a916e08c451xxxxxx;

参考楼上 @iStig  的方法 ，exportOptions.plist 加了个字段 provisioningProfiles 

        <key>provisioningProfiles</key>
    	<dict>
        <key>com.xxx.canyinhdvip</key>
        <string>CanyinHDVip Dis</string>
    	</dict>
