### ISSUE TITLE
mac上搭建Jenkins执行fir publish提示fir：command not found

### ISSUE THREAD

**Issue by Shane022** [FIRHQ/fir-cli#162]
已经安装fir-cli，并且在终端执行fir publish也可以正常执行。Jenkins在系统管理-Environment variables中也设置了PATH，但是构建时执行fir publish提示fir: command not found。现在不太明白问题出在哪里，请帮忙解决一下，谢谢！！！

**Comment by NaixSpirit** [comment]
fir-cli 是 ruby 写的, 说的简单点就是一堆 ruby 脚本
终端能执行是因为终端加载了 .bashrc 或者 .zshrc 里面的 ruby 相关 PATH
所以 Jenkins 运行的时候需要加载 ruby 环境

**Comment by wotoutengleha** [comment]
> 已经安装fir-cli，并且在终端执行fir publish也可以正常执行。Jenkins在系统管理-Environment variables中也设置了PATH，但是构建时执行fir publish提示fir: command not found。现在不太明白问题出在哪里，请帮忙解决一下，谢谢！！！

这个问题我解决了 同学 你解决了吗

**Comment by zhouyu0616** [comment]
@Shane022 命令行执行echo $PATH，将打印出的值，设置到jenkins中的Environment variables。然后一定要重启jenkins。一定要重启jenkins。一定要重启jenkins。（重要步骤说三遍）

**Comment by rockingwp** [comment]
一定要重启jenkins
