### ISSUE TITLE
Check dependencies xcode9 + swift4

### ISSUE THREAD

**Issue by RtzX** [FIRHQ/fir-cli#163]
=== BUILD TARGET Alamofire OF PROJECT Pods WITH CONFIGURATION Debug ===

Check dependencies
Code Signing Error: Alamofire does not support provisioning profiles. Alamofire does not support provisioning profiles, but provisioning profile NO_SIGNING/ has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

**Comment by AndyXTCao** [comment]
You can add the following to the end of the Podfile:
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
end

**Comment by AndyXTCao** [comment]
I solved the issue by adding the following to the end of Podfile:
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
    end
end
![2017-11-13 3 40 25](https://user-images.githubusercontent.com/8197190/32714491-bfd68484-c813-11e7-8745-c7e0a48e32b2.png)

**Comment by RtzX** [comment]
2017.10.11---2019.2.20
