### ISSUE TITLE
请问这个怎么办

### ISSUE THREAD

**Issue by liuyongqing1** [FIRHQ/fir-cli#165]
no implicit conversion of nil into String
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/util/parser/ipa.rb:92:in `join'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/util/parser/ipa.rb:92:in `info'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/util/parser/ipa.rb:100:in `identifier'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/util/parser/ipa.rb:79:in `basic_info'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/util/parser/ipa.rb:70:in `full_info'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/util/info.rb:27:in `ipa_info'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/util/publish.rb:12:in `publish'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/cli.rb:116:in `publish'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/lib/fir/cli.rb:181:in `invoke_command'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.3/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/yiweinie/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jicheng1014** [comment]
请更新 fir-cli 版本到最新

**Comment by dadahua** [comment]
> 请更新 fir-cli 版本到最新

fir-cli 2.0.14  的fir还是有这个问题呢！！

no implicit conversion of nil into String
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/parser/ipa.rb:92:in `join'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/parser/ipa.rb:92:in `info'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/parser/ipa.rb:100:in `identifier'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/parser/ipa.rb:79:in `basic_info'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/parser/ipa.rb:70:in `full_info'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/info.rb:27:in `ipa_info'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/publish.rb:215:in `initialize_publish_options'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/util/publish.rb:15:in `publish'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/cli.rb:147:in `publish'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/lib/fir/cli.rb:194:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.14/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'
