### ISSUE TITLE
安装报xcodeproj's executable "xcodeproj" conflicts with /usr/local/bin/xcodeproj

### ISSUE THREAD

**Issue by JulianSong** [FIRHQ/fir-cli#166]
Fetching: thor-0.20.0.gem (100%)
Successfully installed thor-0.20.0
Fetching: CFPropertyList-2.3.5.gem (100%)
Successfully installed CFPropertyList-2.3.5
Fetching: unf_ext-0.0.7.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.7.4
Fetching: unf-0.1.4.gem (100%)
Successfully installed unf-0.1.4
Fetching: domain_name-0.5.20170404.gem (100%)
Successfully installed domain_name-0.5.20170404
Fetching: http-cookie-1.0.3.gem (100%)
Successfully installed http-cookie-1.0.3
Fetching: mime-types-data-3.2016.0521.gem (100%)
Successfully installed mime-types-data-3.2016.0521
Fetching: mime-types-3.1.gem (100%)
Successfully installed mime-types-3.1
Fetching: netrc-0.11.0.gem (100%)
Successfully installed netrc-0.11.0
Fetching: rest-client-2.0.2.gem (100%)
Successfully installed rest-client-2.0.2
Fetching: rubyzip-1.2.1.gem (100%)
Successfully installed rubyzip-1.2.1
Fetching: ruby_android-0.7.7.gem (100%)
Successfully installed ruby_android-0.7.7
Fetching: chunky_png-1.3.8.gem (100%)
Successfully installed chunky_png-1.3.8
Fetching: rqrcode-0.10.1.gem (100%)
Successfully installed rqrcode-0.10.1
Fetching: claide-1.0.2.gem (100%)
Successfully installed claide-1.0.2
Fetching: colored2-3.1.2.gem (100%)
Successfully installed colored2-3.1.2
Fetching: nanaimo-0.2.3.gem (100%)
Successfully installed nanaimo-0.2.3
Fetching: xcodeproj-1.5.2.gem (100%)
xcodeproj's executable "xcodeproj" conflicts with /usr/local/bin/xcodeproj
Overwrite the executable? [yN]  N
ERROR:  Error installing fir-cli:
	"xcodeproj" from xcodeproj conflicts with /usr/local/bin/xcodeproj

**Comment by jicheng1014** [comment]
可以试试docker fir-cli 解决依赖问题

ps   fir-cli 已经不再限制 xcodeproj 的版本了
