### ISSUE TITLE
fir publish 能不能新增Show on download page配置啊

### ISSUE THREAD

**Issue by itlijunjie** [FIRHQ/fir-cli#169]
这样就不用每次都去后台点击打开按钮下载之前的版本了。
![615fd30f-9139-4052-bb35-d65cca432140](https://user-images.githubusercontent.com/3367048/32540618-3592b4a0-c4a8-11e7-851c-9b5e178ee0a4.png)

**Comment by Rosepotato** [comment]
顶！！我们公司也需要每个版本默认都打开。强烈要求fir publish 加上 Show on download page 的参数，如果这个参数设置为true,这个版本就始终能在download page看到，不设置或者设置为false，老版本就必须手动点开 Show on download page。

**Comment by linesh-simplicity** [comment]
同样遇到这个问题，也需要这个 feature。可以默认关闭，但给开发者打开的权利。

测试了一下，只是更新 build number 的话依然会默认被隐藏，可能需要升小版本或 patch 版本才可以，这样的话可能就难以做到开发/测试环境的持续集成啦。建议考虑新增下这个 feature

**Comment by jicheng1014** [comment]
这个玩意的问题在于 在download 页面太多release的话非常影响载入速度问题   如果你需要确定版本   可以使用 -r  拿到 release_id

**Comment by Rosepotato** [comment]
@jicheng1014 您提到 “如果你需要确定版本 可以使用 -r 拿到 release_id”。可以说具体点吗？这个怎么用。fir 命令行里面没有-r 这个参数啊。

**Comment by jicheng1014** [comment]
@Rosepotato   在publish 的时候

**Comment by linesh-simplicity** [comment]
在 download 页面太多 release _的话非常影响载入速度，这个问题是可以解决的吗？因为我们发现了另一个场景，是用 release_id 不足以解决问题的（当然 release_id 解决了很大一个问题）。

场景是，我们的 QA 需要在多部手机上从 fir 上下载最新应用进行测试，这需要连外网；但打包上传应用到 fir 并拿到 release_id 时必须是在内网的 CI 机器上。所以由于网络限制，QA 同学没有办法直接在 CI 机器上给出的 release_id 上直接跳转到下载页面，而还是只能在每部手机上访问 fir.im，并从列表中选择要下载的应用，这样就会遇到这个「 show on download page」被默认关闭的问题。

可以想到的解决方案有：

1. 让这个 show on download page 不默认关闭（这个 issue 所讨论）
2. 每次打包的时候自动增加一下 build number 
3. 让 QA 同学的每部手机都可以访问内外网

最后者成本最高，1、2种感觉都可以。

**Comment by jicheng1014** [comment]
## "让这个 show on download page 不默认关闭"   

这个东西  如果我这边设置 , 如果最多设置10 个或者确定个数个,  这种应该可以满足需求吧? 

回头我跟产品聊聊, 我也挺想增加这种设置的 

## "每次打包的时候自动增加一下 build number"

这个如果你用fastlane 打包的话  这有一个参考  https://docs.fastlane.tools/actions/increment_version_number/

**Comment by Rosepotato** [comment]
@jicheng1014 @linesh-simplicity 
1.我觉得 增加一个参数让用户能自动选择在fir upload的时候是否一直保持当前版本在download page 能看到， 这个是很重要的。尤其是对于QA来说，经常要取老的版本看 新的功能加上以后 老版本的应用有没有什么问题。
2. 你们说“在 download 页面太多 release 的话非常影响载入速度”， 这个可以分批载入啊（比如说一次载入10个，点击fetch  more, 载入另外10个......）我觉得这个问题在技术上来说应该不是大问题。

**Comment by jerryzhoujw** [comment]
最好是当天出的 build 默认都能看到即便 没有设置 Show on download page。build出来需要再去点下，或者新的build 把之前的覆盖掉了看不到了 在一天中发生多次的话，实在占用时间。

**Comment by itlijunjie** [comment]
真费劲

**Comment by winterwd** [comment]
是啊，这个功能尽早放出来，不然，现在每打一个，都要给测试放开历史记录
