### ISSUE TITLE
fir publish 希望增加 返回 realease_id

### ISSUE THREAD

**Issue by undefined-zola** [FIRHQ/fir-cli#170]
fir publish 希望增加 返回 realease_id

或者 -Q 二维码生成配置，能动态配置 生成带release_id链接的 二维码

**Comment by linesh-simplicity** [comment]
+1。做 CI 持续集成的时候，也希望能返回一个 release_id，这样测试人员可以在众多 build 中简单找到每个 build 所对应的打包文件。

**Comment by jicheng1014** [comment]
目前这个不是很好解决   主要是因为系统的release_id 是在cdn 结束上传后回调产生的,没办法直接拿到

临时解决方案是
分两步:
1. publish 后  wait 一段时间,等待cdn callback(通常在 5s)
2.之后去通过api 读到 master_release_id   , 这个id 默认情况下 就是新上传的 release_id

下个版本会取消掉cdn 的callback  转而手动实现callback 给系统

**Comment by jicheng1014** [comment]
已经实现

gem install fir-cli --pre      之后 publish -r 就有release_id 了

**Comment by xwartz** [comment]
@jicheng1014   上传的接口上有返回 release_id 吗？ 文档上没有看到 https://fir.im/docs/publish

**Comment by karosLi** [comment]
问题提了一年了，貌似也没有答复吧
