### ISSUE TITLE
fir publish HTTP status code 579

### ISSUE THREAD

**Issue by Hellengo** [FIRHQ/fir-cli#171]
log:
fir publish //app-debug.apk -T ******
I, [2017-11-23T12:06:55.938774 #25095]  INFO -- : Publishing app via 
I, [2017-11-23T12:06:55.938843 #25095]  INFO -- : ✈ -------------------------------------------- ✈
I, [2017-11-23T12:06:59.326056 #25095]  INFO -- : Fetching *** uploading info......
I, [2017-11-23T12:06:59.326127 #25095]  INFO -- : Uploading app: ***
warning: Overriding "Content-Type" header "application/json" with "application/x-www-form-urlencoded" due to payload
I, [2017-11-23T12:06:59.422934 #25095]  INFO -- : Uploading app icon......
I, [2017-11-23T12:06:59.423018 #25095]  INFO -- : Converting app's icon......
warning: Overriding "Content-Type" header "application/json" with "multipart/form-data; boundary=----RubyFormBoundarycCEdxYljndxbVGlt" due to payload
E, [2017-11-23T12:06:59.566223 #25095] ERROR -- : HTTP status code 579
I, [2017-11-23T12:06:59.566291 #25095]  INFO -- : Retry 1 times......
E, [2017-11-23T12:07:01.566926 #25095] ERROR -- : closed stream
I, [2017-11-23T12:07:01.566985 #25095]  INFO -- : Retry 2 times......
E, [2017-11-23T12:07:03.567751 #25095] ERROR -- : closed stream
I, [2017-11-23T12:07:03.567801 #25095]  INFO -- : Retry 3 times......
E, [2017-11-23T12:07:05.568341 #25095] ERROR -- : closed stream
I, [2017-11-23T12:07:05.568391 #25095]  INFO -- : Retry 4 times......
E, [2017-11-23T12:07:07.568954 #25095] ERROR -- : closed stream
I, [2017-11-23T12:07:07.568999 #25095]  INFO -- : Retry 5 times......
E, [2017-11-23T12:07:09.569551 #25095] ERROR -- : closed stream

环境：
fir -v
✈ fir-cli 1.6.3

OS:
 cat /etc/issue
Ubuntu 16.04.1 LTS \n \l

gem -v
2.5.1

ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by jicheng1014** [comment]
已经修复了
