### ISSUE TITLE
Hudson 远程ssh执行脚本报错

### ISSUE THREAD

**Issue by QFangMobile** [FIRHQ/fir-cli#173]
/Library/Ruby/Site/2.0.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem fir-cli (>= 0.a) (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.0.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/yanghy/.rvm/rubies/ruby-2.4.0/bin/fir:23:in `<main>'
	from /Users/yanghy/.rvm/rubies/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/yanghy/.rvm/rubies/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
/Library/Ruby/Site/2.0.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem fir-cli (>= 0.a) (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.0.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/yanghy/.rvm/rubies/ruby-2.4.0/bin/fir:23:in `<main>'
	from /Users/yanghy/.rvm/rubies/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/yanghy/.rvm/rubies/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

报这个错如何解决？
命令行手动执行没问题

**Comment by jicheng1014** [comment]
哥们用了rvm 安装了吧

https://42ways.de/blog/tags/jenkins/

**Comment by louis2610** [comment]
> 哥们用了rvm 安装了吧
> 
> https://42ways.de/blog/tags/jenkins/

我也报了这个错，具体怎么操作呢?
