### ISSUE TITLE
Gem依赖冲突

### ISSUE THREAD

**Issue by thierryxing** [FIRHQ/fir-cli#177]
fir-cli中对xcodeproj的依赖和cocoapods 1.4版本冲突：

`s.add_runtime_dependency 'xcodeproj',             '>= 1.5.6', '< 2.0'`
[https://github.com/CocoaPods/CocoaPods/blob/master/cocoapods.gemspec](https://github.com/CocoaPods/CocoaPods/blob/master/cocoapods.gemspec)

**Comment by jicheng1014** [comment]
下个版本将去除 xcodeproj    转而让用户去使用 fastlane gym 进行打包

**Comment by thierryxing** [comment]
👍

**Comment by jicheng1014** [comment]
ps  不知道您这边是直接生成好ipa  还是使用 fir cli  生成 ipa 直接上传呢

**Comment by thierryxing** [comment]
通过fastlane gym生成的，然后通过fir -p上传

**Comment by jicheng1014** [comment]
👍    你可以clone这个项目  
之后把 fir-cli.gemspec 的   
spec.add_dependency 'xcodeproj',      '~> 1.5' 
 的 版本指定依赖干掉,    之后 bundle && rake install

**Comment by thierryxing** [comment]
OK
