### ISSUE TITLE
HTTP status code 579,昨晚一直报这个错误，麻烦处理下

### ISSUE THREAD

**Issue by gaoneng102** [FIRHQ/fir-cli#181]
I, [2018-03-27T07:44:24.224387 #13937]  INFO -- : Publishing app via qileyou1819<qileyou1819@gmail.com>.......
I, [2018-03-27T07:44:24.224468 #13937]  INFO -- : ✈ -------------------------------------------- ✈
I, [2018-03-27T07:44:26.590391 #13937]  INFO -- : Fetching com.qly.hapi@fir.im uploading info......
I, [2018-03-27T07:44:26.590427 #13937]  INFO -- : Uploading app: 哈皮-1.0.0(Build 3)
warning: Overriding "Content-Type" header "application/json" with "application/x-www-form-urlencoded" due to payload
I, [2018-03-27T07:44:26.781043 #13937]  INFO -- : Uploading app icon......
I, [2018-03-27T07:44:26.781163 #13937]  INFO -- : Converting app's icon......
warning: Overriding "Content-Type" header "application/json" with "multipart/form-data; boundary=----RubyFormBoundaryIUrACnRYIahRqVJK" due to payload
I, [2018-03-27T07:44:27.264281 #13937]  INFO -- : Uploading app binary......
warning: Overriding "Content-Type" header "application/json" with "multipart/form-data; boundary=----RubyFormBoundaryFbjlBGP32STqCHj2" due to payload
E, [2018-03-27T07:44:53.762472 #13937] ERROR -- : HTTP status code 579
I, [2018-03-27T07:44:53.762532 #13937]  INFO -- : Retry 1 times......
E, [2018-03-27T07:44:55.767995 #13937] ERROR -- : closed stream
I, [2018-03-27T07:44:55.768028 #13937]  INFO -- : Retry 2 times......
E, [2018-03-27T07:44:57.768959 #13937] ERROR -- : closed stream
I, [2018-03-27T07:44:57.768993 #13937]  INFO -- : Retry 3 times......
E, [2018-03-27T07:44:59.774010 #13937] ERROR -- : closed stream
I, [2018-03-27T07:44:59.774057 #13937]  INFO -- : Retry 4 times......
E, [2018-03-27T07:45:01.779708 #13937] ERROR -- : closed stream
I, [2018-03-27T07:45:01.779746 #13937]  INFO -- : Retry 5 times......
E, [2018-03-27T07:45:03.782804 #13937] ERROR -- : closed stream

**Comment by jicheng1014** [comment]
gem install fir-cli --pre

**Comment by jicheng1014** [comment]
hello 更新后 现在还有这个问题么?

**Comment by gaoneng102** [comment]
@jicheng1014 现在没这个问题了，不过貌似我也没有执行上面那个命令，放了半天自己好了  :)

**Comment by jicheng1014** [comment]
好的 谢谢
