### ISSUE TITLE
上传iOS测试包失败

### ISSUE THREAD

**Issue by siperman** [FIRHQ/fir-cli#182]
1. Travis CI 上自动部署，今天一直卡在上传测试包步骤
安装成功日志：
=========安装 fir-cli 
Fetching: rest-client-2.0.2.gem (100%)
Successfully installed rest-client-2.0.2
Fetching: ruby_android-0.7.7.gem (100%)
Successfully installed ruby_android-0.7.7
Fetching: chunky_png-1.3.10.gem (100%)
Successfully installed chunky_png-1.3.10
Fetching: rqrcode-0.10.1.gem (100%)
Successfully installed rqrcode-0.10.1
Fetching: oj-3.5.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed oj-3.5.0
Fetching: api_tools-0.0.6.gem (100%)
Successfully installed api_tools-0.0.6
Fetching: fir-cli-1.6.4.gem (100%)

上传报错日志
I, [2018-03-27T06:01:12.615088 #8250]  INFO -- : Publishing app via xxx.......
I, [2018-03-27T06:01:12.615455 #8250]  INFO -- : ✈ -------------------------------------------- ✈
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
I, [2018-03-27T06:01:13.540632 #8250]  INFO -- : Fetching xxx uploading info......
I, [2018-03-27T06:01:13.540705 #8250]  INFO -- : Uploading app: xxxx
I, [2018-03-27T06:01:14.287249 #8250]  INFO -- : Uploading app icon......
I, [2018-03-27T06:01:14.287442 #8250]  INFO -- : Converting app's icon......
I, [2018-03-27T06:01:15.471063 #8250]  INFO -- : Uploading app binary......
closed stream
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `read'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `create_file_field'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:137:in `block in build_stream'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each_with_index'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `build_stream'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:47:in `initialize'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `new'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `generate'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/request.rb:77:in `initialize'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:63:in `block in basic_request'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `times'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `basic_request'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:17:in `block (2 levels) in <module:DefaultRestModule>'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:57:in `upload_file'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:48:in `block (2 levels) in <module:Publish>'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:40:in `upload_app'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:16:in `publish'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/fir-cli-1.6.4/lib/fir/cli.rb:116:in `publish'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/fir-cli-1.6.4/lib/fir/cli.rb:181:in `invoke_command'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/fir-cli-1.6.4/bin/fir:8:in `<top (required)>'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/fir:23:in `load'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/fir:23:in `<main>'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by siperman** [comment]
应该是因为 fir-cli 依赖的 rest-client 是2.0.0版本，但是安装时未指定版本号，导致更新到最新版本2.0.2。

**Comment by jicheng1014** [comment]
不是吧....  这个应该是  国内网络与国外信号不好

**Comment by chenfengfeng** [comment]
我跟你一样的问题,也是上传失败
```
I, [2018-03-29T15:13:41.103020 #63881]  INFO -- : Publishing app via CZF-峰峰<315871438@qq.com>.......
I, [2018-03-29T15:13:41.103120 #63881]  INFO -- : ✈ -------------------------------------------- ✈
I, [2018-03-29T15:13:42.065442 #63881]  INFO -- : Fetching com.gmdoc.xi@fir.im uploading info......
I, [2018-03-29T15:13:42.065494 #63881]  INFO -- : Uploading app: xi-1.0(Build 1)
I, [2018-03-29T15:13:42.301131 #63881]  INFO -- : Uploading app icon......
I, [2018-03-29T15:13:42.301326 #63881]  INFO -- : Converting app's icon......
I, [2018-03-29T15:13:43.145520 #63881]  INFO -- : Uploading app binary......
closed stream
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `read'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `create_file_field'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:137:in `block in build_stream'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each_with_index'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `build_stream'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:47:in `initialize'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `new'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `generate'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:77:in `initialize'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:63:in `block in basic_request'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `times'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `basic_request'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:17:in `block (2 levels) in <module:DefaultRestModule>'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:57:in `upload_file'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:48:in `block (2 levels) in <module:Publish>'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:40:in `upload_app'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:16:in `publish'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.4/lib/fir/cli.rb:116:in `publish'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.4/lib/fir/cli.rb:181:in `invoke_command'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Users/fengfeng/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.4/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'
/Users/fengfeng/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `eval'
/Users/fengfeng/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jicheng1014** [comment]
1.6.6 版本已经将默认超时由5秒改成了 300秒, 也可以通过环境变量 FIR_TIMEOUT 进行自定义  单位为秒

**Comment by BianXiaoYan** [comment]
我也出现了这个问题！！


`closed stream
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `read'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `create_file_field'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:137:in `block in build_stream'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each_with_index'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `build_stream'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:47:in `initialize'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `new'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `generate'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:77:in `initialize'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/var/lib/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/var/lib/gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:63:in `block in basic_request'
/var/lib/gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `times'
/var/lib/gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `basic_request'
/var/lib/gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:17:in `block (2 levels) in <module:DefaultRestModule>'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:65:in `upload_file'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:56:in `block (2 levels) in <module:Publish>'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:45:in `upload_app'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:16:in `publish'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/cli.rb:119:in `publish'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/cli.rb:184:in `invoke_command'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/bin/fir:8:in `<top (required)>'`

我的版本是1.6.6，按道理300秒是够了的哦！

**Comment by siperman** [comment]
这个当时是因为网络原因，国外服务访问国内延迟丢包严重，过了两天后恢复了。

**Comment by jicheng1014** [comment]
@siperman    好的谢谢

**Comment by lmmsoft** [comment]
我也遇到同样的问题，前几天挂了，今天就好了~
