### ISSUE TITLE
fir publish  -c 上传的changlog, 在app下载页面无法显示中文字符

### ISSUE THREAD

**Issue by JesseWo** [FIRHQ/fir-cli#184]
通过 fir publish  -c ${changelog_path}上传的changlog, 在app下载页面不显示中文字符, 只显示英文和数字
![image](https://user-images.githubusercontent.com/19713560/39187163-1bd18ca0-47ff-11e8-90c2-1e673477185f.png)

**Comment by jicheng1014** [comment]
能打出来你的环境变量看看么

**Comment by JesseWo** [comment]
Mac OS 
![image](https://user-images.githubusercontent.com/19713560/40109940-45d37872-5931-11e8-9fd2-adcaf34817ab.png)

**Comment by jicheng1014** [comment]
changelog_path   这个

**Comment by JesseWo** [comment]
就是当前目录下的CHANGE_LOG.txt文件
`/usr/local/bin/fir publish ./app/build/outputs/apk/staging/release/app-staging-release.apk -c ./CHANGE_LOG.txt -T ${mytoken} -Q`

**Comment by JesseWo** [comment]
补充一下, CHANGE_LOG.txt 是UTF-8 编码, 文档内的内容没有问题.

**Comment by LiWeiQiangAndroid** [comment]
--changelog='文本' 这个中文或者空格没法识别上传
