### ISSUE TITLE
执行fir就报错

### ISSUE THREAD

**Issue by OctMon** [FIRHQ/fir-cli#187]
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate fir-cli-1.6.6, because CFPropertyList-3.0.0 conflicts with CFPropertyList (~> 2.3) (Gem::ConflictError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/lib/fir.rb:22:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/bin/fir:4:in `require_relative'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/bin/fir:4:in `<top (required)>'
	from /usr/local/bin/fir:22:in `load'
	from /usr/local/bin/fir:22:in `<main>'

**Comment by jicheng1014** [comment]
gem update

**Comment by OctMon** [comment]
gem list
CFPropertyList (3.0.0, 2.3.6, 2.2.8)

**Comment by OctMon** [comment]
删除3.0.0就好了

**Comment by iusn** [comment]
如果cocoapods 和 fastlane 都依赖CFPropertyList 3.0.0 怎么办？
