### ISSUE TITLE
Mac上面在shell脚本中使用有问题

### ISSUE THREAD

**Issue by xinxu** [FIRHQ/fir-cli#19]
I, [2015-09-17T00:41:30.250316 #22022]  INFO -- : Publishing app.......
I, [2015-09-17T00:41:30.250415 #22022]  INFO -- : ✈ -------------------------------------------- ✈
I, [2015-09-17T00:41:31.958848 #22022]  INFO -- : Fetching com.ohsame.same2.0@FIR.im uploading info......
I, [2015-09-17T00:41:32.159018 #22022]  INFO -- : Uploading app's icon......
I, [2015-09-17T00:41:32.751708 #22022]  INFO -- : Uploading app......
undefined method `response' for #<Errno::EPIPE: Broken pipe>
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.2/lib/fir/util/http.rb:35:in `rescue in block (2 levels) in <module:Http>'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.2/lib/fir/util/http.rb:26:in `block (2 levels) in <module:Http>'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.2/lib/fir/util/publish.rb:86:in `upload_app_binary'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.2/lib/fir/util/publish.rb:45:in `upload_app'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.2/lib/fir/util/publish.rb:23:in `publish'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.2/lib/fir/cli.rb:91:in `publish'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.2/lib/fir/cli.rb:156:in `invoke_command'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/tassar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.2/bin/fir:8:in `<top (required)>'
/Users/tassar/.rbenv/versions/2.2.2/bin/fir:23:in `load'
/Users/tassar/.rbenv/versions/2.2.2/bin/fir:23:in `<main>'

**Comment by NaixSpirit** [comment]
网络延时导致发出去的请求没有响应了, 可以再试试

**Comment by hujian** [comment]
一模一样的问题，应该不是网络造成的。

ruby 2.1.3p242

**Comment by NaixSpirit** [comment]
@xinxu @hujian 每一次上传都会报错?

**Comment by hujian** [comment]
map每次都报错，从来没上传成功过。
publish则没有问题。难道和文件大小有关系？

**Comment by NaixSpirit** [comment]
@hujian 目前对 mapping 文件的大小限制是 50MB, 而且在 fir-cli 中内置了对 mapping 的压缩功能, 应该不是文件大小的原因.

map 的报错信息能发下吗?

**Comment by hujian** [comment]
和@xinxu问题，一样的，就是 undefined method response' for #<Errno::EPIPE: Broken pipe>

**Comment by NaixSpirit** [comment]
一直没有复现

**Comment by hahaGitHub** [comment]
@xinxu  我也出现类似的问题了  请问你那修好了吗 怎么修的
