### ISSUE TITLE
fir publish 一直提示 http 579

### ISSUE THREAD

**Issue by 888niannianwang** [FIRHQ/fir-cli#190]
![image](https://user-images.githubusercontent.com/18587194/40214763-3170d03c-5a8f-11e8-8875-587faed48c0a.png)

**Comment by jicheng1014** [comment]
朋友用的是  travis-ci 么 ?   如果是境外的话  可能有时会超时

**Comment by linesh-simplicity** [comment]
我们团队今天也一直遇到相同的情况，错误是相同的，CI 已经挂了一天了 😂

**Comment by jicheng1014** [comment]
@linesh-simplicity    travisci 跑的?

**Comment by jicheng1014** [comment]
稍等我们在联系cdn 厂商

**Comment by linesh-simplicity** [comment]
是用 Jenkins + fastlane 跑的。在命令行手动调用命令也会出现同样的错误：

```bash
fir publish <package> -c <log> -T <token>
```

命令是 ok 的，平时都是用这个命令上传成功的哈。

**Comment by jicheng1014** [comment]
目前是江苏地区因为 不解析我们dns 导致了错误   您试一下将dns 换成 114.114.114.114 或1.1.1.1 试试

**Comment by 888niannianwang** [comment]
我是用的Jenkins，这个截图是本地跑的错误，Jenkins也是一样的错误
地区是在上海

**Comment by 888niannianwang** [comment]
@jicheng1014 本地试了OK了

**Comment by jicheng1014** [comment]
ok    @888niannianwang    你们是七牛么

**Comment by 888niannianwang** [comment]
@jicheng1014 是的，怎么了

**Comment by jicheng1014** [comment]
@888niannianwang   因为刚还在跟你们同事一起调这个bug  :D   这几天不知道为啥  qiniu 的 callback 到不了我们服务器,  之后我们让七牛这写死了个hosts

**Comment by linesh-simplicity** [comment]
同行相见啊 😂 我们用 fir 上传的今天好啦
