### ISSUE TITLE
上传apk报一大段红色的closed stream，用$? != 0判断是上传失败的，其实是上传成功了

### ISSUE THREAD

**Issue by divinghero** [FIRHQ/fir-cli#191]
closed stream
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `read'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `create_file_field'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:137:in `block in build_stream'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each_with_index'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `build_stream'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:47:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `new'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `generate'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:77:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/Library/Ruby/Gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:63:in `block in basic_request'
/Library/Ruby/Gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `times'
/Library/Ruby/Gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `basic_request'
/Library/Ruby/Gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:17:in `block (2 levels) in <module:DefaultRestModule>'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:65:in `upload_file'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:56:in `block (2 levels) in <module:Publish>'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:45:in `upload_app'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:16:in `publish'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/cli.rb:119:in `publish'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/cli.rb:184:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'

**Comment by jicheng1014** [comment]
请更新到最新版
