### ISSUE TITLE
fir jenkins插件问题

### ISSUE THREAD

**Issue by lihaodong** [FIRHQ/fir-cli#192]
jenkins的fir插件是不是出问题了，android安装包实际上传成功，jenkins返回失败。iOS没问题

**Comment by wlrnet** [comment]
确实有这个问题，和官方留言，官方什么都不管，什么破玩意

**Comment by Sinexs** [comment]
有同样的问题，希望能尽快修复

**Comment by jicheng1014** [comment]
jenkins 的插件目前暂时停止维护了    请在 jenkins 的机器里安装 fir-cli  之后用 fir-cli  发布应用

**Comment by Sinexs** [comment]
@jicheng1014 cli 也会报错，android上传成功但返回失败，iOS成功 ，类似issue #93

**Comment by jicheng1014** [comment]
@Sinexs   是最新版 fir-cli 么?   1.6.8

**Comment by Sinexs** [comment]
@jicheng1014 不是最新版，现在用的是1.5.0，因为要支持iOS swift2.2
