### ISSUE TITLE
cocoapods 和 fastlane 依赖CFPropertyList 3.0.0  但是 fir-cli 依赖CFPropertyList 2.3 请问怎么处理？

### ISSUE THREAD

**Issue by iusn** [FIRHQ/fir-cli#193]
Error loading plugin 'fastlane-plugin-fir': Unable to activate fir-cli-1.6.8, because CFPropertyList-3.0.0 conflicts with CFPropertyList (~> 2.3)
[11:47:17]: It seems like you wanted to load some plugins, however they couldn't be loaded
[11:47:17]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/

**Comment by iusn** [comment]
ruby 2.5.1
fir-cli 1.6.8
gem 2.7.7

**Comment by jicheng1014** [comment]
fastlane-plugin-fir   依赖   联系 fastlane-plugin-fir 的作者   或者fork 出来   去修改 它的  gemspec 文件

**Comment by jicheng1014** [comment]
fork 我这个项目   去修改  fir-cli.gemspec      之后  运行  rake install 

我会在下一个版本修改 CFPropertyList的版本信息

**Comment by iusn** [comment]
感谢

**Comment by itlijunjie** [comment]
加急啊
