### ISSUE TITLE
1.6.8 undefined local variable or method `answer' for FIR:Module

### ISSUE THREAD

**Issue by foobra** [FIRHQ/fir-cli#194]
undefined local variable or method `answer' for FIR:Module
/usr/local/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.8/lib/fir/util/publish.rb:23:in `publish'
/usr/local/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.8/lib/fir/cli.rb:119:in `publish'
/usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.8/lib/fir/cli.rb:184:in `invoke_command'
/usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.8/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'

使用-r参数 publish

**Comment by jicheng1014** [comment]
这是个bug,  1.6.10 已经默认输出release_id 了
