### ISSUE TITLE
怎么获取二维码地址，需要在 jenkins 中配置

### ISSUE THREAD

**Issue by devtofu** [FIRHQ/fir-cli#195]
jenkins 用本地图片有问题，fir publish 命令有获取二维码 url 的参数吗

**Comment by jicheng1014** [comment]
不是很理解呢    二维码实际上是个url的地址    短地址其实在上传完毕之后是给出来了的

**Comment by Mabeple** [comment]
应该是获取二维码地址显示在jenkins上....

**Comment by devtofu** [comment]
@Mabeple hhh,描述没写清楚，确实是二维码 url 地址， description setter 插件上用，最后在本地搭了个静态文件服务做 url 了。

**Comment by jicheng1014** [comment]
网站的二维码是用js 算出来的   cli 生成的js 是拿地址算的js

**Comment by Chenkun1989** [comment]
Jenkins打包后显示二维码，我是这么做的
1，fir p的时候指定-Q，会在ipa的那个目录下生成一张对应的二维码图片
2，执行ptyhon脚本，把上面的图片拷贝到jenkins的userContent目录下面
3，在post action里添加 set build description
      <img src="${JENKINS_URL}userContent/fir-xxxx.png" width="200" height="200"/>
