### ISSUE TITLE
Gem::FilePermissionError

### ISSUE THREAD

**Issue by hebiao6446** [FIRHQ/fir-cli#199]
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.

按照步骤说明 ，  出错 
macOS High Sierra   10.13.4 (17E199)  
xcode  Version 9.4 (9F1027a)

**Comment by jicheng1014** [comment]
试试用  rvm 安装ruby 版本
