### ISSUE TITLE
如何指定上传后下载时显示的文件名.

### ISSUE THREAD

**Issue by qwwuyu** [FIRHQ/fir-cli#200]
之前在Jenkins用的插件,下载显示时名字 和 打包时文件名一致.
现在使用fir命令,大概这样用的.
fir p 文件 -T token -c 日志
下载时候显示的文件名2de1956e3e3e35f714832d7416d2cf06a303f5f2.apk

**Comment by jicheng1014** [comment]
目前对于下载次数多的应用  似乎没有很好的方式     或者可以具体情况咨询我们
