### ISSUE TITLE
jenkins fir publish 时...本地为测试包....你们后台变为企业版...

### ISSUE THREAD

**Issue by Mabeple** [FIRHQ/fir-cli#201]
I, [2018-06-19T14:48:23.810733 #44736]  INFO -- : Publishing app via XXXXX.......
I, [2018-06-19T14:48:23.810913 #44736]  INFO -- : ✈ -------------------------------------------- ✈
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: A default keychain could not be found.
security: problem decoding
I, [2018-06-19T14:48:25.110113 #44736]  INFO -- : Fetching ......
I, [2018-06-19T14:48:25.110200 #44736]  INFO -- : Uploading app: zz-zzz(Build 201806191443)
I, [2018-06-19T14:48:25.232118 #44736]  INFO -- : Uploading app icon......
I, [2018-06-19T14:48:25.232314 #44736]  INFO -- : Converting app's icon......
I, [2018-06-19T14:48:25.725746 #44736]  INFO -- : Uploading app binary......
I, [2018-06-19T14:48:48.527164 #44736]  INFO -- : App id is 5b23bd24ca87a839207e3831
I, [2018-06-19T14:48:48.527219 #44736]  INFO -- : Release id is 5b28a750548b7a42ac4c7283
I, [2018-06-19T14:48:48.527275 #44736]  INFO -- : Fetch app info from fir.im
I, [2018-06-19T14:48:48.630945 #44736]  INFO -- : ✈ -------------------------------------------- ✈
I, [2018-06-19T14:48:48.631011 #44736]  INFO -- : Published succeed: 
I, [2018-06-19T14:48:48.798349 #44736]  INFO -- : Local qrcode file: /Users/Shared/Jenkins/Home/workspace/XXXX.png
I, [2018-06-19T14:48:48.798414 #44736]  INFO -- :

**Comment by jicheng1014** [comment]
额?  你是不是用的  fir build ?    推荐你使用 fastlane 编译 成 ipa 文件, 再使用 fir publish 

 fir publish 只会 将你指定的 ipa 文件  上传到fir 
 理论上来说  fir 的显示只是解析了这个ipa 包里的plist 文件   
之后你下载的时候还是下的你传上的包, 我们不会,也不能修改对应的包体
