### ISSUE TITLE
打的是DEBUG包然后用fir info竟然是ad-hoc,

### ISSUE THREAD

**Issue by Mabeple** [FIRHQ/fir-cli#205]

**Comment by Mabeple** [comment]
![qq20180627-161252](https://user-images.githubusercontent.com/16207583/41961496-339228a6-7a25-11e8-885e-47617d5794b8.png)

**Comment by jicheng1014** [comment]
你在浏览器上传一个 debug 的包  之后把短地址给我  我从后台拿到你地址  我来分析下
