### ISSUE TITLE
显示默认图标

### ISSUE THREAD

**Issue by yjukh5** [FIRHQ/fir-cli#206]
用命令上传后显示默认图标

**Comment by jicheng1014** [comment]
应该是解析图标之后失败了   您可以进入web , 进入 app , 之后点击icon 更换icon图片

**Comment by twcx** [comment]
貌似这个图标上传还是有问题，用命令上传ipa，图标是默认的，上传apk正常。
`$ fir version
✈ fir-cli 1.7.0
$ rvm version
rvm 1.29.4 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ ruby -v
ruby 2.6.0preview2 (2018-05-31 trunk 63539) [x86_64-darwin17]`

**Comment by twcx** [comment]
貌似这个图标上传还是有问题，用命令上传ipa，图标是默认的，上传apk正常。
`$ fir version`
` ✈ fir-cli 1.7.0`
`$ rvm version `
`rvm 1.29.4 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`
`$ ruby -v `
`ruby 2.6.0preview2 (2018-05-31 trunk 63539) [x86_64-darwin17]`

**Comment by cheerszhou** [comment]
通过fir publish 命令上传ipa包后, 显示默认图标, 但是通过web 的手动上传ipa包正常:
![image](https://user-images.githubusercontent.com/13127171/56819979-69fe8780-687d-11e9-9258-f948ccdaba9e.png)
