### ISSUE TITLE
上传后下载时显示的文件名为随机字符串

### ISSUE THREAD

**Issue by Taki-Kun** [FIRHQ/fir-cli#207]
https://github.com/FIRHQ/fir-cli/issues/200#issue-331867397

fir p 文件 -T token -c 日志
下载时候显示的文件名2f96fb690f08b669f6693d9907a4f54c3affa8cc.apk
辨识度很低，看情况好像还是随机发生的，同时传的几个包，有的会保持文件名，有的会变，同一个flavor的包在不同时刻上传也有不同的结果，有没有解决方案？

**Comment by jicheng1014** [comment]
其实是因为有的cdn 不支持  有的cdn 支持   我们会跟cdn 厂商沟通
