### ISSUE TITLE
用 --output 参数时导出dSYM的命名不合理

### ISSUE THREAD

**Issue by hujian** [FIRHQ/fir-cli#21]
用 --output 参数时导出时，ipa文件会加版本号：
`app-0.0.2-Build-4.ipa`

dsym文件就不会：
`xxx.app.dSYM`

很不好管理，一不小心，就把以前的覆盖了，郁闷的很。
希望能统一命名。

**Comment by NaixSpirit** [comment]
version 1.2.8
