### ISSUE TITLE
fir安装成功后执行命令失败

### ISSUE THREAD

**Issue by Jack-wrs** [FIRHQ/fir-cli#210]
`wrsdeMacBook-Pro:~ wrs$ export PATH=/usr/local/bin:$PATH;gem install -n /usr/local/bin fir-cli

        ______________        ________    ____
       / ____/  _/ __ \      / ____/ /   /  _/
      / /_   / // /_/ /_____/ /   / /    / /
     / __/ _/ // _, _/_____/ /___/ /____/ /
    /_/   /___/_/ |_|      \____/_____/___/

  ## 更新记录 
  - (1.6.11) 变化了 ruby gem 仓库地址
  - (1.6.10) 增加显示release_id 以及 app_id
  - (1.6.9) 取消了依赖 cfpropertylist 的具体版本号
  - (1.6.8) 取消了远端回调, 改为本地callback
  - (1.6.8) fir-cli 也支持了私有部署模式
  - [fir-cli](https://github.com/firhq/fir-cli) 已经开源
  - 欢迎 fork, issue 和 pull request
  
Successfully installed fir-cli-1.6.11
Parsing documentation for fir-cli-1.6.11
Done installing documentation for fir-cli after 0 seconds
1 gem installed
wrsdeMacBook-Pro:~ wrs$ fir --version
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- byebug (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.11/lib/fir/util/publish.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.11/lib/fir/util.rb:14:in `require_relative'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.11/lib/fir/util.rb:14:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.11/lib/fir.rb:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.11/bin/fir:4:in `require_relative'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.11/bin/fir:4:in `<top (required)>'
	from /usr/local/bin/fir:23:in `load'
	from /usr/local/bin/fir:23:in `<main>'`

**Comment by DeqiuTseng** [comment]
同样遇到了这个问题太折腾了

**Comment by pzhangleo** [comment]
碰到一样的问题

/home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- byebug (LoadError)
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.11/lib/fir/util/publish.rb:3:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.11/lib/fir/util.rb:14:in `require_relative'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.11/lib/fir/util.rb:14:in `<top (required)>'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.11/lib/fir.rb:23:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.11/bin/fir:4:in `require_relative'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fir-cli-1.6.11/bin/fir:4:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/fir:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/fir:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jicheng1014** [comment]
实在抱歉  已经修复

**Comment by jicheng1014** [comment]
如有问题  还请联系微信  atpking

**Comment by zxdvd** [comment]
@pzhangleo  我碰到同样的问题，`sudo gem install byebug` 就好了。
