### ISSUE TITLE
转换图标的时候报错   是什么问题

### ISSUE THREAD

**Issue by yingnierxiao** [FIRHQ/fir-cli#212]
Converting app's icon......
No such file or directory @ rb_file_s_size - /var/folders/sd/d3dc79797rg6t_zhnhsddm880000gp/T/uncrushed_icon20180920-66921-lhp6pf.png
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:89:in `size'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:89:in `icon_information'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:55:in `block (2 levels) in <module:Publish>'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:42:in `upload_app'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:18:in `publish'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/cli.rb:118:in `publish'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/cli.rb:183:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:22:in `load'
/usr/local/bin/fir:22:in `<main>'

**Comment by jicheng1014** [comment]
试试  ruby 2.4.2 版本的?   这个我还真没出现过   要不把你apk 发过来我试试?

**Comment by yhrun** [comment]
No such file or directory @ rb_file_s_size - /var/folders/5w/cjtdbddd5hj2y4w7qz6g0_n00000gn/T/uncrushed_icon20190313-78064-1iareb9.png
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:89:in `size'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:89:in `icon_information'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:55:in `block (2 levels) in <module:Publish>'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:42:in `upload_app'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:18:in `publish'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/cli.rb:118:in `publish'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/lib/fir/cli.rb:183:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.12/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:22:in `load'
/usr/local/bin/fir:22:in `<main>'
