### ISSUE TITLE
能不能新增个功能查看某个 App 的 fir 最新版本?

### ISSUE THREAD

**Issue by iBenjamin** [FIRHQ/fir-cli#213]
我们现在是某个功能做了会打一个包然后上传测试，但是版本号相同会把之前的覆盖，我想得到 fir 上最新的版本然后就可以 +1 ，就不会覆盖了。

**Comment by iBenjamin** [comment]
哪里？我没有在 fir-cli 里面找到

**Comment by jicheng1014** [comment]
他不在 fir-cli 里  是在 open-api 里    你可以自行实现   有时间我把它也加到cli里把  😄

**Comment by iBenjamin** [comment]
😢 open-api 在哪里啊，我找了一圈没找到。

**Comment by iBenjamin** [comment]
找到了

**Comment by jicheng1014** [comment]
https://fir.im/docs/version_detection
