### ISSUE TITLE
Jenkins上fir 上传报错401，本地命令行执行OK

### ISSUE THREAD

**Issue by 888niannianwang** [FIRHQ/fir-cli#217]
401 Unauthorized
/Users/qa/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/Users/qa/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:853:in `start'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:63:in `block in basic_request'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `times'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `basic_request'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:8:in `block (2 levels) in <module:DefaultRestModule>'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.6.12/lib/fir/util.rb:36:in `fetch_user_info'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:216:in `check_supported_file_and_token'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.6.12/lib/fir/util/publish.rb:9:in `publish'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.6.12/lib/fir/cli.rb:118:in `publish'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.6.12/lib/fir/cli.rb:183:in `invoke_command'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/qa/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.6.12/bin/fir:8:in `<top (required)>'
/Users/qa/.rvm/gems/ruby-2.3.0/bin/fir:23:in `load'
/Users/qa/.rvm/gems/ruby-2.3.0/bin/fir:23:in `<main>'
Restclient error, body = {"errors":{"exception":["Authentication failed"]},"code":100020}
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by 888niannianwang** [comment]
发现带上Token上传就会报错401，去掉Token因为之前login过，就上传OK了

**Comment by jicheng1014** [comment]
我猜是 api_token 过期了吧?

**Comment by jicheng1014** [comment]
你查看下 jenkins 里配置的fir-cli 的 api-token 是否与系统里的一致?
