### ISSUE TITLE
fir publish 上传图标失败

### ISSUE THREAD

**Issue by wangxl056** [FIRHQ/fir-cli#218]
I, [2018-11-23T10:43:54.834964 #9729]  INFO -- : Publishing app via .......
I, [2018-11-23T10:43:54.835037 #9729]  INFO -- : ✈ -------------------------------------------- ✈
I, [2018-11-23T10:43:59.325724 #9729]  INFO -- : Fetching @fir.im uploading info......
I, [2018-11-23T10:43:59.325773 #9729]  INFO -- : Uploading app: wonenglicai-real-4.4.0(Build 60)
I, [2018-11-23T10:43:59.528320 #9729]  INFO -- : Uploading app icon......
I, [2018-11-23T10:43:59.528423 #9729]  INFO -- : Converting app's icon......
E, [2018-11-23T10:44:00.985660 #9729] ERROR -- : Uploading app icon failed

**Comment by jicheng1014** [comment]
偶发么?  还是持续的   如果是持续的  能否提供下包体我研究下?

**Comment by wangxl056** [comment]
Jenkins打包调用fir时阶段性持续失败，每次成功后，隔几个小时不用fir命令，再次使用Jenkins调用fir命令时会连续失败，apk下载链接：https://fir.im/x4eh

**Comment by wangxl056** [comment]
> 偶发么? 还是持续的 如果是持续的 能否提供下包体我研究下?
Jenkins打包调用fir时阶段性持续失败，每次成功后，隔几个小时不用fir命令，再次使用Jenkins调用fir命令时会连续失败，apk下载链接：https://fir.im/x4eh

**Comment by jicheng1014** [comment]
请更新下 fir-cli 的版本

之前上传做过重大调整  我不太清楚您这边的fir-cli version
