### ISSUE TITLE
Permission denied @ rb_sysopen - /.fir-cli-app

### ISSUE THREAD

**Issue by seumxc** [FIRHQ/fir-cli#219]
使用jenkins脚本运行fir publish发布apk应用，报错，但是手动在终端执行fir publish能正常发布
fir publish [dir/file.apk] -T [######API TOKEN########]
Permission denied @ rb_sysopen - /.fir-cli-app
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/config.rb:33:in `initialize'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/config.rb:33:in `open'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/config.rb:33:in `write_app_info'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:140:in `fetch_app_info'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:49:in `upload_app'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:16:in `publish'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/cli.rb:119:in `publish'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/lib/fir/cli.rb:184:in `invoke_command'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.3.0/gems/fir-cli-1.6.6/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'

**Comment by jicheng1014** [comment]
建议你更新下你的 fir-cli  版本
