### ISSUE TITLE
fir publish :uploading app binary failed

### ISSUE THREAD

**Issue by hahaGitHub** [FIRHQ/fir-cli#222]
I, [2018-12-11T17:08:26.030143 #43995]  INFO -- : Uploading app icon......
I, [2018-12-11T17:08:26.030313 #43995]  INFO -- : Converting app's icon......
I, [2018-12-11T17:08:26.772816 #43995]  INFO -- : Uploading app binary......

之后等着然后就失败了，请问如何解呢？

我的命令是：fir publish xx.ipa -T token

**Comment by jicheng1014** [comment]
版本是多少  麻烦看一下呗?
