### ISSUE TITLE
上传会传最早的一个ipa

### ISSUE THREAD

**Issue by lxzhh** [FIRHQ/fir-cli#23]
我用命令直接打包并上传
fir b project_path -o export_path ONLY_ACTIVE_ARCH=NO -w -C Debug -S schemeName -p -c "fix bugs"

这样每次在这个export_path会生成一个ipa，但它每次上传的都是最早的那个，而不会上传我刚build出来的这个

**Comment by NaixSpirit** [comment]
@lxzhh 了解了, 下个版本会修正这个 bug

**Comment by NaixSpirit** [comment]
@lxzhh 1.2.9 版本已经修复了这个 bug
