### ISSUE TITLE
--no-qrcode是不生成二维码的意思吗

### ISSUE THREAD

**Issue by 37Jayden** [FIRHQ/fir-cli#233]
fir publish APP_FILE_PATH -Q --no-qrcode，这个命令对吗，怎么还是会生成二维码？？

**Comment by jicheng1014** [comment]
额  是这样的, 因为当时加dingtalk 的时候需要这个文件, 所以就生成了二维码图片了, 实在不好意思, 下个版本会做个扫尾工作      您先临时写个脚本删除下吧

**Comment by jicheng1014** [comment]
额  是这样的, 因为当时加dingtalk 的时候需要这个文件, 所以就生成了二维码图片了, 实在不好意思, 下个版本会做个扫尾工作      您先临时写个脚本删除下吧

**Comment by jicheng1014** [comment]
已经跟新到了 1.7.2   如果不要图片  直接使用  fir publish xxx.ipa   就可以了
