### ISSUE TITLE
可以关联企业微信吗？

### ISSUE THREAD

**Issue by quietStefan** [FIRHQ/fir-cli#234]
上传完之后可以关联企业微信吗？

**Comment by jicheng1014** [comment]
我回头研究下企业微信是咋玩的......

**Comment by jicheng1014** [comment]
已经确认了需求, 应该在2019年07月15日以后, 网站上会支持  企业微信的 webhook

**Comment by jicheng1014** [comment]
现在已经支持了哟

**Comment by quietStefan** [comment]
好的。谢谢

**Comment by quietStefan** [comment]
更新企业微信要怎么操作，没看到有相关文档哇

**Comment by quietStefan** [comment]
这个只能关联到群吗？感觉这样就很鸡肋了。
应该很多的分支都不需要群知晓，这个打扰太多了。

**Comment by jicheng1014** [comment]
https://fir.im/support/articles/webhook/wechat

微信机器人的功能似乎只支持到群呢      
我在钉钉是这么玩的  先加个人建立一个群 之后把这个人移出去, 群还在, 就自己一个人
