### ISSUE TITLE
Error: ruby use system(fir me)

### ISSUE THREAD

**Issue by ZionChang** [FIRHQ/fir-cli#235]
在fastlane或者直接进入到/usr/local/bin执行fir，都会报以下错误，如果在终端在直接执行fir相关命令是ok的，日志如下，请问有什么办法解决吗

    Last login: Wed Jul  3 16:52:38 on ttys001
    /usr/local/bin/fir ; exit;
    ➜  ~ /usr/local/bin/fir ; exit;
    Traceback (most recent call last):
	4: from /Users/xxx/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	3: from /Users/xxx/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	2: from /usr/local/bin/fir:23:in `<main>'
	1: from /Users/xxx/.rvm/rubies/ruby- 
    2.6.3/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:482:in `block in 
    replace_bin_path'
    /Users/xxx/.rvm/rubies/ruby-    
    2.6.3/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:462:in `block in    
    replace_bin_path': can't find executable fir for gem fir-cli. fir-cli is not currently included in 
    the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)

### 版本信息

* fastlane 2.126.0
* ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
* gem 3.0.4
* fir-cli 1.7.2

**Comment by jicheng1014** [comment]
好像是因为环境变量的问题   
您可能需要将 rvm 里对应的  bin 绑在环境变量里

**Comment by ZionChang** [comment]
@jicheng1014 就是感觉哪儿环境出错了，不过找了好久没找到怎么配置。尴尬

**Comment by jicheng1014** [comment]
可以加我微信咱详聊

**Comment by ZionChang** [comment]
@jicheng1014 请问你微信？

**Comment by jicheng1014** [comment]
atpking    readme 上有哟  另外 fastlane 有官方插件  fastlane-plugin-fir_cli
