### ISSUE TITLE
上传ipa包到fir的时候报错 fir login error

### ISSUE THREAD

**Issue by cssshuang** [FIRHQ/fir-cli#236]
Ignoring bcrypt-3.1.11 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.11
Ignoring bindex-0.5.0 because its extensions are not built.  Try: gem pristine bindex --version 0.5.0
Ignoring byebug-9.0.6 because its extensions are not built.  Try: gem pristine byebug --version 9.0.6
Ignoring oj-3.6.5 because its extensions are not built.  Try: gem pristine oj --version 3.6.5
Ignoring unf_ext-0.0.7.5 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.5
Ignoring executable-hooks-1.5.0 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.5.0
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18
Ignoring gem-wrappers-1.4.0 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.4.0
Ignoring nio4r-2.1.0 because its extensions are not built.  Try: gem pristine nio4r --version 2.1.0
Ignoring nokogiri-1.8.0 because its extensions are not built.  Try: gem pristine nokogiri --version 1.8.0
Ignoring puma-3.9.1 because its extensions are not built.  Try: gem pristine puma --version 3.9.1
Ignoring sqlite3-1.3.13 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.13
Ignoring therubyracer-0.12.3 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.3
Ignoring websocket-driver-0.6.5 because its extensions are not built.  Try: gem pristine websocket-driver --version 0.6.5
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': incompatible library version - /Users/zz/.rvm/gems/ruby-2.5.1@global/gems/oj-3.6.5/lib/oj/oj.bundle (LoadError)
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/zz/.rvm/gems/ruby-2.5.1@global/gems/oj-3.6.5/lib/oj.rb:21:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/zz/.rvm/gems/ruby-2.5.1@global/gems/api_tools-0.0.6/lib/api_tools/default_rest.rb:6:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/zz/.rvm/gems/ruby-2.5.1@global/gems/api_tools-0.0.6/lib/api_tools.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/zz/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.10/lib/fir/util/http.rb:4:in `<top (required)>'
	from /Users/zz/.rvm/gems/ruby-2.5.1@global/gems/fir-cli-1.6.10/lib/fir/util.rb:3:in `require_relative'
	from /Users/zz/.rvm/gems/ruby-2.5.1@global/gems/fir-cli-1.6.10/lib/fir/util.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/zz/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.10/lib/fir.rb:23:in `<top (required)>'
	from /Users/zz/.rvm/gems/ruby-2.5.1@global/gems/fir-cli-1.6.10/bin/fir:4:in `require_relative'
	from /Users/zz/.rvm/gems/ruby-2.5.1@global/gems/fir-cli-1.6.10/bin/fir:4:in `<top (required)>'
	from /usr/local/bin/fir:23:in `load'
	from /usr/local/bin/fir:23:in `<main>'
fir login error...

**Comment by jicheng1014** [comment]
老哥, 先更新下  fir-cli  呗   我这最新版是没问题的

**Comment by cssshuang** [comment]
非常感谢指导,确实是我电脑上的fir-cli不是最新版本导致的,更新后再进行上传ipa包到fir就正常了,多谢啦~
