### ISSUE TITLE
完善使用文档

### ISSUE THREAD

**Issue by NaixSpirit** [FIRHQ/fir-cli#24]

**Comment by guoxj** [comment]
你好，第一步能不能把如何从源码编译成可执行文件的步骤列一下

非常感谢

**Comment by NaixSpirit** [comment]
@guoxj 你好, 由于 ruby 是一门脚本语言, 所以不存在编译这个环节, 实际上, `fir` 这个命令, 就是在执行这个文件 https://github.com/FIRHQ/fir-cli/blob/master/bin/fir
