### ISSUE TITLE
用 Ad-Hoc 打出的同一个包，用浏览器在 fir.im 上传显示为「内测版」，使用 fir-cli 上传显示为「企业版」

### ISSUE THREAD

**Issue by EdgarDegas** [FIRHQ/fir-cli#241]
## 环境
- 打包工具
    - Xcode 10.3
    - Xcode 10.2 上的 Xcode Server

- 上传方式：Docker 镜像（firhq/fir-cli:latest）

## 现象
从上至下分别是用 fir-cli Docker 镜像上传的包，与在 Web 页面上传的包：

![fir-cli Docker 镜像上传的包，与在 Web 页面上传的包](https://user-images.githubusercontent.com/12840982/62843607-a9969580-bced-11e9-8ac6-0dfa523a7ed1.png)

**Comment by jicheng1014** [comment]
哦?   应该是包解析错误了     我研究下?   方便说下短链或者是 发一下  ipa 包么?

**Comment by jicheng1014** [comment]
下载其实不影响   只是影响显示呢

**Comment by EdgarDegas** [comment]
看起来确实是不影响使用。
总之，短链接已经发到你的 Gmail。

**Comment by jicheng1014** [comment]
实在是抱歉, 不知是否能够微信联系一下? 我的微信是 atpking
