### ISSUE TITLE
iOS "fir pulish xxx.ipa -T xxx" 报错

### ISSUE THREAD

**Issue by FantasticSkyBaby** [FIRHQ/fir-cli#242]
如题，检查了包内容所有参数完整

/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:154:in `rbuf_fill'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/Users/macbook/.rvm/gems/ruby-2.3.0@global/gems/rest-client-2.1.0/lib/restclient/request.rb:473:in `net_http_do_request'
/Users/macbook/.rvm/gems/ruby-2.3.0@global/gems/rest-client-2.1.0/lib/restclient/request.rb:733:in `block in transmit'
/Users/macbook/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:853:in `start'
/Users/macbook/.rvm/gems/ruby-2.3.0@global/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
/Users/macbook/.rvm/gems/ruby-2.3.0@global/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
/Users/macbook/.rvm/gems/ruby-2.3.0@global/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:66:in `block in basic_request'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `times'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `basic_request'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:10:in `block (2 levels) in <module:DefaultRestModule>'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.7.2/lib/fir/util.rb:36:in `fetch_user_info'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.7.2/lib/fir/util/publish.rb:235:in `check_supported_file_and_token'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.7.2/lib/fir/util/publish.rb:6:in `publish'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.7.2/lib/fir/cli.rb:120:in `publish'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.7.2/lib/fir/cli.rb:167:in `invoke_command'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Users/macbook/.rvm/gems/ruby-2.3.0/gems/fir-cli-1.7.2/bin/fir:8:in `<top (required)>'
/Users/macbook/.rvm/gems/ruby-2.3.0/bin/fir:23:in `load'
/Users/macbook/.rvm/gems/ruby-2.3.0/bin/fir:23:in `<main>'
/Users/macbook/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/macbook/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jicheng1014** [comment]
湖南电信地区最近网络有点问题      我们已经联系了当地运营商了   应该这今天已经恢复了  

如果没有恢复  你可以先将机器的dns 改成114.114.114.114  也可以
