### ISSUE TITLE
希望能和蒲公英的上传app一样方便。

### ISSUE THREAD

**Issue by fwh1990** [FIRHQ/fir-cli#243]
蒲公英和fir.im都有用。

用蒲公英的接口上传只要一个curl命令，带上file和key就行了。[查看文档](https://www.pgyer.com/doc/view/api#uploadApp)

用fir.im  的接口上传需要3个curl命令，拿token，上传icon，上传安装包。[查看文档](https://fir.im/docs/publish)

我是觉得可以更简单一些，毕竟icon、platform和bundle等信息可以直接在安装包里拿。而且你们的网页端不就是这么搞的嘛，拖一个apk或者ipa文件过去就行了。

-------

所以就是希望：**能用一个curl命令，带上file和token，就传成功了**。服务不也正是往更好用、更方便、更稳定的方向去发展吗

**Comment by jicheng1014** [comment]
额 实现原理不一样吧    fir-cli 也是一个指令的 

只不过你说的那种  用curl 的 我这也可以考虑实现一个  :D

**Comment by fwh1990** [comment]
我说的是api层面的。不是指这个库。

**Comment by fwh1990** [comment]
我其实就是想用shell简简单单地把事情给做了。蒲公英的上传api接口够简单，什么都不用处理，打包文件传给它就行了，自动获取各种信息。fir.im的上传api接口稍微有点复杂，虽然也能用shell实现

**Comment by fwh1990** [comment]
所以如果有考虑在`服务端`做一些自动处理的话，其实就不需要那么多的cli工具了，大家维护起来也方便

**Comment by fwh1990** [comment]
对于用户来讲，一步就能完成的任务，要拆成3步处理，不太明白是基于什么考虑。

**Comment by jicheng1014** [comment]
哦哦哦, 不好意思理解错了

api 层面的话   是因为我们因为带宽和速度的考虑

实际上我们并不直接接收用户的文件, 而是直接传到云厂商的 bucket 中

pgyer 是传服务器, 之后服务器分析完毕, 再用服务器传云厂商 

我们这种上传会快一点点,  pgyer 那种会慢一点点

**Comment by jicheng1014** [comment]
你这种需求的话  倒是可以单开一条线来做, 只是如果要保证上传速度快, 我就得将服务器带宽调比较大

ps  "而且你们的网页端不就是这么搞的嘛，拖一个apk或者ipa文件过去就行了。"    其实还是请求的三次

**Comment by fwh1990** [comment]
希望能出一个这种api，毕竟竞品有的，我们也必须有，没有也得有（滑稽脸）。最主要是方便了想去DIY，想把api集成到更多服务里的开发者们。

你们是用阿里云吗？是的话就好办了，直接内网传到阿里云的OSS。然后也可以回源到七牛

**Comment by fwh1990** [comment]
我发现你们用的是百度云，所以BOS也是一样的

**Comment by fwh1990** [comment]
是否有计划呢？大概要多久能够实现呢？期待

**Comment by jicheng1014** [comment]
因为这个需要额外的上传带宽, 目前估计不太好批下来这个需求

**Comment by hnyer** [comment]
根据fir的官方api封装的一个 Androidstudio插件，用来更方便地上传Apk， 
插件 和源码地址   https://gitee.com/hnyer/FirApkUploadPluginX
