### ISSUE TITLE
macOS Catalina 10.15 上传ruby路径出错

### ISSUE THREAD

**Issue by laughing25** [FIRHQ/fir-cli#245]
macOS Catalina 10.15 使用出错
/usr/local/bin/fir: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by wpwb110** [comment]
重新安装一下，貌似好使

**Comment by jicheng1014** [comment]
我会说我还没升级到   10.15么  

好像10.15 会取消包括 ruby, python 等默认安装的脚本语言....

**Comment by jicheng1014** [comment]
我升级 10.15 测试了下, 好像系统默认的ruby 确实被删除了   需要先安装ruby 才能使用的
