### ISSUE TITLE
使用Mac自动操作无法使用fir命令

### ISSUE THREAD

**Issue by yumengqing** [FIRHQ/fir-cli#246]
通过一个使用shell脚本上传app(iOS), 在终端运行的时候，可以正常上传app, 但是使用Mac自带的自动操作来执行shell脚本，fir命令居然找不到，是为什么了？。
自动操作： 启动台-> 其他-> 自动操作(顶部新建应用，搜索shell，导入shell脚本路径)

脚本示例
`
#! /bin/sh
echo "将执行fir命令"
fir --version  #在自动操作中无效 终端执行可行
/usr/local/bin/fir --version  # 本机fir的路径，自动操作和终端都可以
alias a_fir=`/usr/local/bin/fir`
a_fir me
if [ $? -eq 0 ]; then
    echo "fir 命令执行成功"
else
    echo "执行失败"
fi
exit 0`

**Comment by jicheng1014** [comment]
我猜是环境变量惹的祸?     要不先source 下 bashrc?

**Comment by jicheng1014** [comment]
可以加我微信详细沟通  atpking
