### ISSUE TITLE
--changelog问题

### ISSUE THREAD

**Issue by watermelon520** [FIRHQ/fir-cli#247]
我是想要使用最近20条gitlog作为changelog，发现上传上去之后，在更新信息里只能看到第一条gitlog

代码类似如下

lastBuildDate=2019-11-11 12:12:00
changeLog=`git log -20 --no-merges --date-order --after="${lastBuildDate}" --date=format:'%Y-%m-%d %H:%M:%S' --pretty=format:'%cd %h <%an> %s'`

fir p ${uploadFilePath} -T ${firImAPIToken} --changelog="${changeLog}"

是内部会做截断？我之前使用curl方法是可以传上去的

**Comment by jicheng1014** [comment]
稍等我试试这个情况

**Comment by jicheng1014** [comment]
您可以  先将日志结果输出到一个临时文件, 之后changlog 指向这个文件即可  

您可以参考下
```
echo $changeLog > changelog.txt
fir p ${uploadFilePath} -T ${firImAPIToken} --changelog=./changelog.txt
rm changlog.txt

```
