### ISSUE TITLE
Linux centos安装fir-cli失败

### ISSUE THREAD

**Issue by yinbiaos** [FIRHQ/fir-cli#249]
[root@redis-164 ~]# sudo gem install fir-cli
Building native extensions. This could take a while...
ERROR:  Error installing fir-cli:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.6/ext/unf_ext
/usr/bin/ruby -r ./siteconf20191125-8328-e20j8z.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

**Comment by jicheng1014** [comment]
sudo yum install ruby-devel   先装ruby 的高版本
