### ISSUE TITLE
publish already exists! 

### ISSUE THREAD

**Issue by Invincible1996** [FIRHQ/fir-cli#250]
/Users/xxx/.rvm/gems/ruby-2.6.0/gems/fir-0.1.4/lib/fir/generator.rb:15:in `generate!': publish already exists! Aborting. (RuntimeError)
<img width="1023" alt="WechatIMG15" src="https://user-images.githubusercontent.com/22675676/69903224-dae8bd80-13d1-11ea-9528-7bc5547e9136.png">
https://guides.github.com/features/mastering-markdown/

**Comment by jicheng1014** [comment]
小老弟   你的这个gem 不对     

如果你要在fastlane 里使用的话   

使用官方支持的 `fastlane add_plugin fir_cli`
