### ISSUE TITLE
publish给钉钉机器人的式样能我们自己控制嘛

### ISSUE THREAD

**Issue by yushilong** [FIRHQ/fir-cli#253]
现在这个式样有点满足不了需求，而且logo特别大。。我们又不能改。。

**Comment by jicheng1014** [comment]
请fork

**Comment by jicheng1014** [comment]
请fork

**Comment by yushilong** [comment]
fork然后修改了，怎么用fir-cli的publish呢

**Comment by jicheng1014** [comment]
所有信息最后的日志输出都有   

本质上钉钉只是个  curl 请求  你可以根据自己的需求去实现自己想要的样式

**Comment by jicheng1014** [comment]
在你自己的项目下  rake install 即可

**Comment by yushilong** [comment]
好的 我试试 谢谢啦

**Comment by jicheng1014** [comment]
你也可以修改   fir-cli.gemspec    生成自己的 gem 唯一标识    之后  rake release 发表自己的gem 到网上

**Comment by jicheng1014** [comment]
你也可以修改   fir-cli.gemspec    生成自己的 gem 唯一标识    之后  rake release 发表自己的gem 到网上

**Comment by yushilong** [comment]
你好 rake install这个怎么用？我想是不是这样的
先git@github.com:yushilong/fir-cli.git到本地 然后修改publish.rb文件这里的代码
`def dingtalk_notifier(download_url, qrcode_path)
      return if options[:dingtalk_access_token].blank?

      title = "#{@app_info[:name]}-#{@app_info[:version]}(Build #{@app_info[:build]})"
      payload = {
        "msgtype": 'markdown',
        "markdown": {
          "title": "#{title} uploaded",
          "text": "#{title} uploaded at #{Time.now}\nurl: #{download_url}\n ![app二维码](data:image/png;base64,#{Base64.strict_encode64(File.read(open(qrcode_path)))})"
        }
      }
      url = "https://oapi.dingtalk.com/robot/send?access_token=#{options[:dingtalk_access_token]}"

      # 用完了二维码, 就删了
      File.delete(qrcode_path) unless @export_qrcode

      DefaultRest.post(url, payload)
    rescue StandardError => e
      logger.warn "Dingtalk send error #{e.message}"
    end`
然后rake install https://github.com/yushilong/fir-cli/blob/master/Gemfile吗？
然后就可以使用fir publish了吗？

**Comment by yushilong** [comment]
@jicheng1014 有空帮忙解答一下嘛？

**Comment by jicheng1014** [comment]
在你的项目目录下 直接输入  `rake install`   即会安装你自己修改后的  fir-cli  

你如果就自用  就到这步就结束了, 你之后用的  fir-cli 就是自己的修改

如果你想分享给你的同事  第一步, 是去 fir-cli.gemspec 里修改spec_name 

之后去网上找下 如何发布自己的gem 到 rubygems.org  或者官网看示例也行

**Comment by jicheng1014** [comment]
你要是对ruby 不熟悉  你可以不用fir-cli 里的dingtalk     而是写个脚本 从fir-cli 的输出中获取你要的信息, 自行实现一个对钉钉机器人地址的curl 即可

**Comment by yushilong** [comment]
写个脚本 从fir-cli 的输出中获取你要的信息 . 这个怎么写，完全不会。。。 @jicheng1014

**Comment by yushilong** [comment]
还有这个命令没作用--force_pin_history，并不会在页面下边显示

**Comment by jicheng1014** [comment]
"写个脚本 从fir-cli 的输出中获取你要的信息 . 这个怎么写，完全不会。。。 @jicheng1014"     ???  要不你可以考虑下买我们的私有部署  我帮你实现你要的功能

"还有这个命令没作用--force_pin_history，并不会在页面下边显示"   => 当前版本不会  你下一个版本上传的时候   就在了
