### ISSUE TITLE
fir-cli's executable "console" conflicts with wannabe_bool

### ISSUE THREAD

**Issue by jerryzhoujw** [FIRHQ/fir-cli#254]
> a@a> gem list | grep "fir"
fir-cli (1.6.12)
a@a> gem install fir-cli
Fetching: ruby_android_apk-0.7.7.1.gem (100%)
Successfully installed ruby_android_apk-0.7.7.1
Fetching: api_tools-0.1.0.gem (100%)
Successfully installed api_tools-0.1.0
Fetching: fir-cli-2.0.0.gem (100%)
fir-cli's executable "console" conflicts with wannabe_bool
Overwrite the executable? [yN]

Will this have problem to overwrite `wannabe_bool` directly ?

> a@a> gem install wannabe_bool
wannabe_bool's executable "console" conflicts with fir-cli

try to install `wannabe_bool` again, it still show error.

**Comment by jicheng1014** [comment]
hello,

**Comment by jicheng1014** [comment]
Hi, u had a command 'console' by wannabe_bool before, that is conflict with fir-cli, and if u are sure that u will not use wanabe_bool provided 'console', u can run `gem uninstall wannable_bool`, or just overwrite the console.   if shit happens, run 'gem install wannable_bool' or gem uninstall fir-cli to rollback

if u are not sure, u can use fir-cli docker version.

**Comment by jerryzhoujw** [comment]
@jicheng1014 Thank you. I removed `wannable_bool` to make it work first.
