### ISSUE TITLE
境外上传的老是超时，有没有办法解决？

### ISSUE THREAD

**Issue by peterleng** [FIRHQ/fir-cli#256]
我们公司使用的是circleci，属于境外上传，上传apk或ipa的时候都会失败，报错是超时了，有什么办法可以解决呢？ `FIR_TIMEOUT` 这个参数怎么用？ 它的单位是秒还是什么？
<img width="1254" alt="WX20191209-145734@2x" src="https://user-images.githubusercontent.com/7566681/70414178-44cd2b00-1a94-11ea-99d7-1d344b68035e.png">

**Comment by jicheng1014** [comment]
参数是秒  
FIR_TIMEOUT=300 fir p xxxxx

**Comment by peterleng** [comment]
> 参数是秒
> FIR_TIMEOUT=300 fir p xxxxx

**Comment by peterleng** [comment]
> 参数是秒
> FIR_TIMEOUT=300 fir p xxxxx

我使用了 export FIR_TIMEOUT=300， 为什么还是会等到10分钟后超时呢？
