### ISSUE TITLE
想个办法从根本上解决境外上传时失败的问题吧

### ISSUE THREAD

**Issue by peterleng** [FIRHQ/fir-cli#258]
境外服务器上传经常失败，超时等，从服务器上根本解决吧，只依赖设置参数无法根本解决

**Comment by jicheng1014** [comment]
这个问题从本质上来说是费用问题, 

由于监管问题, 我们必须将服务器, 存储等放置在境内以符合监管

阿里提供了 oss 境外加速服务, 但是费用高达 1.25 元 / GB 

以目前的收费方案是不行的   

如果实在有特殊需求, 也可购买我们的私有部署服务, 我们可以部署一套在境外

**Comment by jicheng1014** [comment]
具体可以参见 https://help.aliyun.com/document_detail/59636.html?spm=a2c4g.11186623.6.554.2212614f2K01NK
