### ISSUE TITLE
fir-cli上传InHouse打包的ipa，会自动变成内测版本

### ISSUE THREAD

**Issue by everettjf** [FIRHQ/fir-cli#26]
使用
```
fir p xxx.ipa -T mytoken
```
上传InHouse打包的ipa，会自动变成内测版本。

在网页上点击『上传新版本』就能自动识别为企业版本。
看了fir help，没找到什么信息。
我哪里做的不对吗？

**Comment by NaixSpirit** [comment]
你好, 这是一个 bug, cli 的解析器写错了个方法, 这就修正

**Comment by NaixSpirit** [comment]
@everettjf 请安装 1.3.3 版本

**Comment by everettjf** [comment]
@NaixSpirit 非常感谢。

**Comment by everettjf** [comment]
@NaixSpirit 你好，又发现一个区别。请看：https://github.com/FIRHQ/fir-cli/issues/28
