### ISSUE TITLE
[集中讨论海外加速贴] 使用 Circle CI 等境外服务, 提示 fir publish 失败

### ISSUE THREAD

**Issue by HectorHann** [FIRHQ/fir-cli#260]
环境：Circle CI
版本：fir-cli-2.0.0
问题：在Circle CI 中，fir publish命令经常失败，错误原因是超时。可能和境外访问有关系。

**Comment by jicheng1014** [comment]
https://github.com/FIRHQ/fir-cli/issues/258

参见这里

**Comment by jicheng1014** [comment]
另外你也可以在最后增加  --switch_to_qiniu    试试七牛的线路看下

**Comment by HectorHann** [comment]
七牛试了，不行。所以给个收费标准，使用你们服务，按年按月怎么收费。成为付费账户

**Comment by jicheng1014** [comment]
以目前的情况, 实在是抱歉, 目前的情况下, 确实没有很好的解决方案
如果十分迫切, 我建议您在香港搭一个 jenkins 服务器, 接收 circle ci 调用的 webhook, 在香港区上传, 经我们的测试, 我们的 oss 在香港表现尚可.
或者也可以联系客服 购买我们的私有部署方案.

如果不迫切, 就等我忽悠老板补贴一些钱来实现这个功能.

=====================================

这个问题, 确实非常困扰我, 我已经多次在 issue 上回答过这个问题, 每次我回答的也很纠结, 毕竟我也是开发者, 面对这种已知的问题, 特别尴尬.

我仅从自己的思路上来说这个事情, 
如果海外加速如果要单独收费, 涉及以下修改: 

- 海外加速切换, 以及防止国内用户用各种 hack 手段切换到这种服务
- 用户单独购买这类服务的购买模块
- 加速服务过期模块
- 因为现有计费方式逻辑不一样, 所以需要与现有的计费和结算做兼容
- 展示界面, 文档说明, 客服培训
 
所有但修改都包括了从需求分析直到对应的测试, 大家可以预估研发成本 

相关流量费用我已经提过,  这里做个不靠谱的估算: 
App 在 ci 肯定会多次跑, 先按每个 app 大小为50-150 M,  每天跑10次左右, 所以拍脑袋先定每天1G流量, 每天 1.25 元.
每个账户咱预估有2-3 个 app 在跑 ci , 大致就可以算出一个账户一个月会花掉 30-90 元的流量费用. 当然如果量大, 应该可以找供应商拿到一些优惠. 

研发费用+ 流量费用 平均分摊到用户上,  如果收 100 元 / 月估计大概率亏本. 200 元 / 月, 如果有一定规模 应该可以盈利. 但是经验告诉我们, 仅海外上传加速这个简单的功能就要这么高的费用, 用户肯定觉得我们是黑心奸商.  

另外购买这类服务的用户规模也是个比较麻烦的问题. 假设最终通过各类技术手段, 与服务商撕逼, 最终能从购买这类服务的用户手上月盈利 10 元. 对于公司层面可以预估一下, 为这类服务付费的用户的规模大概个数, 以及开发所花费的代价.

如果您是公司的负责人, 看到这个分析, 估计心里也会有一个结论. 

最后, 我也在试图说服老板烧钱补贴有这种海外加速需求等同学. 我尽量忽悠, 也欢迎有这类需求的用户在这个帖子后面 +1. 愿意支持我的同学欢迎支付宝扫码 Readme 下面的赞助链接补贴我 9.9 元购买 luckin 咖啡.  
有资金实力的用户, 也可以直接购买我们的私有部署服务.

**Comment by HectorHann** [comment]
感谢你这么详细耐心的解释。
虽然说需求只是海外加速，但实际操作会涉及很多部门。

因为要部署海外服务器，所以产生费用也是不可避免的。可否给使用者提供多个档位的套餐？

例如：我们用贵公司平台来管理测试包，所以下载量比较小，流量也比较小。

**Comment by jicheng1014** [comment]
可能我的表述还有点问题,   其实我们的成本大头不是在服务器上, 而是存储和 cdn 

目前您这个需求主要如果是贵在境外的上传加速这块, 费用较高, 

国内下载的话目前的收费策略还是可以基本涵盖 cdn 成本的.

ps, 如果最终忽悠老板下来了这个需求, 可能还要区分一下使用场景, 需要的朋友也可以回答下 :

1. 境外上传  境内下载:
这种我们可以在香港搭一个adapter,  转到境内的oss, 这种成本应该比较低, 但是会有一定的延迟, 取决于香港服务器的带宽. 

2. 境外上传  境外下载:

这种方式 就直接 aws s3 跑就好了

3. 境外上传, 全球下载, 小量:

这种方式估计是补贴一点钱做全球加速

4. 境外上传, 全球下载, 大量:

这种最麻烦, 费用最高

=================

另外就是费用定价问题, 不讨论下载情况, 只讨论上传情况, 如果要做海外加速, 大家能接受的价格是?

1. 50 元/月
2. 100 元/月
3. 200 元/月

或者换种思路, 根据上传的次数, 比如购买加速上传次数, 100次, 共计100元, 使用加速通道上传一次扣一块啥的.

**Comment by HectorHann** [comment]
境外上传, 全球下载, 小量
包月，包年都可以

**Comment by jicheng1014** [comment]
200 元每月  下载次数海外不超过每月1000次  接受么

**Comment by jicheng1014** [comment]
目前正在开发境外上传, 不日上线, 要参与内测的小伙伴可以在这里留下你们的 fir 账号信息, 内测期间产生的加速费用 fir 全额补贴

**Comment by lyf571321556** [comment]
lyf571321556@163.com +1 参与境外上传内测。。。  快被appcenter搞死了，还得专门给每台手机挂vpn才能下载

**Comment by jicheng1014** [comment]
@lyf571321556    现已支持， 您直接加参数开启海外加速即可
