### ISSUE TITLE
应用版本过期无法下载

### ISSUE THREAD

**Issue by quietStefan** [FIRHQ/fir-cli#264]
请问下，命令行上传版本有没办法自动打开【显示在下载页面】
希望平台可以保存近60天的版本；
只保留最新的30个版本有点太少了，分支多了之后上传的版本很快就过期了。
还有个问题，没太看明白--force_pin_history 这个参数要怎么使用，有示例可以提供下吗？

**Comment by jicheng1014** [comment]
就是这个参数   --force_pin_history   如  fir p 1.apk --force_pin_history      这个的含义就是  记录为历史版本, 当他不是最新版本的时候, 就会显示在下载页面的版本记录里

可以最多保存60 个版本 (30个最新版本 和 30 个历史版本)   目前满足绝大多数用户

至于 保留60 天的, 是策略不同, 目前基于我们的财务条件, 无法做到大规模的保存60天的版本.

如果您有特殊需求, 可以加我微信, 根据您之前的上传记录, 我可以适当增加您的保留版本个数

**Comment by quietStefan** [comment]
怎么区分是历史版本？即使用了--force_pin_history参数，在下载列表也看不出区别呀，
右边的那个【显示在下载页面】也没有自动打开。

**Comment by jicheng1014** [comment]
当使用--force_pin_histroy 这个应用的版本 不是最新版本的时候, web 界面才会显示出来这个 "显示在下载页面"    

参数加在最后面   如   `fir p 1.apk --force_pin_histroy` 或 `fir p 1.apk -H`

如果还有问题  可以微信联系我, 告知您的具体app 我在后台帮您查一下

**Comment by jicheng1014** [comment]
另外建议您升级下 fir-cli  之前有个用户跟您类似的问题  最后发现他的fir 版本在1.7.2  好像这个版本还不支持这个参数
