### ISSUE TITLE
fir publish失败

### ISSUE THREAD

**Issue by howard0103** [FIRHQ/fir-cli#265]
/Library/Ruby/Gems/2.6.0/gems/ruby_android_apk-0.7.7.1/lib/android/apk.rb:41:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/lib/fir/util/parser/apk.rb:11:in `new'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/lib/fir/util/parser/apk.rb:11:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/lib/fir/util/info.rb:43:in `new'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/lib/fir/util/info.rb:43:in `apk_info'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/lib/fir/util/publish.rb:219:in `initialize_publish_options'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/lib/fir/util/publish.rb:10:in `publish'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/lib/fir/cli.rb:138:in `publish'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/lib/fir/cli.rb:185:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'

**Comment by howard0103** [comment]
有人帮我看看吗？thanks very much

**Comment by jicheng1014** [comment]
日志没贴全阿朋友

**Comment by howard0103** [comment]
> 日志没贴全阿朋友

昨天一直不行，刚试了一下，秒上传成功了呀。-_-
