### ISSUE TITLE
iOS fir publish 出错了 老哥帮我看看

### ISSUE THREAD

**Issue by zhuxinleibandou** [FIRHQ/fir-cli#266]
/Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/api_tools-0.1.0/lib/api_tools/default_rest.rb:2:in `require_relative': /Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:81: syntax error, unexpected '.' (SyntaxError)
        response_code: exception&.response&.code,
                                  ^
/Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:107: syntax error, unexpected end-of-input, expecting keyword_end
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/api_tools-0.1.0/lib/api_tools/default_rest.rb:2:in `<top (required)>'
	from /Users/zhuxl/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhuxl/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/api_tools-0.1.0/lib/api_tools.rb:2:in `<top (required)>'
	from /Users/zhuxl/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhuxl/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/admqr_knife-0.1.5/lib/admqr_knife.rb:4:in `<top (required)>'
	from /Users/zhuxl/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhuxl/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/fir-cli-2.0.3/lib/fir.rb:7:in `<top (required)>'
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/fir-cli-2.0.3/bin/fir:4:in `require_relative'
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/gems/fir-cli-2.0.3/bin/fir:4:in `<top (required)>'
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/bin/fir:22:in `load'
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/bin/fir:22:in `<main>'
	from /Users/zhuxl/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/zhuxl/.rvm/gems/rub

**Comment by jicheng1014** [comment]
ruby 版本 需要在 2.4 以上

**Comment by zhuxinleibandou** [comment]
> ruby 版本 需要在 2.4 以上

好的，我下午升级一下，谢谢老哥，提前祝你新年快乐
