### ISSUE TITLE
是不是不能指定iOS打包完成以后ipa 的文件名

### ISSUE THREAD

**Issue by guoxj** [FIRHQ/fir-cli#27]
谢谢你们的产品
如题

**Comment by NaixSpirit** [comment]
@guoxj 是的, 目前 ipa 的命名方式是 `ipaName-ipaVersion-build-ipaBuild`, 这样做的目的是为了让 daily build 出来的 app 更加清晰和方便的辨别版本, 如果 `指定 ipa 文件名` 这个需求很强烈的话我可以 想想办法加上

**Comment by guoxj** [comment]
你好，我尝试自己改下，然后编译，出现错误。我装的ruby 2.0.0  
因为初次接触，能给点提示么？ 
不胜感激
xiaojiedeMacBook-Pro:lib guoxj$ ruby fir.rb
/Users/guoxj/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- thor (LoadError)
	from /Users/guoxj/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from fir.rb:3:in `<main>'
xiaojiedeMacBook-Pro:lib guoxj$

**Comment by guoxj** [comment]
是不是我有什么依赖没有安装呢？
因为之前没接触过ruby 对环境不太熟悉。如果你能整理下编译安装的步骤就最好不过了。
谢谢

**Comment by NaixSpirit** [comment]
@guoxj 如果使用 `gem install fir-cli` 正常安装顺利的话, 你可以使用 `which fir` 来查看 `fir` 这个命令是在哪里, 由于脚本语言没有编译环节, 直接运行即可.
