### ISSUE TITLE
gem install fir-cli 成功后，执行报错undefined method `_info' for FIR:Module

### ISSUE THREAD

**Issue by tang786472181** [FIRHQ/fir-cli#270]
firimResult=$(fir publish -T $firToken $uploadfFilePath -c $uploadfRemark)
脚本执行到这里的时候报错，firToken有有值，uploadfFilePath有值 ，uploadfRemark有值

报错内容如下：
undefined method `_info' for FIR:Module
Did you mean?  info
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.3.1/lib/fir/util/publish.rb:219:in `initialize_publish_options'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.3.1/lib/fir/util/publish.rb:10:in `publish'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.3.1/lib/fir/cli.rb:138:in `publish'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.3.1/lib/fir/cli.rb:185:in `invoke_command'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.3.1/bin/fir:8:in `<top (required)>'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/bin/fir:23:in `load'
/Users/tangxiaohu/.rvm/gems/ruby-2.6.3/bin/fir:23:in `<main>'

麻烦帮忙看下

**Comment by jicheng1014** [comment]
请问升级到最新版本后还有这个么?   最新版本是2.0.4

**Comment by fabcz** [comment]
+1，版本已更新到 2.0.5 了

**Comment by jicheng1014** [comment]
> +1，版本已更新到 2.0.5 了

2.0.5 还是这个问题么?

**Comment by fabcz** [comment]
是的，无论是直接用 fastlane 的 fastlane run fir_cli api_token:"xxx" specify_file_path:"./build/" 还是 fir-cli 的 fir publish "./build/" 都是同样的报错

**Comment by fabcz** [comment]
> > +1，版本已更新到 2.0.5 了
> 
> 2.0.5 还是这个问题么?

是的，无论是直接用 fastlane 的 fastlane run fir_cli api_token:"xxx" specify_file_path:"./build/" 还是 fir-cli 的 fir publish "./build/" 都是同样的报错

**Comment by jicheng1014** [comment]
哦?    文件存在么?

**Comment by jicheng1014** [comment]
> > > +1，版本已更新到 2.0.5 了
> > 
> > 
> > 2.0.5 还是这个问题么?
> 
> 是的，无论是直接用 fastlane 的 fastlane run fir_cli api_token:"xxx" specify_file_path:"./build/" 还是 fir-cli 的 fir publish "./build/" 都是同样的报错

老哥  文件存在不?     方便加微信聊不?

**Comment by fabcz** [comment]
> > > > +1，版本已更新到 2.0.5 了
> > > 
> > > 
> > > 2.0.5 还是这个问题么?
> > 
> > 
> > 是的，无论是直接用 fastlane 的 fastlane run fir_cli api_token:"xxx" specify_file_path:"./build/" 还是 fir-cli 的 fir publish "./build/" 都是同样的报错
> 
> 老哥 文件存在不? 方便加微信聊不?

wx：chengcongweibo

**Comment by pengzai170** [comment]
这个是什么问题？我也遇到了

**Comment by jicheng1014** [comment]
是因为文件没找到  导致的,  最新版  (version 2.0.7) 已经将这种错误强提示出来了
