### ISSUE TITLE
2.0.3.1  fir publish xxx.ipa -s short 报错

### ISSUE THREAD

**Issue by fakepinge** [FIRHQ/fir-cli#271]
fir publish xxx.ipa -s short  执行到Updating app info 就报错400 Bad Request

D, [2020-03-03T11:31:53.741764 #35263] DEBUG -- : upload binary ... finished
I, [2020-03-03T11:31:53.741921 #35263]  INFO -- : File uploaded. During: 15 seconds, Upload Speed: 9167 KB/s 
I, [2020-03-03T11:31:53.741977 #35263]  INFO -- : App id is 5deb4d79f945485ab84c027e
I, [2020-03-03T11:31:53.741998 #35263]  INFO -- : Release id is 5e5dcfa90d81cc0ba86ee478
I, [2020-03-03T11:31:53.742068 #35263]  INFO -- : Updating devices info......
I, [2020-03-03T11:31:54.069678 #35263]  INFO -- : Updating app info......
Restclient error, body = 
400 Bad Request
/Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
/Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
/Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:920:in `start'
/Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
/Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
/Library/Ruby/Gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
/Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:66:in `block in basic_request'
/Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `times'
/Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `basic_request'
/Library/Ruby/Gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:19:in `block (2 levels) in <module:DefaultRestModule>'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3.1/lib/fir/util/publish.rb:119:in `update_app_info'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3.1/lib/fir/util/publish.rb:83:in `upload_app'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3.1/lib/fir/util/publish.rb:15:in `publish'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3.1/lib/fir/cli.rb:138:in `publish'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3.1/lib/fir/cli.rb:185:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.3.1/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'

**Comment by GG526** [comment]
我这边也是这个报错 2.0.3.3

**Comment by GG526** [comment]
Traceback (most recent call last):
	44: from /Users/seven/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	43: from /Users/seven/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	42: from /Users/seven/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	41: from /Users/seven/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	40: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/bin/fastlane:23:in `<top (required)>'
	39: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	38: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	37: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	36: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	35: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	34: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	33: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	32: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	31: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	30: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	29: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	28: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	27: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	26: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	25: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	24: from Fastfile:165:in `block (2 levels) in parsing_binding'
	23: from Fastfile:172:in `fire'
	22: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	21: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	20: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	19: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	18: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	17: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	16: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-2.142.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	15: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fastlane-plugin-fir_cli-2.0.3.3/lib/fastlane/plugin/fir_cli/actions/fir_cli_action.rb:31:in `run'
	14: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fir-cli-2.0.3.2/lib/fir/util/publish.rb:15:in `publish'
	13: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fir-cli-2.0.3.2/lib/fir/util/publish.rb:84:in `upload_app'
	12: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/fir-cli-2.0.3.2/lib/fir/util/publish.rb:120:in `update_app_info'
	11: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:19:in `block (2 levels) in <module:DefaultRestModule>'
	10: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `basic_request'
	 9: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `times'
	 8: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:66:in `block in basic_request'
	 7: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	 6: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	 5: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	 4: from /Users/seven/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:910:in `start'
	 3: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
	 2: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
	 1: from /Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/Users/seven/.rvm/gems/ruby-2.5.1/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 400 Bad Request (RestClient::BadRequest)

**Comment by jicheng1014** [comment]
抱歉    是因为  我们的 cdn 暂时不支持patch 方法  麻烦升级至 2.0.4 即可

**Comment by fakepinge** [comment]
2.0.4 问题已解决
