### ISSUE TITLE
fir-cli 2.0.4上传报错：URL过滤。

### ISSUE THREAD

**Issue by samingzhong** [FIRHQ/fir-cli#272]
MacBook-Pro-Jenkins:$fir p ${uploadFilePath} -T ${firImAPIToken} --qrcode --no-open --password=${firImPassword} --changelog="test"
报错：
767: unexpected token at '<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>URL过滤</title>
<link href="../css/terminal.css" rel="stylesheet" type="text/css" />

</head>

<script language="JavaScript" type="text/JavaScript">

// Added by csz in [2011-9-13] for the customize for malaysia: access denied page should show ip addr information etc.
var strShow = "According to the access control policy, you are not allowed to access this website. If you have any doubt, please contact the network administrator.";

function defendXSSReplace(str){
	var s = "";
	if(str.length == 0) return "";
	s = str.replace(/&/g,"&amp;");
	s = s.replace(/</g,"&lt;");
	s = s.replace(/>/g,"&gt;");
	s = s.replace(/ /g,"&nbsp;");
	s = s.replace(/\'/g,"&#39;");
	s = s.replace(/\"/g,"&quot;");
	return s;
}

function getParamString(name)
{
    var strHref = window.location.href;
	var intPos = strHref.indexOf("?");
    if(-1 == intPos)
    {
        return '';
    }

	var strRight = strHref.substr(intPos + 1);  // get the parameter from url
	var parameters = strRight.split("&");

    var pos, paraName, paraValue;

	for(var i=0; i<parameters.length; i++)
    {
        // get psoition of equality operator
        pos = parameters[i].indexOf('=');
        if(pos == -1)
        {
            continue;
        }

        // get name and value from url
        paraName = parameters[i].substring(0, pos);
        paraValue = parameters[i].substring(pos + 1);

        // if name search hit, then return current value. And restore + operator to blank space
        if(paraName == name)
        {
            return defendXSSReplace(decodeURIComponent(paraValue.replace(/\+/g, " ")));
        }
    }

    return '';
}

function onInit()
{
    //var strIp   = getParamString("ip");
    var strType = getParamString("url_type");
    var strPlc  = getParamString("plc_name");

    if(strPlc.indexOf("#")>-1){
    	strPlc = strPlc.match(/(.*)#/)[1];
    }
    document.getElementById("strType").innerHTML = strType;
    document.getElementById("strPlc").innerHTML = strPlc;
}

</script>

<body onload="onInit()">
<div id="content">
  <h1 class="warning">访问被拒绝</h1>
  <div class="partition"> <span class="partition_left" style="width:220px;"></span> </div>
  <div name="ContentShow" id="ContentShow">
  	<p class='b_distance'>您尝试访问的网站类型属于[<font color=red id="strType"></font>]已经被上网策略[<font color=red id="strPlc"></font>]拒绝访问。如果有疑问，请联系网络管理员。</p>
</div>
</div>
</body>
</html>'
/Users/xufuhe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/xufuhe/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/multi_json-1.14.1/lib/multi_json/adapters/json_common.rb:14:in `load'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/multi_json-1.14.1/lib/multi_json/adapter.rb:21:in `load'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/multi_json-1.14.1/lib/multi_json.rb:122:in `load'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:67:in `block in basic_request'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `times'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `basic_request'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:10:in `block (2 levels) in <module:DefaultRestModule>'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.4/lib/fir/util.rb:36:in `fetch_user_info'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.4/lib/fir/util/publish.rb:227:in `initialize_publish_options'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.4/lib/fir/util/publish.rb:10:in `publish'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.4/lib/fir/cli.rb:138:in `publish'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.4/lib/fir/cli.rb:185:in `invoke_command'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Users/xufuhe/.rvm/gems/ruby-2.6.3/gems/fir-cli-2.0.4/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'
/usr/local/bin/ruby_executable_hooks:24:in `eval'
/usr/local/bin/ruby_executable_hooks:24:in `<main>'

**Comment by jicheng1014** [comment]
这个是因为  你们有深信服的 网上上网行为管理ac    这个设备对我们的域名 api.bq04.com 有误判, 所以这里比较尴尬

您可以先将 bq04.com 加入深信服 ac 的白名单, 临时解决下这个问题

我们已经联系了深信服, 他们的答复是 

"收到！已反馈！预计在3月17日左右的规则库更新，辛苦当时暂时需要使用的话先临时放通下，等规则库更新及时使用设备联网更新最新的规则库，有什么疑问您在及时反馈，感谢您的支持。
"

**Comment by jicheng1014** [comment]
另外 2.0.5 已经切到了另外一个域名
