### ISSUE TITLE
fir-cli 上传ipa报错

### ISSUE THREAD

**Issue by wjling** [FIRHQ/fir-cli#276]
报错信息：

E, [2020-03-18T13:45:58.678610 #88003] ERROR -- : upload icon error ! undefined method `body' for nil:NilClass

I, [2020-03-18T13:45:58.678679 #88003]  INFO -- : ignore icon upload error undefined method `body' for nil:NilClass

...

E, [2020-03-18T13:54:00.492601 #88003] ERROR -- : upload binary ... error ! undefined method `body' for nil:NilClass

E, [2020-03-18T13:54:00.492665 #88003] ERROR -- : binary upload to ali fail, undefined method `body' for nil:NilClass

想问问这个是怎么回事？fir-cli版本2.0.8

**Comment by jicheng1014** [comment]
说明没连到服务器上       
是不是您在terminal 翻墙了

或者您在jenkins 跑的  之后配置的有不正确?

**Comment by jicheng1014** [comment]
搞不定的话  可以加我微信  并下载好 teamviewer  我帮您远程调下

**Comment by wjling** [comment]
感谢，我先排查一下是不是网络问题。配置jenkins那台电脑并不是我在使用的电脑

**Comment by wjling** [comment]
跟翻墙没有什么关系，都是一样的报错。jenkins那台机ruby是用homebrew重新装的，然后用新的ruby装的fir-cli。不知道会不会有问题

**Comment by jicheng1014** [comment]
您把日志贴全我看看呗

**Comment by jicheng1014** [comment]
或者直接联系我微信也行

**Comment by wjling** [comment]
抱歉，回复晚了。能留个微信联系一下吗

**Comment by jicheng1014** [comment]
atpking

**Comment by jicheng1014** [comment]
我遇到了一个  类似案例的   
他的网络 是用了 代理   走了一圈地球
之后我们这个回调接口是  5秒超时
您看下是不是这个原因
如果是的话, 还请麻烦确保fir-cli 走国内线路  
或者稍微等下
我下个版本会增加回调的超时时间的设置方式

**Comment by jicheng1014** [comment]
客户反馈已经处理完毕
