### ISSUE TITLE
fir-cli上传InHouse打包的ipa，没有provisioning file的企业信息

### ISSUE THREAD

**Issue by everettjf** [FIRHQ/fir-cli#28]
再次感谢，修改了下面的问题。
https://github.com/FIRHQ/fir-cli/issues/26

但，fir-cli上传与web手动上传还有一点区别，没有显示provisioning file的企业信息。

<img width="728" alt="screenshot 2015-10-28 18 11 06" src="https://cloud.githubusercontent.com/assets/1665109/10785775/3bd1d2ce-7da1-11e5-9a9e-90f950a104b3.png">

不知道这样的区别有没有什么问题？

**Comment by NaixSpirit** [comment]
@everettjf 明白, cli 没有主动上传这个值, 待会就加上

**Comment by NaixSpirit** [comment]
@everettjf 1.3.4 版本已经好了:laughing:

**Comment by everettjf** [comment]
好迅速:+1:
