### ISSUE TITLE
Commands 提示在较窄窗口中显示不全

### ISSUE THREAD

**Issue by Cygra** [FIRHQ/fir-cli#280]
命令行中输入 `$ fir`，Commands 中的提示信息在较窄的窗口中显示不全，如图：

![391585810192_ pic](https://user-images.githubusercontent.com/34186314/78219132-82e1d500-74f1-11ea-894c-70ace26d1be4.jpg)
![401585810192_ pic](https://user-images.githubusercontent.com/34186314/78219141-85442f00-74f1-11ea-9ce6-5662d709c23c.jpg)

**Comment by jicheng1014** [comment]
额  这个  超出我能力范围了   fir-cli 是用的是 thor 作为命令行管理工具
