### ISSUE TITLE
我好像一直无法更新到最新版本，还停留在1.6.0....

### ISSUE THREAD

**Issue by sugerGDev** [FIRHQ/fir-cli#282]
如题，按照所说的已经试过
gem 最新
ruby 2.6.3
10.14.6

**Comment by sugerGDev** [comment]
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-rdoc

**Comment by sugerGDev** [comment]
是要更新ruby版本吗？

**Comment by jicheng1014** [comment]
今天 rubygems.org  好像出问题了

**Comment by jicheng1014** [comment]
具体  参见这个帖子 

https://ruby-china.org/topics/39726

**Comment by sugerGDev** [comment]
> 具体 参见这个帖子
> 
> https://ruby-china.org/topics/39726

已经可以正常更新了，thx
