### ISSUE TITLE
jenkins上传成功，但是shell却提示失败

### ISSUE THREAD

**Issue by SheepYang1993** [FIRHQ/fir-cli#285]
![image](https://user-images.githubusercontent.com/15150244/80664941-abe28f00-8aca-11ea-980e-d4e42b82ab19.png)

**Comment by jicheng1014** [comment]
老哥    fir publish  看您的结果是   返回了 0   应该是正常的  
你可以紧接那句话下面   echo $? 确认下 

感觉像是是其他地方引起的

**Comment by jicheng1014** [comment]
另外您日志可以放全一些   感觉像是最顶上引起的   但是是什么造成的  目前的信息量看不出来呢

**Comment by SheepYang1993** [comment]
找到原因了，是后面的shell代码导致的错误
