### ISSUE TITLE
jenkins 的fir.im插件问题

### ISSUE THREAD

**Issue by xavierXing** [FIRHQ/fir-cli#286]
环境：macbook pro 
系统：10.15.3
打包工具： jenkins
问题描述：
           打包上传fir.im成功之后，output log显示 you can use ENV var $FIR_DOWNLOAD_URL 但是这个变量是无效的，我在jenkins的发送的邮件内容中引用到了这个变量，但是发送的邮件不显示任何的路径，我的引用是这样 <a>${ENV, var="FIR_DOWNLOAD_URL"}<a/>。 期待你的帮助

**Comment by jicheng1014** [comment]
老哥  发下日志看看呗

**Comment by jicheng1014** [comment]
话说你用的是   jenkins 的  fir 插件么?  那个没维护了  推荐您使用  fir-cli

**Comment by hahaGitHub** [comment]
请问token如何找到呢
