### ISSUE TITLE
插件上传失败

### ISSUE THREAD

**Issue by mxpasser** [FIRHQ/fir-cli#287]
@jicheng1014 老哥，用的插件上传iPa，报了下面的错误，是啥原因哦~~~
found remote files : [LXxxx-IPA/xxx.ipa]
Deployment failed : null
Build step 'Upload to fir.im' marked build as failure
Finished: FAILURE

**Comment by jicheng1014** [comment]
你是说 jenkins的  fir插件么  

那个没维护了  建议您直接在 jenkins 里调用  fir-cli

**Comment by mxpasser** [comment]
@jicheng1014 嗯呢，是plugin 的插件 fir-plugin.hpi。。。后来更新了fir-cli，用命令行可以上传成功了！ 😄

**Comment by jicheng1014** [comment]
好的 ~
