### ISSUE TITLE
在Jenkins中刚开始执行就停了，也没有报错啥的，麻烦帮忙看看

### ISSUE THREAD

**Issue by fengxiaolei** [FIRHQ/fir-cli#288]
![image](https://user-images.githubusercontent.com/8679403/82171136-05372480-98f9-11ea-8654-cdb287261244.png)
在命令窗口里面是没有问题，放到Jenkins 里面就不行了，也按照文档添加了一些参考信息。还是不成功！ 麻烦帮忙看看，是不是其他地方还有问题

**Comment by jicheng1014** [comment]
我猜是中文问题?

**Comment by fengxiaolei** [comment]
> 我猜是中文问题?

中文如果有问题，感觉在命令窗口也不会成功！ 我先试试看。

**Comment by fengxiaolei** [comment]
还有一个疑问就是我上传上去之后，图标是这个样子的
![image](https://user-images.githubusercontent.com/8679403/82181100-746e4200-9914-11ea-8f86-cb1ad73d5b7f.png)
问下这个是在哪里可以更换？

**Comment by jicheng1014** [comment]
我的意思是   ipa 的文件名称 修改成英文试试?   

图标  的问题 可以参见这里



https://github.com/FIRHQ/fir-cli/issues/279

fir-cli 支持独立指定 icon 文件  --specify_icon_file_path   后面接一个 png 文件即可

**Comment by fengxiaolei** [comment]
是中文得问题，已解决。多谢！ 提前给ipa做了重命名发现可以了。
