### ISSUE TITLE
上传apk成功啦,但是任务失败; 

### ISSUE THREAD

**Issue by yangyu92** [FIRHQ/fir-cli#289]
fir-cli版本也升级到2.0.9啦,
看升级日志,这个错误在2.0.4解决的,现在不知道什么原因;错误日志如下:
Release id is 5ec7a893b2eb467e1623c80a
I, [2020-05-22T18:25:23.771411 #51927]  INFO -- : Updating app info......
Restclient error, body = {"errors":{"exception":[{"short":["Short is already taken"]}]},"code":100108}
400 Bad Request
Build step 'Execute shell' marked build as failure

**Comment by jicheng1014** [comment]
short 被占用
