### ISSUE TITLE
fir-cli更新到2.0.9以后，二维码扫描安卓下载的包名，不是打包出来的，而是随机名字

### ISSUE THREAD

**Issue by TesterQiao** [FIRHQ/fir-cli#293]
fir-cli更新到2.0.9以后，安卓下载包名不是打包出来的，而是随机名字
例如395afaa5197a1749a2cc9d12492880b534bf3bf1.apk
打包出来是Wod.apk

**Comment by jicheng1014** [comment]
是的  这个是因为部分cdn服务器不支持设置 名称   而是一个 sha值    部分cdn 支持  看账户分配了

**Comment by TesterQiao** [comment]
好的，了解。
