### ISSUE TITLE
添加了钉钉机器人报错

### ISSUE THREAD

**Issue by huxq-coder** [FIRHQ/fir-cli#295]
# 多个参数 可以使用逗号(, )分离   
    fir_cli(
	api_token: "7bba36f810fe58ea7b135a0aa6b95496",  
	changelog: "测试版本提交",
	dingtalk-access-token: "****",
	dingtalk-custom-message: "***",  
	dingtalk-at-phones: "***"
	)
配置如上

报错如下“

[!] Syntax error in your Fastfile on line 28: Fastfile:28: syntax error, unexpected ':', expecting =>
	dingtalk-access-token: "***...
	                     ^
Fastfile:28: syntax error, unexpected ',', expecting end
...***",
...                              ^
Fastfile:29: syntax error, unexpected ':', expecting end
	dingtalk-custom-message: "**...
	                       ^
Fastfile:29: syntax error, unexpected ',', expecting end-of-input
... ***",  
...                              ^

**Comment by jicheng1014** [comment]
下划线

**Comment by jicheng1014** [comment]
dingtalk_access_token  类似这样   

这个是用的  https://github.com/FIRHQ/fastlane-plugin-fir_cli  吧?

**Comment by huxq-coder** [comment]
👌，已解决，非常感谢。
