### ISSUE TITLE
can't upload apk, i don't know why

### ISSUE THREAD

**Issue by meskgron** [FIRHQ/fir-cli#296]
I, [2020-08-18T17:06:18.491920 #360783]  INFO -- : begin to upload ...
D, [2020-08-18T17:06:18.491978 #360783] DEBUG -- : begin to upload icon
D, [2020-08-18T17:06:18.492098 #360783] DEBUG -- : icon_url = https://fir-app-icon.oss-cn-beijing.aliyuncs.com/0d1868a7f5a300a60f7ccbc19df03b472e972513, icon_info = #<File:0x000056467075fd98>
D, [2020-08-18T17:06:24.492128 #360783] DEBUG -- : begin to callback api
D, [2020-08-18T17:06:25.793029 #360783] DEBUG -- : callback api finished
D, [2020-08-18T17:06:25.793161 #360783] DEBUG -- : upload icon finished
D, [2020-08-18T17:06:25.793219 #360783] DEBUG -- : begin to upload binary ...
D, [2020-08-18T17:06:25.793339 #360783] DEBUG -- : binary_url = https://fir-app-binary.oss-cn-beijing.aliyuncs.com/e6a81d8fd1698b87befa68c4ac169ced15a894ce.apk, binary_info = #<File:0x0000564670736150>
D, [2020-08-18T17:06:25.793410 #360783] DEBUG -- : {"CONTENT-DISPOSITION"=>"attachment; filename* = UTF-8''app-dev-debug.apk", "Content-Type"=>"application/vnd.android.package-archive", "date"=>"Tue, 18 Aug 2020 09:06:18 GMT", "x-oss-date"=>"Tue, 18 Aug 2020 09:06:18 GMT", "authorization"=>"OSS LTAIH45wjMAbqQjW:AVqejiMa/pYyrxJ5Yt2LDCV+vSk="}
E, [2020-08-18T17:14:29.221601 #360783] ERROR -- : upload binary ... error ! Server broke connection
E, [2020-08-18T17:14:29.221715 #360783] ERROR -- : binary upload to ali fail, Server broke connection

**Comment by meskgron** [comment]
fir --version
✈ fir-cli 2.0.9

fir  p   "./app/build/outputs/apk/dev/debug/app-dev-debug.apk" -T 6f59b00XXXXXX

**Comment by jicheng1014** [comment]
add  `--oversea_turbo`  if fir-cli runs oversea (not in China)

`fir p ./app/build/outputs/apk/dev/debug/app-dev-debug.apk -T 6f59b00XXXXXX  --oversea_turbo`

**Comment by jicheng1014** [comment]
so? @meskgron
