### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by DDfans** [FIRHQ/fir-cli#299]
I, [2020-09-08T19:39:56.540778 #98528]  INFO -- : Fetching c@fir.im uploading info......
I, [2020-09-08T19:39:56.540861 #98528]  INFO -- : Uploading app: xxx
I, [2020-09-08T19:39:57.422988 #98528]  INFO -- : Publishing app via .......
I, [2020-09-08T19:39:57.423302 #98528]  INFO -- : ✈ -------------------------------------------- ✈
I, [2020-09-08T19:39:57.423331 #98528]  INFO -- : begin to upload ...
I, [2020-09-08T19:39:57.423388 #98528]  INFO -- : skip update icon...
D, [2020-09-08T19:39:57.423421 #98528] DEBUG -- : begin to upload binary ...
D, [2020-09-08T19:39:57.423661 #98528] DEBUG -- : binary_url = https://fir-app-binary.oss-cn-beijing.aliyuncs.com/bc916e92e798ebabe1ebcac629d634fa7f54b838, binary_info = #<File:0x00007fd953d0b7e8>
D, [2020-09-08T19:39:57.423714 #98528] DEBUG -- : {"CONTENT-DISPOSITION"=>"attachment; filename* = UTF-8''LP-20200908193216-new.ipa", "Content-Type"=>"application/octet-stream", "date"=>"Tue, 08 Sep 2020 11:39:57 GMT", "x-oss-date"=>"Tue, 08 Sep 2020 11:39:57 GMT", "authorization"=>"OSS LTAIH45wjMAbqQjW:Ay7FAMm4KhJV6vxJ2j5I7qADSHc="}
E, [2020-09-08T19:41:14.272924 #98528] ERROR -- : upload binary ... error ! Connection reset by peer - SSL_connect
E, [2020-09-08T19:41:14.273021 #98528] ERROR -- : binary upload to ali fail, Connection reset by peer - SSL_connect

fir publish LP-20200908193216-new.ipa --skip-update-icon -T xxx

直接在命令行上传时候基本不会失败，但是写在shell脚本里执行会经常失败

**Comment by jicheng1014** [comment]
我猜     你执行shell 脚本的地方是海外？   海外可以用海外加速参数
