### ISSUE TITLE
方便加个参数，能够指定生成ipa的名称吗？

### ISSUE THREAD

**Issue by guoxj** [FIRHQ/fir-cli#30]
因为我们项目的每一次build都会让buildversion自增一。这样每一次生成的ipa文件名都不一定，上传的时候就比较麻烦。最好能够自己指定ipa文件名
谢谢

**Comment by NaixSpirit** [comment]
@guoxj 好的, 下个版本我加上了通知你

**Comment by NaixSpirit** [comment]
@guoxj 请安装 1.3.6 版本, 在 build_ipa 的命令中加了 -n 参数

**Comment by guoxj** [comment]
@NaixSpirit  谢谢！
