### ISSUE TITLE
feishu_custom_message是否支持飞书发送富文本消息？

### ISSUE THREAD

**Issue by JingFengJi** [FIRHQ/fir-cli#300]
你好，我想通过feishu_custom_message 发送 二维码到飞书群聊，我看到飞书机器人应该支持发送富文本消息，不知道该如何实现呢？

飞书的发送富文本消息文档
https://open.feishu.cn/document/ukTMukTMukTM/uMDMxEjLzATMx4yMwETM

**Comment by jicheng1014** [comment]
hello   看了下  飞书有个上传图片的接口  我去实现下    下个版本应该ok

**Comment by JingFengJi** [comment]
> hello 看了下 飞书有个上传图片的接口 我去实现下 下个版本应该ok

感谢，期待您下个版本的支持

**Comment by jicheng1014** [comment]
已更新
