### ISSUE TITLE
请问400错误是因为什么原因

### ISSUE THREAD

**Issue by LYluyu** [FIRHQ/fir-cli#301]
如题，命令如下
`release_id  = sh("fir publish -s #{ENV["FIRLINK"]} #{output_path} | grep -i 'Release id is ' | grep -o -E '[a-z0-9]{16,}'")`
<img width="1313" alt="WX20201030-185540@2x" src="https://user-images.githubusercontent.com/16254669/97697999-cb428f00-1ae2-11eb-98cc-c0edc276ebb2.png">

**Comment by jicheng1014** [comment]
看下  app 是不是被禁封了

**Comment by LYluyu** [comment]
并没有被禁封，查看fir的后台，上传成功了，但是控制台出现了这个错误

**Comment by LYluyu** [comment]
已修改，是我的short与需要上传的包不一致导致的

**Comment by LYluyu** [comment]
short问题，.env定义的short和fir上的不一致导致，谢谢回答

**Comment by jicheng1014** [comment]
ok   下个版本处理报错问题  😆
