### ISSUE TITLE
中文changelog 提交不了

### ISSUE THREAD

**Issue by lixiuwen** [FIRHQ/fir-cli#304]
fir publish debug.apk -c “中文说明”
提交后界面上没有日志

**Comment by jicheng1014** [comment]
我感觉是你的bash 的设置问题， 你可以曲线救国一下

可以将日志先输出成一个文本, 之后 --changelog=这个本文 即可实现changlog换行

**Comment by lixiuwen** [comment]
已经解决了，是升级了glibc ,导致系统编码问题，已经解决

**Comment by yyx230** [comment]
> 已经解决了，是升级了glibc ,导致系统编码问题，已经解决

我也遇到这种问题，请问是如何解决的呢？
