### ISSUE TITLE
无法安装fir-cli

### ISSUE THREAD

**Issue by zy654781296** [FIRHQ/fir-cli#305]
Mac OS 11.1
gem 版本 3.0.3
ruby 2.6.3p62

gem install fir-cli  报错
Building native extensions. This could take a while...
ERROR:  Error installing fir-cli:
        ERROR: Failed to build gem native extension.

![image](https://user-images.githubusercontent.com/4401199/102452079-b0b57c80-4074-11eb-8084-dbe43b3a6a01.png)

**Comment by zy654781296** [comment]
Building native extensions. This could take a while...
ERROR:  Error installing fir-cli:
        ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/unf_ext-0.0.7.7/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20201217-12075-15ck6n6.rb extconf.rb
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
        --with-static-libstdc++
        --without-static-libstdc++
        --with-stdc++lib
        --without-stdc++lib
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:789:in `try_func'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

**Comment by jicheng1014** [comment]
推荐使用 rvm 安装 ruby 环境会好一点， 不依赖sudo 写 bin目录

可以参考  https://ruby-china.org/wiki/rvm-guide   安装 2.4 以上的ruby 版本均可



如果必须用原生， 可以参考下面的指令
sudo xcodebuild -license
brew install ruby  
brew install coreutils

gem install fir-cli 


其实这个报错是因为 unf_ext 没装上， 原因是缺失一些组件

**Comment by foobra** [comment]
> 推荐使用 rvm 安装 ruby 环境会好一点， 不依赖sudo 写 bin目录
> 
> 可以参考 https://ruby-china.org/wiki/rvm-guide 安装 2.4 以上的ruby 版本均可
> 
> 如果必须用原生， 可以参考下面的指令
> xcode-select --install
> sudo xcodebuild -license
> brew install ruby
> brew install coreutils
> 
> gem install fir-cli
> 
> 其实这个报错是因为 unf_ext 没装上， 原因是缺失一些组件

brew install ruby 现在会安装 ruby3, 会导致执行失败
