### ISSUE TITLE
提交的更新日志中有换行的话，更新日志内容会被截断

### ISSUE THREAD

**Issue by williamliuok** [FIRHQ/fir-cli#306]
通过命令行方式执行的参数内容貌似不能含有换行符，即使包含在字符串中，终端执行程序还是会读取到并截断后面的参数内容。

**Comment by williamliuok** [comment]
比如：
我的日志内容是这样的
![image](https://user-images.githubusercontent.com/19565360/103134213-b6e9cf80-46ea-11eb-8c7c-95f54e1cc575.png)
但是上传后的日志内容却是这样的
![image](https://user-images.githubusercontent.com/19565360/103134236-e0a2f680-46ea-11eb-91bf-f05e2341e19c.png)

**Comment by zzzwgg** [comment]
可以将日志先输出成一个文本, 之后 --changelog=这个本文

**Comment by zj974** [comment]
可以将日志先输出成一个文本, 之后 --changelog=这个本文

**Comment by jicheng1014** [comment]
是的，   您可以先将日志输出成一个  txt 文本  之后   --changlog 填写这个文本的路径即可

**Comment by williamliuok** [comment]
的确如此，原来还支持这样操作，明白了
