### ISSUE TITLE
gradle脚本上传报错，命令行执行却没问题

### ISSUE THREAD

**Issue by williamliuok** [FIRHQ/fir-cli#308]
I, [2020-12-30T10:05:06.433497 #27296]  INFO -- : ✈ -------------------------------------------- ✈
I, [2020-12-30T10:05:06.433690 #27296]  INFO -- : begin to upload ...
I, [2020-12-30T10:05:06.433922 #27296]  INFO -- : skip update icon...
D, [2020-12-30T10:05:06.434137 #27296] DEBUG -- : begin to upload binary ...
D, [2020-12-30T10:05:06.434435 #27296] DEBUG -- : binary_url = https://fir-app-binary.oss-cn-beijing.aliyuncs.com/c0f7e91b0dbe688748a42da9dc5a45605ed4676e.apk, binary_info = #<File:0x00000000133fde60>
D, [2020-12-30T10:05:06.434617 #27296] DEBUG -- : {"CONTENT-DISPOSITION"=>"attachment; filename* = UTF-8''Zfb_v3.0.0.12_debug.apk", "Content-Type"=>"application/vnd.android.package-archive", "date"=>"Wed, 30 Dec 2020 02:05:08 GMT", "x-oss-date"=>"Wed, 30 Dec 2020 02:05:08 GMT", "authorization"=>"OSS LTAIH45wjMAbqQjW:Hjln/MvLOChVUfDfSf+MK4i2vBw="}
D, [2020-12-30T10:08:23.128395 #27296] DEBUG -- : begin to callback api
E, [2020-12-30T10:08:23.128692 #27296] ERROR -- : upload binary ... error ! "\x9E" followed by "," on GBK
E, [2020-12-30T10:08:23.128905 #27296] ERROR -- : binary upload to ali fail, "\x9E" followed by "," on GBK

**Comment by jicheng1014** [comment]
我感觉像是您gradle 里调用的  fir-cli ?   能确定下版本么
