### ISSUE TITLE
命令行可以在上传后发送dingding消息，jenkins可以上传成功，但是没有dingding消息

### ISSUE THREAD

**Issue by zhaojianfei686** [FIRHQ/fir-cli#309]
反复试验了几次，找不到原因。

**Comment by jicheng1014** [comment]
我猜测  

你没设置关键字       建议在钉钉机器人上加上你app 的name 作为关键字

**Comment by jicheng1014** [comment]
经过跟用户沟通  发现是用户在jenkins 中的路径含有中文， 导致了  jenkins 没能正确的识别 后面的参数   将地址换为纯英文后  故障消失。
