### ISSUE TITLE
钉钉通知二维码不显示了

### ISSUE THREAD

**Issue by weinierfei** [FIRHQ/fir-cli#310]
1.29号钉钉的接口好像有变更，发到钉钉群机器人消息，二维码没有了

**Comment by jicheng1014** [comment]
好的  抽时间我去研究下  钉钉这个变化的接口。。。

**Comment by jicheng1014** [comment]
新版本已支持

**Comment by weinierfei** [comment]
升级到2.0.12后还是不行呢，依旧没有二维码。需要改命令行参数之类的吗？我还是原来的命令，没有改动。

**Comment by jicheng1014** [comment]
> 升级到2.0.12后还是不行呢，依旧没有二维码。需要改命令行参数之类的吗？我还是原来的命令，没有改动。

不需要任何改动呀   请在日志中看下 最上面有 fir 的版本输出   您确认下版本

![image](https://user-images.githubusercontent.com/1264913/108490511-c85fea00-72dd-11eb-909e-a804362825fc.png)

**Comment by jicheng1014** [comment]
![image](https://user-images.githubusercontent.com/1264913/108490646-ec233000-72dd-11eb-8403-e1ac9e4fde83.png)

**Comment by weinierfei** [comment]
版本是没问题的,
1、fir -v出来的就是2.0.12
<img width="412" alt="111" src="https://user-images.githubusercontent.com/11873816/108577058-a9536d80-735a-11eb-87cc-035755b99ef1.png">

2、我的日志里头没看到版本信息:
<img width="599" alt="000000000" src="https://user-images.githubusercontent.com/11873816/108576892-2cc08f00-735a-11eb-8cb1-26c60974cf97.png">

3、mac版本的钉钉没显示二维码
<img width="465" alt="11111" src="https://user-images.githubusercontent.com/11873816/108576759-bde33600-7359-11eb-9d7f-c114352e349f.png">

4、安卓版钉钉上是有二维码的
![WechatIMG134](https://user-images.githubusercontent.com/11873816/108576839-ff73e100-7359-11eb-9805-1c6a4b291cd6.jpeg)

**Comment by weinierfei** [comment]
上传命令
`xx.apk -exec fir publish -R -T xxxx -c "当前环境：$curEnv" -D xxxxxxxx --dingtalk_custom_message="当前环境为：$curEnv  当前分支为：$SELECT_BRANCH" {} \;`

**Comment by jicheng1014** [comment]
是不是钉钉的问题？

我这个就是 mac 版本的钉钉

**Comment by jicheng1014** [comment]
我知道问题了， 您这个 jenkins 里的  fir  和 命令行里的 fir 不是一个版本   

您可以在 jenkins 的 指令前面加入  fir -v 跑一遍看下输出  

gem update fir-cli 可以升级  

jenkins 下运行 fir-cli 具体可参见这篇文章

http://blog.betaqr.com/use-fir-cli-in-jenkins/

**Comment by weinierfei** [comment]
感谢，可以了。我这个job挂在了另外一台物理机上，昨天升级的时候，只升级了主Jenkins，忘记升级另外一台了。抱歉，添麻烦了！
