### ISSUE TITLE
上传后webhook飞书

### ISSUE THREAD

**Issue by beatman423** [FIRHQ/fir-cli#313]
fir publish xxx.ipa -D --feishu-access-token=feishu_token -T fir_token

publish成功 但飞书群无响应 语法问题吗?

**Comment by jicheng1014** [comment]
刚试了下  能收到   
![image](https://user-images.githubusercontent.com/1264913/115644722-a1f81280-a351-11eb-8e30-8b9bd3ce0573.png)

![image](https://user-images.githubusercontent.com/1264913/115644662-87259e00-a351-11eb-8add-5d881e2630e1.png)

我注意到飞书好像增加了  对 webhook 的校验   不知道您是不是设置了那个引起的问题

**Comment by beatman423** [comment]
curl -X POST试了一下请求成功但是机器人也没响应  应该是我们的飞书是定制版本的问题 webhook用到的url域名是定制的需要内网验证

**Comment by beatman423** [comment]
可以close了 打扰了 =.=

**Comment by jicheng1014** [comment]
飞书还有定制版。。。

**Comment by beatman423** [comment]
嗯 有的  webhook的域名不是open.feishu.cn的
