### ISSUE TITLE
jenkins 通过fir-cli 上传应用时有如下报错，上传成功后应用名称显示乱码

### ISSUE THREAD

**Issue by guanyongbo** [FIRHQ/fir-cli#314]
![image](https://user-images.githubusercontent.com/19591374/116333703-80da6a80-a806-11eb-942c-9d6da107a91c.png)
![image](https://user-images.githubusercontent.com/19591374/116333753-951e6780-a806-11eb-9ec1-e93c21f136cb.png)

**Comment by jicheng1014** [comment]
哦?  感觉像是bash 的编码问题
