### ISSUE TITLE
fir me

### ISSUE THREAD

**Issue by nobut** [FIRHQ/fir-cli#316]
.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb .rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:99:in `find' .rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-4.0.0/lib/psych/class_loader.rb:28:in `load'

**Comment by jicheng1014** [comment]
根据跟用户的交流  目前发现是  用户的  psych 4.0 似乎有问题, 降到3.x 之后就可以了

之后开发者这边的机器包括开了几台不同操作系统的ecs, 安装 4.0 版本都未复现这个问题 

so,暂时归类于  psych 的环境问题     如遇到这个问题, 手动降级下 psych 版本即可
