### ISSUE TITLE
飞书的通知样式不想吐槽

### ISSUE THREAD

**Issue by lionnner** [FIRHQ/fir-cli#318]
1.发的通知区分不出iOS还是Android
2.添加了--feishu-access-token 后，至少20%的概率会失败，仅仅是通知失败，但是导致了我们的命令行被中断。

**Comment by jicheng1014** [comment]
1. 下个版本修复修正这个问题
2. 比较好奇你失败在哪一步   麻烦贴下错误日志

至于样式类型的, 欢迎 PR 建议

**Comment by lionnner** [comment]
> 1. 确实没注意, 下个版本会增加
> 2. 麻烦贴下错误日志, 另外还请说明下你们网络环境. 刚我在北京联通的环境下手动测试了20次, 好像都成功了.
> 
> 至于样式类型, 欢迎 PR
> 
> 最后, fir-cli 代码其实不复杂, feishu 的主要逻辑在 feishu_helper 里, 您要是着急用, 欢迎 fork 后修改下, fir-cli 是遵循 MIT 协议的软件, 是鼓励大家 fork, PR 的.

log没有了,上海电信，近期也没遇到过了。

**Comment by jicheng1014** [comment]
ps  已经发布新版本, 添加了 type 类型
