### ISSUE TITLE
没有生成dsym文件

### ISSUE THREAD

**Issue by hydyy** [FIRHQ/fir-cli#32]
fir build_ipa ~/
xx/xx/xx -w -S xx

为什么呢？

**Comment by hydyy** [comment]
而且生成的ipa会比我用xcode打包出来的ipa大好几兆~~~

**Comment by NaixSpirit** [comment]
@hydyy 升级最新的 fir-cli 试试, 最新版本我更新了打包的方式

**Comment by hydyy** [comment]
@NaixSpirit  我已经升级到最新版本了 确实不行 。。。。

**Comment by NaixSpirit** [comment]
@hydyy 把详细的 build 命令, 发给我邮件吧, hxy@fir.im

**Comment by hydyy** [comment]
@NaixSpirit  发过去了

**Comment by sunbohong** [comment]
@NaixSpirit  自定义 DWARF_DSYM_FOLDER_PATH 时，无法生成 dsym 文件。

`fir build_ipa -w -S zgzzzs -p -T *** -M true -P ***`

**Comment by NaixSpirit** [comment]
@sunbohong 
```sh
DEBUG=1 fir build_ipa -w -S zgzzzs -p -T *** -M true -P ***
```
可以打出 fir-cli 使用的 xcodebuild 命令

**Comment by sunbohong** [comment]
@NaixSpirit  已经解决了。

**Comment by sunbohong** [comment]
@NaixSpirit  刚看见这个命令，我先测试一下
