### ISSUE TITLE
fir publish上传apk包报错。

### ISSUE THREAD

**Issue by shihuadc** [FIRHQ/fir-cli#320]
D, [2021-06-24T17:09:29.909498 #28033] DEBUG -- : {"CONTENT-DISPOSITION"=>"attachment; filename* = UTF-8''app-release.apk", "Content-Type"=>"application/vnd.android.package-archive", "date"=>"Thu, 24 Jun 2021 09:07:14 GMT", "x-oss-date"=>"Thu, 24 Jun 2021 09:07:14 GMT", "authorization"=>"OSS LTAIH45wjMAbqQjW:M0sNwtNmvJ+7CUEHSF522+83lEw="}
E, [2021-06-24T17:25:40.180235 #28033] ERROR -- : upload binary ... error ! 403 Forbidden
E, [2021-06-24T17:25:40.180304 #28033] ERROR -- : binary upload to ali fail, 403 Forbidden

**Comment by jicheng1014** [comment]
hello  是我们沟通过么?    就是因为网络原因?

**Comment by shihuadc** [comment]
嗯嗯，是出口带宽太小导致的。
