### ISSUE TITLE
skype能否使用Webhook

### ISSUE THREAD

**Issue by maybeliu** [FIRHQ/fir-cli#326]
你好，我上传成功之后消息能否回调到skype

**Comment by jicheng1014** [comment]
这个    似乎不行  没研究过 skype   我盲猜 skype 可以接受邮件    之后你可以将升级邮件转发到 skype 邮箱（如果有的话）

**Comment by maybeliu** [comment]
> Contributor

应该是，我也查过了，确实不行，可能企业版的可以，类似企业微信
