### ISSUE TITLE
fir publish -D ***不触发钉钉机器人的群消息发送。 机器人关键词已经和应用名称保持一致

### ISSUE THREAD

**Issue by AndroidLMY** [FIRHQ/fir-cli#328]
fir publish -D ***不触发钉钉机器人的群消息发送。 机器人关键词已经和应用名称保持一致

**Comment by jicheng1014** [comment]
版本号是？

**Comment by jicheng1014** [comment]
老哥  我刚试了下  我这 ok

你可以先加下 --dingtalk-custom-message=你的关键词   试试


或者直接使用加签模式  --dingtalk-secret

**Comment by AndroidLMY** [comment]
我的命令如下
find ${WORKSPACE}/app/build/outputs/apk/matrix32/debug -name "*.apk" -exec fir publish -c 7777 -D token*** --dingtalk_custom_message="乡遇" -T token** {} \;
机器人的配置如下 还是无法收到消息。  但是apk确实上传成功了
![image](https://user-images.githubusercontent.com/32607888/160082198-65cfcf59-78ed-46c3-a9d3-dfe8139bc8ad.png)

**Comment by AndroidLMY** [comment]
老哥你看下github

发自我的iPhone

**Comment by jicheng1014** [comment]
你先试试   单个 关键词  就只在 dingtalk 的 robot 里设置   为 乡遇       之后 --dingtalk_custom_message=乡遇

**Comment by AndroidLMY** [comment]
好的这个dingtalk_custom_message还是dingtalk-custom-message。下划线_和-有差没。到底用哪个

**Comment by AndroidLMY** [comment]
试过了还是没有消息收到
另外执行完毕后日志如图
Permission denied @ rb_sysopen - /.fir-cli-app
跟这个有关系吗  包每次都可以传到fir

![image](https://user-images.githubusercontent.com/32607888/160084198-197f6c5f-95e6-433d-91ec-e541f4b034c6.png)

**Comment by AndroidLMY** [comment]
在这里配置相同的机器人webhok地址
![image](https://user-images.githubusercontent.com/32607888/160086190-c6515eb0-6f85-46e0-9f10-552a36b78432.png)
就可以收到消息
![image](https://user-images.githubusercontent.com/32607888/160086249-2bc52ee4-7b3c-415f-a323-e71c02692b36.png)
说明token没啥问题啊

**Comment by AndroidLMY** [comment]
以下是我的shell脚本
#!/bin/bash --login
source /etc/profile
JENKINS_PROJECT_NAME=NewDemo
WORKSPACE=/home/www/.jenkins/workspace/${JENKINS_PROJECT_NAME}
find ${WORKSPACE}/app/build/outputs/apk/matrix32/debug -name "*.apk" -exec fir publish -c 7777 -D 8d** --dingtalk-custom-message=乡遇哈哈哈哈哈哈 -T f2** {} \;
下面是执行结果
[NewDemo] $ /bin/bash --login /www/server/tomcat/temp/jenkins687805372698397320.sh
undefined method `response' for #<Errno::EACCES: Permission denied @ rb_sysopen - /.fir-cli-app>
Did you mean?  respond_to?
/usr/local/rvm/gems/ruby-2.6.2/gems/fir-cli-2.0.14/lib/fir/util/publish.rb:99:in `rescue in upload_app'
/usr/local/rvm/gems/ruby-2.6.2/gems/fir-cli-2.0.14/lib/fir/util/publish.rb:70:in `upload_app'
/usr/local/rvm/gems/ruby-2.6.2/gems/fir-cli-2.0.14/lib/fir/util/publish.rb:20:in `publish'
/usr/local/rvm/gems/ruby-2.6.2/gems/fir-cli-2.0.14/lib/fir/cli.rb:147:in `publish'
/usr/local/rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.6.2/gems/fir-cli-2.0.14/lib/fir/cli.rb:194:in `invoke_command'
/usr/local/rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/usr/local/rvm/gems/ruby-2.6.2/gems/fir-cli-2.0.14/bin/fir:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.2/bin/fir:23:in `load'
/usr/local/rvm/gems/ruby-2.6.2/bin/fir:23:in `<main>'
/usr/local/rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'
I, [2022-03-25T16:59:40.009405 #2882276]  INFO -- : Fetching com.shouxiu.tcjy@fir.im uploading info......
I, [2022-03-25T16:59:40.009476 #2882276]  INFO -- : Uploading app: 乡遇-2.1.0-debug(Build 100430)
I, [2022-03-25T16:59:40.129188 #2882276]  INFO -- : Publishing app via kewei.songkw<kewei.songkw@shangnide.com>.......
I, [2022-03-25T16:59:40.129243 #2882276]  INFO -- : ✈ -------------------------------------------- ✈
I, [2022-03-25T16:59:40.129282 #2882276]  INFO -- : begin to upload ...
I, [2022-03-25T16:59:40.129304 #2882276]  INFO -- : fir-cli version 2.0.14 (2.6.2 @ x86_64-linux)
D, [2022-03-25T16:59:40.129338 #2882276] DEBUG -- : begin to upload icon
D, [2022-03-25T16:59:40.129408 #2882276] DEBUG -- : icon_url = https://fir-app-icon.oss-cn-beijing.aliyuncs.com/10463b899eba073548d62b3b3e7eeb797e696a45, icon_info = #<File:0x000000000e2c4260>
D, [2022-03-25T16:59:40.479486 #2882276] DEBUG -- : begin to callback api
D, [2022-03-25T16:59:40.595067 #2882276] DEBUG -- : callback api finished
D, [2022-03-25T16:59:40.595128 #2882276] DEBUG -- : upload icon finished
D, [2022-03-25T16:59:40.595142 #2882276] DEBUG -- : begin to upload binary ...
D, [2022-03-25T16:59:40.595185 #2882276] DEBUG -- : binary_url = https://fir-app-binary.oss-cn-beijing.aliyuncs.com/1f12174339c6af161cf3f06691276b583b0f6bcc.apk, binary_info = #<File:0x000000000e3a32a8>
D, [2022-03-25T16:59:40.595198 #2882276] DEBUG -- : {"CONTENT-DISPOSITION"=>"attachment; filename* = UTF-8''tcjy_xy-2.1.0-debug-matrix32.apk", "Content-Type"=>"application/vnd.android.package-archive", "date"=>"Fri, 25 Mar 2022 08:59:40 GMT", "x-oss-date"=>"Fri, 25 Mar 2022 08:59:40 GMT", "authorization"=>"OSS LTAIH45wjMAbqQjW:k1KXe/FwWfuI6FQHyHOTt5KcXhQ="}
D, [2022-03-25T17:01:19.216662 #2882276] DEBUG -- : begin to callback api
D, [2022-03-25T17:01:19.943897 #2882276] DEBUG -- : callback api finished
D, [2022-03-25T17:01:19.943964 #2882276] DEBUG -- : upload binary ... finished
I, [2022-03-25T17:01:19.944009 #2882276]  INFO -- : File uploaded. During: 99 seconds, Upload Speed: 683 KB/s 
I, [2022-03-25T17:01:19.944020 #2882276]  INFO -- : App id is 60e69e130d81cc219414dd53
I, [2022-03-25T17:01:19.944029 #2882276]  INFO -- : Release id is 623d84df23389f12a4908003
I, [2022-03-25T17:01:19.944099 #2882276]  INFO -- : Fetch app info from fir.im
Permission denied @ rb_sysopen - /.fir-cli-app
Finished: SUCCESS

**Comment by AndroidLMY** [comment]
我试着在命令行中执行相同的命令 命令行中的指令正常触发了钉钉消息发送

**Comment by jicheng1014** [comment]
额是否是因为脚本的中文问题？

**Comment by AndroidLMY** [comment]
我脚本里也没啥中文啊。只有--dingtalk-custom-message=乡遇哈哈哈哈哈哈 这里有中文。 相同的命令我在centos的终端里执行是能够触发群消息的。  undefined method response' for #<Errno::EACCES: Permission denied @ rb_sysopen - /.fir-cli-app> Did you mean? respond_to? /usr/local/rvm/gems/ruby-2.6.2/gems/fir-cli-2.0.14/lib/fir/util/publish.rb:99:in rescue in upload_app'   是因为这个引起的吗

**Comment by jicheng1014** [comment]
主要是你说相同的内容在终端里执行没问题  

所以我猜测是不是中文引起的    要不你先试试 用鉴权的方式 来发送钉钉的机器人？

**Comment by AndroidLMY** [comment]
好的 我先试试

发自我的iPhone

**Comment by AndroidLMY** [comment]
2.0.14

发自我的iPhone
