### ISSUE TITLE
fir-cli 上传apk时成功，但上传之后，app 的图标变成了默认的图标，不是应用自己的图标

### ISSUE THREAD

**Issue by htoooth** [FIRHQ/fir-cli#33]
我是在win7下，使用 ruby版本： 2.1.5p273，fir-cli  上传之后，应用的图标变成了默认的。
但是使用网站上传，应用的图标就是app 自己的图标。

**Comment by NaixSpirit** [comment]
使用 fir-cli 的版本是?

**Comment by htoooth** [comment]
@NaixSpirit 我的版本是`fir-cli 1.3.7`

**Comment by 13666012878** [comment]
谢谢

**Comment by NaixSpirit** [comment]
@htoooth 把应用的包发给我, 我看看是怎么回事吧, hxy@fir.im

**Comment by htoooth** [comment]
@NaixSpirit 直接上fir.im下载吧，我的应用是：http://fir.im/pathprint

**Comment by NaixSpirit** [comment]
@htoooth 安装 1.4.0 版本试试

**Comment by htoooth** [comment]
@NaixSpirit 安装了 1.4.1 还是不行。

**Comment by NaixSpirit** [comment]
@htoooth 我找台 windows 测下

**Comment by htoooth** [comment]
@NaixSpirit  还是不行啊，我现在的版本是 1.4.4

**Comment by NaixSpirit** [comment]
你的图标正常啊. 不是默认的黄色图标啊

**Comment by htoooth** [comment]
@NaixSpirit 我自已重新用网站传了一遍
