### ISSUE TITLE
fir build_ipa 所打包比手动打包打了几M

### ISSUE THREAD

**Issue by javenisme** [FIRHQ/fir-cli#34]
RT，fir build_ipa 所打包为：38.42M 手动打包为：36.41M，不知是为何？

**Comment by 13666012878** [comment]
谢谢

**Comment by NaixSpirit** [comment]
@javenisme 我研究研究, build_ipa 使用的是 `xcrun` 进行 archived 的

**Comment by MIyulong** [comment]
我打出的也是、不但大了，还不能运行的，不知道怎么回事的。然后用xcode手动打包出来的就能正常运行的

**Comment by cskevincs** [comment]
FIY，不知道fir-cli有没有添加bit code的命令

**Comment by NaixSpirit** [comment]
使用下面的命令可以看到 fir-cli 内部使用的 xcodebuild 命令
```sh
$DEBUG=1 fir build_ipa xxxx
```
