### ISSUE TITLE
打包远程工程

### ISSUE THREAD

**Issue by leonard0629** [FIRHQ/fir-cli#36]
fir build是否支持编译git仓库中用gradle构建的android工程？能否指定分支和版本

**Comment by NaixSpirit** [comment]
@leonard0629 你好, 这个需求不错, 我会在下一个大版本上加上该功能

**Comment by leonard0629** [comment]
好的，感觉编译远程代码仓库的需求还是非常必要的

**Comment by NaixSpirit** [comment]
@leonard0629 升级至 1.4.1 版本, enjoy.

**Comment by leonard0629** [comment]
thx, i'll try this

**Comment by NaixSpirit** [comment]
![image](https://cloud.githubusercontent.com/assets/1676616/11141949/d015bf9c-8a24-11e5-9383-30f8749efdc9.png)

**Comment by NaixSpirit** [comment]
![image](https://cloud.githubusercontent.com/assets/1676616/11141963/e96f7bfe-8a24-11e5-9508-8f4f2ada10f8.png)

**Comment by leonard0629** [comment]
i use "fir upgrade", but i can just upgrade to 1.4.0

**Comment by NaixSpirit** [comment]
估计淘宝源要20分钟后同步

**Comment by leonard0629** [comment]
ok, i'll try later. maybe u'd better add the step into readme

**Comment by NaixSpirit** [comment]
ok, i'll.
