### ISSUE TITLE
在Xcode可以正常打包，但在终端用命令行打包失败。

### ISSUE THREAD

**Issue by JianrongHui** [FIRHQ/fir-cli#38]
在Xcode可以正常打包，但在终端用命令行打包失败。
我在终端中执行以下命令：
$fir build_ipa ${WORKSPACE} -o ${WORKSPACE}/TestJenkins.ipa -p -T MY_TOKEN

编译到最后报错如下：

*\* BUILD FAILED **

The following build commands failed:
    Ld build/MyProject.build/Release-iphoneos/ZCDHPlatform.build/Objects-normal/armv7/MyProject normal armv7
(1 failure)
E, [2015-11-12T10:03:17.543515 #5998] ERROR -- : Build failed

请问为了能用命令行打包，需要在工程中作其他配置吗？

**Comment by NaixSpirit** [comment]
@JianrongHui 能把全部 build 时候的命令发给我吗? hxy@fir.im

**Comment by JianrongHui** [comment]
已经给你发邮件了。谢谢~ @NaixSpirit

**Comment by huapeng222** [comment]
我也遇到这个错误了
The following build commands failed:
	CompileC build/Ole_Chat.build/Debug-iphoneos/Ole_Chat.build/Objects-normal/armv7/AddFromContact.o Ole_Chat/ui/message/AddFromContact.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

试了下其他项目可以正常打包,就这个工程不行
fir build_ipa /Users/kameshipeng/Documents/工作/O了_work/Ole_Chat/Ole_Chat.xcodeproj -o /Users/kameshipeng/Desktop/111

**Comment by soliury** [comment]
我也遇到了，我用fir来打包https://github.com/soliury/noder-react-native

**Comment by 651893553** [comment]
我也遇到了这个问题。用的是1.5版本，请问这个现在解决了么？
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/cyou/Library/Developer/Xcode/DerivedData/QuXuan-cvnixmcteustzifnxhymfqdtlqiu/Build/Intermediates/QuXuan.build/Release-iphoneos/QuXuan.build/Objects-normal/armv7/MainViewController1.o QuXuan/View/MainView/MainViewController1.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

E, [2016-08-29T17:01:58.224767 #3914] ERROR -- : Build failed
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by Marviszhao** [comment]
@NaixSpirit  我遇到了相同的问题 ✈ fir-cli 1.5.0
The following build commands failed:
	CompileC /Users/marvis/Library/Developer/Xcode/DerivedData/LiveShow-bqsunhoccfwctycjoigqzvfwgqgt/Build/Intermediates/LiveShow.build/DebugOnlineArch-iphoneos/LiveShow.build/Objects-normal/armv7/LSPCUserInterestVC.o LiveShow/UI/PersonalCenter/ViewControllers/LSPCUserInterestVC.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by 651893553** [comment]
各位有谁解决了么？

**Comment by jaywongs** [comment]
求问有解决的吗？

**Comment by GordonLY** [comment]
求问有解决的吗？

**Comment by zjjzmw1** [comment]
我的也是同样的问题：The following build commands failed:
	CompileC /Users/zhangmingwei/Library/Developer/Xcode/DerivedData/niaoyutong-dfkbsdyldkxahudgkltbsgstbnte/Build/Intermediates.noindex/ArchiveIntermediates/niaoyutong/IntermediateBuildFilesPath/niaoyutong.build/Release-iphoneos/niaoyutong.build/Objects-normal/armv7/MessageViewController.o niaoyutong/MessageVC/MessageViewController.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by zjjzmw1** [comment]
有解决的话，在这里说下吧，谢谢了。

**Comment by PXLZHM** [comment]
我也遇到同样的问题 求解答
CompileC /Users/macserver/Library/Developer/Xcode/DerivedData/Rider-exawekdyplephweksfizyyzwnzxs/Build/Intermediates.noindex/Rider.build/Debug-iphoneos/Rider.build/Objects-normal/armv7/DAMapViewComponent.o Rider/DWeex/Plugins/DAMapViewComponent.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Build step 'Xcode' marked build as failure
Finished: FAILURE
