### ISSUE TITLE
fir -q 没有生效?

### ISSUE THREAD

**Issue by sanshanchuns** [FIRHQ/fir-cli#43]
fir build_ipa . -q -w -C Release -S licaishi CODE_SIGN_IDENTITY="....." -p

命令如上,   . 表当前目录,   -q 表示不输出, -w 表示 workspace -C 表示configuration -S 表示 scheme
-p 表示 publish

但是 -q 没有起作用? 这条命令封装的有点儿问题?

**Comment by NaixSpirit** [comment]
@sanshanchuns 你是说依然输出了 xcodebuild 在 build 时候的命令吗?

**Comment by sanshanchuns** [comment]
对,  依旧有一堆的输出, 就是 xcodebuild 在 build 时候的输出

**Comment by NaixSpirit** [comment]
试试 1.4.3 版本, 修改了获取 `Process::Status` 的方式
