### ISSUE TITLE
用jenkins执行命令打包上传后在fir上下载APP，APP无法启动直接闪退是为什么呢？

### ISSUE THREAD

**Issue by 651893553** [FIRHQ/fir-cli#44]
我使用jenkins在构建后执行fir build_ipa ${WORKSPACE}/workspace -w -S name -p -T xxxxxx  
打包上传成功了，但是我在iOS8上下载APP来直接闪退，iOS9上目前没事，但是我手动打包上传的包就没有这个问题，这是什么原因呢？

**Comment by NaixSpirit** [comment]
把用 cli 打包的 app 发我邮箱吧, hxy@fir.im

**Comment by 651893553** [comment]
已经发邮件给你了，你看一下吧！

**Comment by NaixSpirit** [comment]
已经收到

**Comment by 651893553** [comment]
昨天又发现个问题，打包成功包，在iOS9  6S Plus上ipa的安装包提示无法安装！

**Comment by NaixSpirit** [comment]
uuid 没加上吧

**Comment by 651893553** [comment]
我用的是企业版的发布证书，不需要添加udid的

**Comment by NaixSpirit** [comment]
你发给我的包, 是内测版的, 你检查一下你的证书吧

**Comment by 651893553** [comment]
使用fir build_ipa命令时必须要指定Provisioning Profile么？  我这个是设置成Automatic的 Code Signing Identity 中Debug 选择的开发证书   Release选择的是发布证书！

**Comment by NaixSpirit** [comment]
fir build_ipa 就是封装了一下 xcodebuild 的命令, 你可以先用 xcodebuild 命令试试
