### ISSUE TITLE
新Mac机 OSX 10.11 EI Capitan 按照ReadMe 安装报错

### ISSUE THREAD

**Issue by googoodalls** [FIRHQ/fir-cli#46]
似乎需要 安装 HomeBrew，还没搞定

请完善 ReadMe 的安装步骤，以方便后来人。

#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.11/x86_64/ruby-2.2.1.tar.bz2
Checking requirements for osx.
About to install Homebrew, press `Enter` for default installation in `/usr/local`,
type new path if you wish custom Homebrew installation (the path needs to be writable for user)
: Requirements installation failed with status: 1.

**Comment by googoodalls** [comment]
出现如上错误后，我需要先安装 “HomeBrew”
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by googoodalls** [comment]
请更新 ReadMe ，加上这部分描述。节省后来者时间。谢谢！

**Comment by NaixSpirit** [comment]
@googoodalls 谢谢, 已添加至 README
