### ISSUE TITLE
编译用 CocoaPods 做依赖管理的 .ipa 包 命令失败

### ISSUE THREAD

**Issue by zhuozhuo** [FIRHQ/fir-cli#47]
在工程目录下 执行 fir build_ipa path/to/workspace -w -S <scheme name>
错误提示：  parse error near `\n'
没有用CocoaPods管理的工程 工程目录下 fir build_ipa path/to/project -o path/to/output  是可以的。

**Comment by godlikeonline** [comment]
fir build_ipa path/to/workspace -w -S <scheme name>
<scheme name>你忘记了吧
