### ISSUE TITLE
ios9.1无法下载应用

### ISSUE THREAD

**Issue by fantasysea** [FIRHQ/fir-cli#48]
ios9.1无法下载应用 此时无法安装。这是什么原因呢

**Comment by NaixSpirit** [comment]
可以用这个工具查看一下 http://fir.im/tools/log_guru

**Comment by fantasysea** [comment]
不好意思啊。我的问题。我打包的时候描述文件错了。提示无法下载，然后刚刚好ios8的设备是错的那个描述文件里面的设备
