### ISSUE TITLE
请问如何做一个定时任务，每天自动打包上传

### ISSUE THREAD

**Issue by fantasysea** [FIRHQ/fir-cli#49]
本人在mac环境下。百度之后参考
http://my.oschina.net/shede333/blog/470377
写下了一个
com.may.fir.plist
------------
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.may.fir.plist</string>
    <key>ProgramArguments</key>
    <array>
        <string>/Users/cc/Desktop/test_shell.sh</string>
    </array>
    <key>KeepAlive</key>
    <false/>
    <key>RunAtLoad</key>
    <true/>
    <key>StartInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>/Users/cc/Desktop/schedule.log</string>
</dict></plist>

test_shell.sh
----------------------
#!/bin/sh

LANG=en_US.UTF-8
export LANG

svn status | xargs echo 
echo "out: 输出正确的中文"
fir login mytoken
fir build_ipa /Users/cc/Desktop/xcode/StartsMove -o /Users/cc/Desktop/xcode/inline
say hello world
echo "out: end"

这样的定时器，但是只打印了out: 输出正确的中文  和 end  say hello  也执行了，就是没执行fir的命令行。
有同样需求的吗？大家来研究一下。

**Comment by NaixSpirit** [comment]
`#!/bin/sh` 改为 `#!/bin/bash`

**Comment by fantasysea** [comment]
@NaixSpirit 刚刚试了一下，还是无法执行。但是我执行python 文件是可以的。

**Comment by NaixSpirit** [comment]
直接运行这个 shell 脚本看看报了什么错

**Comment by fantasysea** [comment]
@NaixSpirit 直接执行不报错，可以运行。感觉是定时任务没识别fir命令而直接跳过了
