### ISSUE TITLE
fir -c 不支持 \n

### ISSUE THREAD

**Issue by SuperMarioBean** [FIRHQ/fir-cli#53]
我在使用 mac 上传ipa包，申明的 -c 参数中带有 \n 换行符，但是上传之后，都被原样显示了

    fir p $WORKSPACE/build/${BUILD_NUMBER}/${YT_PROJECT_FINAL_NAME}.ipa -T ${YT_FIR_TOKEN} -c "持续化集成 ${JOB_NAME}:${BUILD_DISPLAY_NAME}(${YT_PROJECT_FINAL_NAME})\n${YT_CHANGE_LOG}" 

    持续化集成 Carmaster-iOS-Release:#15(carmaster-origin_release_v1.1.0-cf0bde93c03b0e0ede78c760588ebc01263ae497-car_master_for_test_ad_hoc)\ncf0bde9 隐藏调试使用的状态栏

**Comment by NaixSpirit** [comment]
仔细查了一下, 是 ruby 中的 ARGV 自动做了转义, 把所有 `\n` 都转义成了 `\\n`, 这边暂时不好修改, 如果想换行, 可以直接在命令行中换行或者 `-c` 后面接上 changelog 的文件
