### ISSUE TITLE
 While executing gem ... (Gem::FilePermissionError)

### ISSUE THREAD

**Issue by sauchye** [FIRHQ/fir-cli#55]
### 安装失败提示
> gem install fir-cli
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

### 解决方法
`` sudo  gem install fir-cli ``
#### 输入密码，最后安装成功。

> ➜  ~  sudo  gem install fir-cli
Password:
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: unf_ext-0.0.7.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.7.1
Fetching: unf-0.1.4.gem (100%)
Successfully installed unf-0.1.4
Fetching: domain_name-0.5.25.gem (100%)
Successfully installed domain_name-0.5.25
Fetching: http-cookie-1.0.2.gem (100%)
Successfully installed http-cookie-1.0.2
Fetching: mime-types-2.99.gem (100%)
Successfully installed mime-types-2.99
Fetching: rest-client-1.8.0.gem (100%)
Successfully installed rest-client-1.8.0
Fetching: rubyzip-1.1.7.gem (100%)
Successfully installed rubyzip-1.1.7
Fetching: ruby_android-0.7.7.gem (100%)
Successfully installed ruby_android-0.7.7
Fetching: chunky_png-1.3.5.gem (100%)
Successfully installed chunky_png-1.3.5
Fetching: rqrcode-0.8.0.gem (100%)
Successfully installed rqrcode-0.8.0
Fetching: fir-cli-1.4.5.gem (100%)

        ______________        ________    ____
       / ____/  _/ __ \      / ____/ /   /  _/
      / /_   / // /_/ /_____/ /   / /    / /
     / __/ _/ // _, _/_____/ /___/ /____/ /
    /_/   /___/_/ |_|      \____/_____/___/

  ## 更新记录
  ### fir-cli 1.4.5
  - 增加 Android flavor 打包(感谢 [msdx](https://github.com/msdx) 的热心帮助)
  - `$ fir ba <project dir> -f <flavor>`
  - 详细更新记录, 请查看: https://github.com/FIRHQ/fir-cli/blob/master/CHANGELOG
  - [fir-cli](https://github.com/FIRHQ/fir-cli) 已经开源
  - 欢迎 fork, issue 和 pull request
  
Successfully installed fir-cli-1.4.5
Parsing documentation for thor-0.19.1
Installing ri documentation for thor-0.19.1
Parsing documentation for unf_ext-0.0.7.1
Installing ri documentation for unf_ext-0.0.7.1
Parsing documentation for unf-0.1.4
Installing ri documentation for unf-0.1.4
Parsing documentation for domain_name-0.5.25
Installing ri documentation for domain_name-0.5.25
Parsing documentation for http-cookie-1.0.2
Installing ri documentation for http-cookie-1.0.2
Parsing documentation for mime-types-2.99
Installing ri documentation for mime-types-2.99
Parsing documentation for rest-client-1.8.0
Installing ri documentation for rest-client-1.8.0
Parsing documentation for rubyzip-1.1.7
Installing ri documentation for rubyzip-1.1.7
Parsing documentation for ruby_android-0.7.7
Installing ri documentation for ruby_android-0.7.7
Parsing documentation for chunky_png-1.3.5
Installing ri documentation for chunky_png-1.3.5
Parsing documentation for rqrcode-0.8.0
Installing ri documentation for rqrcode-0.8.0
Parsing documentation for fir-cli-1.4.5
Installing ri documentation for fir-cli-1.4.5
Done installing documentation for thor, unf_ext, unf, domain_name, http-cookie, mime-types, rest-client, rubyzip, ruby_android, chunky_png, rqrcode, fir-cli after 14 seconds
12 gems installed

**Comment by NaixSpirit** [comment]
![image](https://cloud.githubusercontent.com/assets/1676616/12047588/f9b2bf2c-af08-11e5-9640-da197fee6ff8.png)
