### ISSUE TITLE
Cocoapods工程 ,如果不指定-C，默认变成Debug 证书了

### ISSUE THREAD

**Issue by calvingit** [FIRHQ/fir-cli#57]
不是默认是Release的吗？害的我以为自己证书设置错误了，折腾了半天，加了-C Release就没事了
```
fir build_ipa ./ -o ./ipa -w -S test -C Release -p -T
```

**Comment by NaixSpirit** [comment]
build_ipa 实际上就是封装了 xcodebuild 的命令, 并没有做太多额外的参数处理, 如果 xcodebuild 命令需要加上 -C, 那么 build_ipa 也需要加上 -C, 我估计是你在 xcode 上的配置默认不是 release

**Comment by calvingit** [comment]
在工程设置里面确实是Release啊。xxxx.xcodeproj/project.pbxproj
```
defaultConfigurationName = Release;
```

**Comment by NaixSpirit** [comment]
`DEBUG=1 fir build_ipa ./ -o ./ipa -w -S test -C Release -p -T`
会开启 debug 模式输出封装的 xcodebuild 命令, 你试试
