### ISSUE TITLE
osx11 尝试安装fir-cli

### ISSUE THREAD

**Issue by hainuo** [FIRHQ/fir-cli#6]
安装成功后，找不到fir命令 请问fir被安装在哪里了？

**Comment by Sarah1018** [comment]
fir help 可查看全部命令 每条命令加-h 为该命令的使用方法

--
Sarah       @FIR.im

**Comment by hainuo** [comment]
@Sarah1018   回答不满意啊，因为fir这个命令找不到所以我才问fir被安装在那里，你的回答不正确，
不过我已经使用find 命令全局搜索找到了在目录
`Library/Ruby/bin/fir`
大家可以在bash中手动加入到PATH变量中

不过对于你的及时回复 还是挺感谢的
