### ISSUE TITLE
converting app's icon 特别慢

### ISSUE THREAD

**Issue by holysin** [FIRHQ/fir-cli#63]
用 fir-cli 上传在 converting app's icon 这一步特别慢

**Comment by NaixSpirit** [comment]
这个取决于你的 app 中的图片, 你的图片是不是特别大啊

**Comment by holysin** [comment]
是桌面图标吗？

**Comment by NaixSpirit** [comment]
是 app 显示的 icon
网页版也会转换, 只不过是在前端转换了

**Comment by holysin** [comment]
嗯，但是 icon 转换之后直接就上传成功了，我怀疑是icon转换成功没提示，然后把上传的 progress 也掩盖掉了
