### ISSUE TITLE
publish的时候报错

### ISSUE THREAD

**Issue by yzlhccdec** [FIRHQ/fir-cli#65]
undefined method `response' for #<SocketError:0x007fc3f454f0f0>
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.5/lib/fir/util/http.rb:16:in `rescue in get'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.5/lib/fir/util/http.rb:8:in `get'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.5/lib/fir/util.rb:36:in `fetch_user_info'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.5/lib/fir/util/publish.rb:172:in `check_supported_file_and_token'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.5/lib/fir/util/publish.rb:8:in `publish'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.5/lib/fir/cli.rb:104:in `publish'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.5/lib/fir/cli.rb:169:in `invoke_command'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.5/bin/fir:8:in `<top (required)>'
/usr/bin/fir:23:in `load'

(./scripts/deploy.sh) returned exit code 1

**Comment by NaixSpirit** [comment]
看起来像是网络问题, 是每次都报错还是就这一次?

**Comment by yzlhccdec** [comment]
之前连续报错了3次，然后好了1次。在circleci上面跑的

**Comment by NaixSpirit** [comment]
是网络错误, 我会在这里加上一个重试的策略
