### ISSUE TITLE
fir build 带apple watch os2 的项目编译失败

### ISSUE THREAD

**Issue by jackrex** [FIRHQ/fir-cli#67]
编译命令： log=`fir b ./ -o ${output_dir} -w -S ${build_scheme} 2>&1`

Log：
target specifies product type 'com.apple.product-type.watchkit2-extension', but there's no such product type for the 'iphoneos' platform

**Comment by NaixSpirit** [comment]
安装 1.4.7 版本, 然后 `fir b ./ -o ${output_dir} -w -S ${build_scheme} -d 'name=iPhone 6s' 2>&1` 试试

**Comment by jackrex** [comment]
Check dependencies
target specifies product type '\''com.apple.product-type.watchkit2-extension'\'', but there'\''s no such product type for the '\''iphonesimulator'\'' platform

**Comment by jackrex** [comment]
还是不对 。。。。  变成 '\''iphonesimulator'\'' platform这个了

**Comment by NaixSpirit** [comment]
等晚上我再看看

**Comment by NaixSpirit** [comment]
`fir b ./ -o ${output_dir} -w -S ${build_scheme} -d 'platform=iOS Simulator,name=iPhone 6s' 2>&1`

这个问题跟 fir-cli 关系不大, build_ipa 就是封装了一些 xcodebuild 参数, 其他什么都没有做处理, 如果哪个 xcodebuild 参数没封装的话, 可以继续封装

**Comment by NaixSpirit** [comment]
http://stackoverflow.com/questions/24090455/xcode-getting-target-specifies-product-type-com-apple-product-type-bundle-unit

**Comment by jackrex** [comment]
你这个是 OCUnit 的相关设置，和watchOS2 不一样， 改为 
fir b ./ -o ${output_dir} -w -S ${build_scheme} -d 'platform=iOS Simulator,name=iPhone 6s' 2>&1
或
fir b ./ -o ${output_dir} -w -S ${build_scheme} -d 'platform=iphonesimulator,name=iPhone 6s' 2>&1
依旧出现
target specifies product type '\''com.apple.product-type.watchkit2-extension'\'', but there'\''s no such product type for the '\''iphonesimulator'\'' platform

**Comment by NaixSpirit** [comment]
`DEBUG=1 fir b ./ -o ${output_dir} -w -S ${build_scheme} -d 'platform=iOS Simulator,name=iPhone 6s' 2>&1` 这样的方式可以输出 fir-cli 使用的 xcodebuild 命令
你可以看看这条 xcodebuild 命令是否缺了什么东西

**Comment by jackrex** [comment]
好像没有缺啥...
'xcodebuild build -sdk iphoneos -workspace '\''/Users/keep/.jenkins/jobs/KeepiOSWatch/workspace/Keep.xcworkspace'\'' -scheme '\''Keep'\'' -destination '\''platform=iOS Simulator,name=iPhone 6s'\''

**Comment by NaixSpirit** [comment]
如果这条命令直接编译就失败, 很可能是因为 xcode 的设置某个地方不对
看看这两个帖子对你有帮助吗?
http://stackoverflow.com/questions/31197769/target-specifies-product-type-com-apple-product-type-watchkit2-extension-but
http://stackoverflow.com/questions/31632660/target-specifies-product-type-com-apple-product-type-watchkit2-extension-but

**Comment by jackrex** [comment]
带AppleWatch 的项目可以不指定 xcodebuild build -sdk iphoneos 是 iphoneos吗，也就是如何使用fir 命令 可以达到 -sdk 是缺省的，这样编译就是用了默认工程的配置 

例如 fir b ./ -o xxx  如何对应 xcodebuild -workspace -scheme 没有 -sdk
如何做到
