### ISSUE TITLE
fir build_ipa -p  打包发布后的发布页面显示403错误 

### ISSUE THREAD

**Issue by Kenshinhu** [FIRHQ/fir-cli#68]
fir build_ipa -p  打包发布后的发布页面显示403错误

**Comment by NaixSpirit** [comment]
短链接发过来看看

**Comment by Kenshinhu** [comment]
fir.im/rn5c

当使用 fir publish 就正常
直接使用 fir build_ipa -p 就会显示403

**Comment by NaixSpirit** [comment]
是一个 bug, 1.4.6 版本新增了 -p -o 两个参数，忘记了在相应的 build 里面进行添加

**Comment by NaixSpirit** [comment]
1.4.8 版本修复
