### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by chsasaw** [FIRHQ/fir-cli#69]
上传错误是为什么？

Jenkins-Mobile:~ jenkins$ fir publish /build/outputs/apk/dorm-qa_test.apk -T #token#
I, [2016-03-03T17:33:53.029172 #13440]  INFO -- : Publishing app via xxxx_dev<>.......
I, [2016-03-03T17:33:53.029290 #13440]  INFO -- : ✈ -------------------------------------------- ✈
undefined method `name' for "\n>\n":REXML::Text
/Library/Ruby/Gems/2.0.0/gems/ruby_android-0.7.7/lib/android/manifest.rb:226:in `block in label'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rexml/parent.rb:41:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rexml/parent.rb:41:in `each'
/Library/Ruby/Gems/2.0.0/gems/ruby_android-0.7.7/lib/android/manifest.rb:226:in `find'
/Library/Ruby/Gems/2.0.0/gems/ruby_android-0.7.7/lib/android/manifest.rb:226:in `label'
/Library/Ruby/Gems/2.0.0/gems/ruby_android-0.7.7/lib/android/apk.rb:176:in `label'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.8/lib/fir/util/parser/apk.rb:26:in `basic_info'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.8/lib/fir/util/parser/apk.rb:16:in `full_info'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.8/lib/fir/util/info.rb:35:in `apk_info'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.8/lib/fir/util/publish.rb:12:in `publish'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.8/lib/fir/cli.rb:114:in `publish'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.8/lib/fir/cli.rb:179:in `invoke_command'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Library/Ruby/Gems/2.0.0/gems/fir-cli-1.4.8/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'

**Comment by NaixSpirit** [comment]
看起来像是解析 apk 失败了, 把这个 apk 的包发给我吧
email: hxy@fir.im

**Comment by NaixSpirit** [comment]
AndroidManifest.xml 第53行多了个 `>`
