### ISSUE TITLE
上传apk icon时出现一个异常

### ISSUE THREAD

**Issue by xxxifan** [FIRHQ/fir-cli#7]
/var/lib/gems/2.1.0/gems/fir-cli-1.1.0/lib/fir/patches/bin/pngcrush: 1: /var/lib/gems/2.1.0/gems/fir-cli-1.1.0/lib/fir/patches/bin/pngcrush: Syntax error: ")" unexpected

**Comment by NaixSpirit** [comment]
如果方便的话, 把 ipa 包发我邮箱吧, 我们这边需要单独对这个 ipa 包做做检测
hxy@fir.im

**Comment by xxxifan** [comment]
不好意思  是apk，也一样发吗？

**Comment by NaixSpirit** [comment]
@xxxifan apk 的话就不用了, 我这边处理一下

**Comment by xxxifan** [comment]
好吧 - - 刚刚发送    无视掉吧

**Comment by NaixSpirit** [comment]
@xxxifan 已经更新 1.1.1 版本, 如果使用国内淘宝源的话, 15分钟之后可以安装最新版.
