### ISSUE TITLE
打包怎么指定开发证书和provisioning Profile???

### ISSUE THREAD

**Issue by albertjson** [FIRHQ/fir-cli#70]
自从项目集成了cocoapods之后，打包的应用包大小是以前的两倍。最关键的是：打包之后我的开发证书就会不定期失效，请问怎么解决？
在线等

**Comment by NaixSpirit** [comment]
<img width="796" alt="2016-03-04 5 16 26" src="https://cloud.githubusercontent.com/assets/1676616/13522835/dd1ecc46-e22c-11e5-99f9-6aa87cc3a703.png">

**Comment by NaixSpirit** [comment]
如果还有什么参数需要的话, 可以再提 issue

**Comment by lkkwxy** [comment]
-f 后面应该怎么赋值啊
