### ISSUE TITLE
应用发布密码不起作用？

### ISSUE THREAD

**Issue by kinglee0120** [FIRHQ/fir-cli#71]
fir p ${WORKSPACE}/build/JLP.ipa -Q --password=xxxxx 为什么这么写，ipa包发布到fir.im后，扫描二维码安装，没有输入密码的操作的？

**Comment by NaixSpirit** [comment]
短链接发给我看看

**Comment by kinglee0120** [comment]
什么短链接？fir命令是这样加下载密码的吗？


发自 网易邮箱大师
在2016年03月09日 11:21，hxy 写道:

短链接发给我看看

**Comment by NaixSpirit** [comment]
指令是没问题, 短链接是指你发布这个 ipa 包后在 fir.im 上的链接, 或者你自己把二维码发到我邮箱也可以, 我们这边要看看具体的问题
hxy@fir.im

**Comment by NaixSpirit** [comment]
是一个 bug, 下午的新版本修正这个 bug

**Comment by kinglee0120** [comment]
好的！谢谢！


发自 网易邮箱大师
在2016年03月09日 11:37，hxy 写道:

是一个 bug, 下午的新版本修正这个 bug

**Comment by NaixSpirit** [comment]
[1.4.9](https://rubygems.org/gems/fir-cli) 版本已经修改该 bug
