### ISSUE TITLE
fir更新报错

### ISSUE THREAD

**Issue by kinglee0120** [FIRHQ/fir-cli#72]
fir更新报错
YLindeMacBook-Pro:~ Apple$ sudo fir upgrade
Password:
   Upgrade fir-cli (use `gem install fir-cli --no-ri --no-rdoc`)
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/console
请问这个应该怎么解决呢？

**Comment by kinglee0120** [comment]
环境：Mac OS 10.11
这样安装的：sudo gem install -n /usr/local/bin fir-cli --no-ri --no-rdoc

**Comment by NaixSpirit** [comment]
直接运行 `sudo gem install -n /usr/local/bin fir-cli --no-ri --no-rdoc` 就能安装最新的了
