### ISSUE TITLE
File does not exist 

### ISSUE THREAD

**Issue by winking324** [FIRHQ/fir-cli#73]
I build my workspace use command like:

fir build_ipa NAME -o NAME/Build/ -w -S NAME -p

but at the end, result is:

Results at '/var/folders/lr/rn6hnq455lldkqc_w3jy5mfh0000gn/T/d20160309-36033-1i04yqv/1457519088.ipa'

I, [2016-03-09T18:24:52.630955 #36033]  INFO -- : Build Success
I, [2016-03-09T18:24:52.631060 #36033]  INFO -- :
E, [2016-03-09T18:24:52.631196 #36033] ERROR -- : File does not exist

so, whta is wrong?

**Comment by winking324** [comment]
➜  ios git:(*) ✗ fir v
✈ fir-cli 1.4.8
➜  ios git:(*) ✗ fir me
I, [2016-03-10T11:07:15.736515 #90708]  INFO -- : Login succeed, current user's email: ***@***
I, [2016-03-10T11:07:15.736635 #90708]  INFO -- : Login succeed, current user's name: ***
I, [2016-03-10T11:07:15.736654 #90708]  INFO -- :


version and login information

**Comment by NaixSpirit** [comment]
first, use this command `fir build_ipa NAME -o NAME/Build/ -w -S NAME`, make sure the **NAME/Build/** folder have your builded app.
second, if the app don't exist in your folder, use this command `DEBUG=1 fir build_ipa NAME -o NAME/Build/ -w -S NAME` to check the first line in your terminal, the line is the xcodebuild tool command which fir-cli has used, run the command, check the xcodebuild cmd success or failed.

**Comment by winking324** [comment]
@NaixSpirit Thank you very much, but there still some problem with my building.

building .......

Results at '/var/folders/lr/rn6hnq455lldkqc_w3jy5mfh0000gn/T/d20160310-99457-1jldjtv/1457581172.ipa'

Exception `Errno::EEXIST' at /Users/*/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252 - File exists @ dir_s_mkdir - /var/folders/lr/rn6hnq455lldkqc_w3jy5mfh0000gn/T/ipa_files-1457581175/Payload

...something same as above...

Exception `Errno::ENOENT' at /Users/*/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1328 - No such file or directory @ rb_file_s_stat - /Users/*/src/SDK/demo/ios/NAME/Build/NAME-1.0-build-1.ipa

Exception `Errno::ENOENT' at /Users/*/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:527 - No such file or directory @ sys_fail2 - (/var/folders/lr/rn6hnq455lldkqc_w3jy5mfh0000gn/T/d20160310-99457-1jldjtv/1457581172.ipa, /Users/*/src/SDK/demo/ios/NAME/Build/NAME-1.0-build-1.ipa)

I, [2016-03-10T11:39:36.680680 #99457]  INFO -- : Build Success
I, [2016-03-10T11:39:36.680810 #99457]  INFO -- :

**Comment by NaixSpirit** [comment]
is the folder `NAME/Build/` exist? before you build
if it isn't exist, make it

**Comment by NaixSpirit** [comment]
the fir-cli's next version will autobuild your output folder and fix it

**Comment by winking324** [comment]
@NaixSpirit
