### ISSUE TITLE
ipa 打包成功后上传失败

### ISSUE THREAD

**Issue by 651893553** [FIRHQ/fir-cli#74]
你好  我使用fir-cli 1.48版本
问题1：fir build_ipa ${WORKSPACE}/workspace -w -S XXX -C Release -p -T xxtokenxxx这个命令打包进行上传，之前用着都没什么问题，但是最近总出现上传不成功现象报错如下：
Results at '/var/folders/03/s8g3qj_s47x5rt30s2fgb3980000gp/T/d20160310-24638-y5hc1m/1457591875.ipa' 

I, [2016-03-10T14:38:06.978109 #24638]  INFO -- : Build Success
I, [2016-03-10T14:38:06.978213 #24638]  INFO -- : 
I, [2016-03-10T14:38:07.327672 #24638]  INFO -- : Publishing app via XXXXXx.......
I, [2016-03-10T14:38:07.327719 #24638]  INFO -- : ✈ -------------------------------------------- ✈
I, [2016-03-10T14:38:08.102099 #24638]  INFO -- : Fetching XXXXXX@fir.im uploading info......
I, [2016-03-10T14:38:08.102173 #24638]  INFO -- : Uploading app: XXXX-1.1.0(Build 1.1.2)
I, [2016-03-10T14:38:08.301725 #24638]  INFO -- : Uploading app icon......
I, [2016-03-10T14:38:08.301840 #24638]  INFO -- : Converting app's icon......
I, [2016-03-10T14:38:10.038844 #24638]  INFO -- : Uploading app binary......
E, [2016-03-10T14:39:28.559959 #24638] ERROR -- : 502 Bad Gateway
I, [2016-03-10T14:39:28.560028 #24638]  INFO -- : Retry in 5 times......
E, [2016-03-10T14:39:28.560546 #24638] ERROR -- : closed stream
I, [2016-03-10T14:39:28.560567 #24638]  INFO -- : Retry in 4 times......
E, [2016-03-10T14:39:28.560833 #24638] ERROR -- : closed stream
I, [2016-03-10T14:39:28.560854 #24638]  INFO -- : Retry in 3 times......
E, [2016-03-10T14:39:28.561320 #24638] ERROR -- : closed stream
I, [2016-03-10T14:39:28.561345 #24638]  INFO -- : Retry in 2 times......
E, [2016-03-10T14:39:28.561759 #24638] ERROR -- : closed stream
I, [2016-03-10T14:39:28.561783 #24638]  INFO -- : Retry in 1 times......
E, [2016-03-10T14:39:28.562497 #24638] ERROR -- : closed stream
Build step 'Execute shell' marked build as failure
Finished: FAILURE

问题2：使用工具打包和使用Xcode打包出来的程序运行的效果不同，比如我给一个button加了圆角属性，xcode打包的app运行没有问题，但是用fir-cli打包的app运行时就没有圆角效果，烦请解答！
谢谢！

问题3.使用fir upgrade无法更新到1.4.9版本

**Comment by NaixSpirit** [comment]
问题一: 是网络问题, 我会检查我们这边的网络是否稳定
问题二: fir build_ipa 命令内部封装的是 xcodebuild 指令, 可以使用 `DEBUG=1 fir build_ipa xxx` 来查看内部的指令是不是某个参数没有设置对
问题三: 直接 `sudo gem install fir-cli` 就可以升级最新版

**Comment by 651893553** [comment]
感谢你的回复：使用 sudo gem install fir-cli 命令安装的也是1.4.8版本的
log如下：

$ sudo gem install fir-cli
Password:
Fetching: fir-cli-1.4.8.gem (100%)

        ______________        ________    ____
       / ____/  _/ __ \      / ____/ /   /  _/
      / /_   / // /_/ /_____/ /   / /    / /
     / __/ _/ // _, _/_____/ /___/ /____/ /
    /_/   /___/_/ |_|      \____/_____/___/

  ## 更新记录
  ### fir-cli 1.4.8
  - 修正 build 后直接 -p 发布的权限错误
  - 增加上传时候设置密码及公开访问权限
  - 增加 build_ipa 中的 destination 参数
  - 详细更新记录, 请查看: https://github.com/FIRHQ/fir-cli/blob/master/CHANGELOG
  - [fir-cli](https://github.com/FIRHQ/fir-cli) 已经开源
  - 欢迎 fork, issue 和 pull request

Successfully installed fir-cli-1.4.8
Parsing documentation for fir-cli-1.4.8
Installing ri documentation for fir-cli-1.4.8
Done installing documentation for fir-cli after 0 seconds
1 gem installed

**Comment by NaixSpirit** [comment]
@651893553 不客气, 看起来像是 taobao 的 gem 源没有同步啊, 换一个 gem 源就好了

```sh
$ sudo gem sources --add https://gems.ruby-china.org/ --remove https://ruby.taobao.org/
$ sudo gem install fir-cli
```
