### ISSUE TITLE
打出的包感觉怪怪的,好像不是标准包

### ISSUE THREAD

**Issue by huapeng222** [FIRHQ/fir-cli#75]
我把target都设置成release了,然后用最简单的命令
$ fir build_ipa /Users/xx/Desktop/工作xx/xx/xx.xcodeproj -o /Users/xx/Desktop/xx/xx/ipa -C Release

因为我在项目里设置了release模式下,禁用了nslog输出,装手机上看了下没有输出了,说明已经是release的包了,但是我捕获到的crash日志,里边并不是内存地址(正常的),是解析好的,
正确的打包姿势是什么,求教....

**Comment by NaixSpirit** [comment]
```sh
DEBUG=1 fir build_ipa /Users/xx/Desktop/工作xx/xx/xx.xcodeproj -o /Users/xx/Desktop/xx/xx/ipa -C Release  
```
会输出 fir-cli 使用 `xcodebuild` 的命令, 可以看看这条命令是否正确, 是否缺少了参数

**Comment by huapeng222** [comment]
xcodebuild build -sdk iphoneos -project '/Users/xx/Desktop/xx/xx/GroupV/GroupV.xcodeproj' -configuration 'Release' /Users/xx/Desktop/xx/xx/xx.xcodeproj='' TARGET_BUILD_DIR='/var/folders/7g/lbb8__t92gd7plyrmsptxvrw0000gn/T/d20160314-22834-15wppj5' CONFIGURATION_BUILD_DIR='/var/folders/7g/lbb8__t92gd7plyrmsptxvrw0000gn/T/d20160314-22834-15wppj5' DWARF_DSYM_FOLDER_PATH='/Users/xx/Desktop/xx/xx/ipa' 2>&1
