### ISSUE TITLE
能否判断上传是否成功？

### ISSUE THREAD

**Issue by HamGuy** [FIRHQ/fir-cli#76]
由于需要在成功上传后，发布测试通知邮件，有没有办法判断上传是否成功？

**Comment by NaixSpirit** [comment]
判断 `$?` 是否为0 即可

**Comment by NaixSpirit** [comment]
@HamGuy 下个版本会增加一个上传成功后的简要 app info 文件

**Comment by HamGuy** [comment]
判断 $? 是否为0

不是很明白？

**Comment by NaixSpirit** [comment]
http://stackoverflow.com/questions/7101995/what-does-if-eq-0-mean-for-shell-scripts
`$?` 就是上一条指令的返回状态码
