### ISSUE TITLE
gitlab-ci环境下fir build_ipa 命令长时间阻塞

### ISSUE THREAD

**Issue by semicoder** [FIRHQ/fir-cli#8]
```shell
fir b ${xcworkspace_path} -w -S ${scheme} -p -T ${token}
I, [2015-07-08T16:21:58.637603 #62469]  INFO -- : Building......
I, [2015-07-08T16:21:58.637639 #62469]  INFO -- : ✈ -------------------------------------------- ✈
```

**Comment by NaixSpirit** [comment]
目前测了很多遍, 没有复现, 不知道是不是个别机器的环境造成的, 暂时关闭.

**Comment by xilin** [comment]
我这使用也是这个情况，输出两行以后长时间没有响应，直到几分钟后输出结果。
我还以为就是设计成这样的。。

**Comment by EggsOfAngel** [comment]
我也是这个情况，OS X EI Capitan 版本10.11.2！长时间无响应，知道几分钟后才输出结果

**Comment by NaixSpirit** [comment]
可以开启 debug 模式看看, `DEBUG=1 fir build_ipa xxxxx` 会输出 build 时候的实际调用 xcodebuild 的命令, fir build_ipa 实际上就是调用了 xcodebuild 的命令

**Comment by EggsOfAngel** [comment]
已经是debug模式了！但只会出在分割线那里，后面的命令没有输出，直到几分钟完成后才会全打印出来

**Comment by NaixSpirit** [comment]
@EggsOfAngel 我是说你可以自己运行运行打印出来的 xcodebuild 命令

**Comment by NaixSpirit** [comment]
fir-cli 就是运行了 debug 模式开始时候打印出来的那行命令
