### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by BillZong** [FIRHQ/fir-cli#80]
```Bash
IPA_PATH=$(cat ./path.txt)
echo "ips path:${IPA_PATH}"
fir publish ${IPA_PATH} -T ******
```
I've written a shell script, and it fail with error: **File does not exist**
The path is right, the file is there, but the script won't work.
Once I used the path string, it works...

**Comment by NaixSpirit** [comment]
make sure the `IPA_PATH` is the **Absolute Path**
