### ISSUE TITLE
有没有控制 发布 开放下载的开关啊

### ISSUE THREAD

**Issue by dake** [FIRHQ/fir-cli#81]
比如。上传一个版本为 1.0.0 开放下载，再上传一个 1.0.1 也可以开放下载， 但是之前的 1.0.0 的下载就被关了。。。有没有参数可以设置之前的版本不要关闭下载？

**Comment by NaixSpirit** [comment]
暂时未开放这个 api, 我先记下了, 目前可以从网页上设置

**Comment by dake** [comment]
@NaixSpirit  此下载开关控制有迭代计划了否？ 持续集成自动打包上传，网页里那个手点的开关用不上啊。。。

**Comment by dake** [comment]
啊。。。半年过去了。。此功能还是没见反应。。。。
@NaixSpirit

**Comment by NaixSpirit** [comment]
@dake 目前我没有 fir-cli 项目的维护权限, 新功能开发可以去 fir-dev 群里寻找相关开发人员.

**Comment by dake** [comment]
又半年过去了。。。。2017
