### ISSUE TITLE
-f命令不起作用

### ISSUE THREAD

**Issue by jokefaker** [FIRHQ/fir-cli#85]
我没理解错的话，-f应该是指定profile吧？
命令如下：
fir bi -o ../build -w -C Release -S souban -p -f ./souban_inhouse.mobileprovision

但是实际编译后使用的profile还是项目中设置的profile

✈ fir-cli 1.4.5

**Comment by jokefaker** [comment]
更新到1.5.0之后xcodebuild直接报错：
命令：✗ fir bi -o ../build -w -C Release -S souban -f souban_inhouse.mobileprovision -p
error：
INFO -- : xcodebuild: error: The flag -exportArchive is required when specifying -exportProvisioningProfile.
xcodebuild: error: The flag -archivePath is required when specifying -exportArchive.

✈ fir-cli 1.5.0

**Comment by lkkwxy** [comment]
哥们，解决了吗？

**Comment by trawor** [comment]
这里cli用的是build ipa的方式，不是先归档再导出的方式，所以可以直接用原生参数： 
```
CODE_SIGN_IDENTITY="iPhone Developer: XXXXXXXXX" 
PROVISIONING_PROFILE="XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX"
```
