### ISSUE TITLE
fir upload error

### ISSUE THREAD

**Issue by hahaGitHub** [FIRHQ/fir-cli#90]
你好，在上传api时，出现这个错误（信息如下），请问如何解决呢：
I, [2016-07-05T14:37:44.090432 #24752]  INFO -- : Uploading app icon......
I, [2016-07-05T14:37:44.090559 #24752]  INFO -- : Converting app's icon......
I, [2016-07-05T14:37:46.133193 #24752]  INFO -- : Uploading app binary......
E, [2016-07-05T14:42:10.932946 #24752] ERROR -- : Broken pipe
I, [2016-07-05T14:42:10.933002 #24752]  INFO -- : Retry in 5 times......
E, [2016-07-05T14:42:10.933318 #24752] ERROR -- : closed stream
I, [2016-07-05T14:42:10.933336 #24752]  INFO -- : Retry in 4 times......
E, [2016-07-05T14:42:10.933493 #24752] ERROR -- : closed stream
I, [2016-07-05T14:42:10.933508 #24752]  INFO -- : Retry in 3 times......
E, [2016-07-05T14:42:10.933651 #24752] ERROR -- : closed stream
I, [2016-07-05T14:42:10.933666 #24752]  INFO -- : Retry in 2 times......
E, [2016-07-05T14:42:10.933800 #24752] ERROR -- : closed stream
I, [2016-07-05T14:42:10.933815 #24752]  INFO -- : Retry in 1 times......
E, [2016-07-05T14:42:10.933946 #24752] ERROR -- : closed stream

**Comment by pylee** [comment]
same issue

**Comment by zhaoyunyi** [comment]
看看是不是你填错了appToken

**Comment by zhaochangwu** [comment]
我又出现了相同的问题, 问题解决了吗
