### ISSUE TITLE
上传包生成的二维码希望能对应到版本

### ISSUE THREAD

**Issue by AloneFire** [FIRHQ/fir-cli#91]
上传包生成的二维码只对应到项目地址，不能对应到相应的版本，这样的生成保存二维码没意义，希望能根据对应二维码找到相应版本，满足自动化需求

**Comment by lych0317** [comment]
这个现在解决了吗？我也觉得这个功能挺需要的

**Comment by karosLi** [comment]
这个目前有满足吗

**Comment by karosLi** [comment]
亲测，现在已经是对应到具体的版本了。

**Comment by karosLi** [comment]
可是最近试的时候，还是有问题，二维码每次都是最新的
