### ISSUE TITLE
Fir publish 提示 400 Bad Request

### ISSUE THREAD

**Issue by wongzigii** [FIRHQ/fir-cli#94]
I, [2016-07-16T00:04:58.778551 #97231]  INFO -- : Publishing app via app<app@app.com>.......
I, [2016-07-16T00:04:58.778690 #97231]  INFO -- : ✈ ----------------------------------------
I, [2016-07-16T00:04:59.923619 #97231]  INFO -- : Fetching com.app.app@fir.im uploading info......
I, [2016-07-16T00:04:59.923696 #97231]  INFO -- : Uploading app: app-2.5.1(Build 39)
E, [2016-07-16T00:04:59.991155 #97231] ERROR -- : 400 Bad Request
I, [2016-07-16T00:04:59.991230 #97231]  INFO -- : Retry in 5 times......
E, [2016-07-16T00:05:00.059825 #97231] ERROR -- : 400 Bad Request
I, [2016-07-16T00:05:00.059894 #97231]  INFO -- : Retry in 4 times......
E, [2016-07-16T00:05:00.128952 #97231] ERROR -- : 400 Bad Request
I, [2016-07-16T00:05:00.129021 #97231]  INFO -- : Retry in 3 times......
E, [2016-07-16T00:05:00.200937 #97231] ERROR -- : 400 Bad Request
I, [2016-07-16T00:05:00.201004 #97231]  INFO -- : Retry in 2 times......
E, [2016-07-16T00:05:00.267451 #97231] ERROR -- : 400 Bad Request
I, [2016-07-16T00:05:00.267507 #97231]  INFO -- : Retry in 1 times......
E, [2016-07-16T00:05:00.338458 #97231] ERROR -- : 400 Bad Request

**Comment by pjocer** [comment]
同样遇到了这个问题，是不是fir服务器现在不稳定？麻烦确认一下
