### ISSUE TITLE
更新Pods到1.0后，pod里面并没有bundle，打包报"xxx.bundle" not found

### ISSUE THREAD

**Issue by SinCheung** [FIRHQ/fir-cli#95]
/bin/sh -c /Users/Admin/Library/Developer/Xcode/DerivedData/XXX-aktefzafmkxjbhgulfqvjknojywu/Build/Intermediates/XXX.build/Release-iphoneos/XXX.build/Script-AD31BBB6278C432B14015ABD.sh
error: Resource "/Users/Admin/Library/Developer/Xcode/DerivedData/XXX-aktefzafmkxjbhgulfqvjknojywu/Build/Products/Release-iphoneos/FSMediaPicker/FSMediaPicker.bundle" not found. Run 'pod install' to update the copy resources script.

FSMediaPicker中并没有bundle

**Comment by jiyee** [comment]
同样遇到此问题，能解决一下么？

**Comment by HaloWang** [comment]
同样的问题...求解

**Comment by zwq418** [comment]
这问题困扰我很久了，这么久了竟然还没有解决方案？

**Comment by TheCodeor** [comment]
看来是没办法解决了 大家散了吧
