### ISSUE TITLE
fir publish -c 不支持中文

### ISSUE THREAD

**Issue by BryanOne** [FIRHQ/fir-cli#96]
使用-c模式，想把change log打上去，但是发现不能出来中文

**Comment by shenandjie2011** [comment]
我也遇到这个问题，这是Bug吗？有什么解决方案没有，急等

**Comment by BryanOne** [comment]
not a bug, 修改下环境的语言

**Comment by YasinZhou** [comment]
环境的语言修改为什么啊？

**Comment by YasinZhou** [comment]
环境的语言修改成什么啊？

**Comment by YasinZhou** [comment]
我用的jenkins shell命令，修改环境语言后可以了
#!/bin/sh
#修改环境语言，否则fir上传日志中文不显示
export LANG="en_US.UTF-8"
