### ISSUE TITLE
-c命令上传文件中文乱码

### ISSUE THREAD

**Issue by xiaozhi** [FIRHQ/fir-cli#98]
fir publish "${ipaDir}${ipaName}".ipa -T ${token} -c "fir_changelog"

发布日志文件到fir上面，有中文乱码？changelog是UTF8的

**Comment by YasinZhou** [comment]
我也到的更怪异，用命令行上传的日志文件中文是正常的，用jenkins shell上传的中文都不见了

**Comment by YasinZhou** [comment]
我用的jenkins shell命令，修改环境语言后可以了
#!/bin/sh
#修改环境语言，否则fir上传日志中文不显示
export LANG="en_US.UTF-8"
